### ISSUE TITLE
ansible-container build fails with geerlingguy.apache role with /usr/bin/python: ont found

### ISSUE THREAD

**Issue by jonpugh** [ansible/ansible-container#101]
I'm working on a fork of ansible-container-examples to see if I can get a drupal site working.

I'm going to work with geerlingguy's roles, I added a playbook that just included geerlingguy.apache or geerlingguy.drupal, installed the roles manully, then on `ansible-container build` I get 

"/bin/sh: 1: /usr/bin/python: not found\n"

container.yml:

```
version: "1"
services:
  drupal:
    image: ubuntu:14.04
    
  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 'RANDOMSECUREPASSWORD12345'
      MYSQL_DATABASE: 'drupal'
      MYSQL_USER: 'drupal'
      MYSQL_PASSWORD: 'password'

registries: {}
```

main.yml:
```
# This should be your Ansible playbooks to provision your containers.
# An inventory will be automatically created using the names of the services
# from your container.yml file.
# Add any roles or other modules you'll need to this directory too.
# For many examples of roles, check out Ansible Galaxy: https://galaxy.ansible.com/


- hosts: drupal
  roles:
    - { role: geerlingguy.drupal }
```

I'm going to try and add python to the base image.
