### ISSUE TITLE
Allow setting image config options

### ISSUE THREAD

**Issue by chouseknecht** [ansible/ansible-container#116]
I think there is a way to give the user a bit more control over final image attributes. On the `docker commit ` command there is a [--change option](https://docs.docker.com/engine/reference/commandline/commit/). This allows setting  `CMD | ENTRYPOINT | ENV | EXPOSE | LABEL | ONBUILD | USER | VOLUME | WORKDIR`

This seems to map to the *conf* attribute in the *commit* method of docker-py. Therefore, it would be easy for us to add support for this. 

Here is how the docker CLI passes the *changes* to the API:  https://github.com/docker/docker/blob/7fd53f7c711474791ce4292326e0b1dc7d4d6b0f/vendor/src/github.com/docker/engine-api/client/container_commit.go. This provides the how-to we need, I think.

Thinking we implement this as a new section in our container.yml schema. See the **image_config** in the example below:

```
version: "1"
services:
  django:
    image: centos:7
    expose:
      - "8080"
    links:
      - postgresql
    command: ['/usr/bin/dumb-init', '/venv/bin/gunicorn', '-w', '2', '-b', '0.0.0.0:8080', 'example.wsgi:application']
   image_config:
     user: 1000
     workdir: /django   
   dev_overrides:
      command: ['/usr/bin/dumb-init', '/venv/bin/python', 'manage.py', 'runserver', '0.0.0.0:8080']
      volumes:
        - "$PWD:/django"
    options:
      kube:
        runAsUser: 1000
```
