### ISSUE TITLE
Infinite Recursive Child Images

### ISSUE THREAD

**Issue by darkn3rd** [ansible/ansible-container#119]
### DESCRIPTION

`ansible-container` doesn't replace the existing image and creates a child image on top of itself infinitely.  

This is particularly problematic on Mac/Win, as Docker Machine VM will start showing weird errors with `ansible-container` as it runs out of space on the VM.

### STEPS

1. `ansible-container build`
2. `ansible-container build`
3. `ansible-container build`

### ACTUAL RESULTS

Snippets using dataviz.

```bash
# First Time
└─<missing> Virtual Size: 656.9 MB
  └─abb6383ef5fe Virtual Size: 656.9 MB Tags: node:4, node:argon
    └─cb8d56eeb4a0 Virtual Size: 656.9 MB Tags: express-express:20160709174440, 
# Second Time
└─<missing> Virtual Size: 656.9 MB
  └─abb6383ef5fe Virtual Size: 656.9 MB Tags: node:argon, node:4
    └─cb8d56eeb4a0 Virtual Size: 656.9 MB Tags: express-express:20160709174440
      └─86640624eefe Virtual Size: 656.9 MB Tags: express-express:20160709190401, express-express:latest
# Third Time
└─<missing> Virtual Size: 656.9 MB
   └─abb6383ef5fe Virtual Size: 656.9 MB Tags: node:4, node:argon
     └─cb8d56eeb4a0 Virtual Size: 656.9 MB Tags: express-express:20160709174440
       └─86640624eefe Virtual Size: 656.9 MB Tags: express-express:20160709190401
         └─632a6acd58fc Virtual Size: 656.9 MB Tags: express-express:20160709190507, express-express:latest
```

### EXPECTED RESULTS

There would only be one image, the image I am building with `ansible-container` under `node:argon`.

### NOTES

In case this was important.

*main.yml*
```yaml
  tasks:
     - name: Make AppDir
       file: name=/usr/src/app state=directory recurse=true
```

*container.yml*
```yaml
version: '1'
services:
  express:
    image: node:argon
registries: {}
```
