### ISSUE TITLE
Support Mechanism for .dockerignore

### ISSUE THREAD

**Issue by darkn3rd** [ansible/ansible-container#121]
### DESCRIPTION

I have several files that I don't want copied into the container, like .git, .vagrant, node_modules/, that will significantly fatten the container, or in the case of compiled code, such as local node module like bcrypt, I would want linux node_modules, not Mac OS X version.  Please have a mechanism to .dockerignore.

In a Dockerfile, I could specify something like this

```Dockerfile
ENV APP_ROOT /usr/src/app
RUN mkdir -p ${APP_ROOT}/
COPY . ${APP_ROOT}/
```

In Ansible-container, my work around is to do something like this:

```yaml
- hosts: express
  vars:
      app_root: "/usr/src/app"
  tasks:
     - name: Make APP_ROOT direcotry
       file: name="{{ app_root }}" state=directory recurse=true
     - name: Copy Source to APP_ROOT
       copy: src="{{ lookup('pipe','dirname `pwd`') }}/" dest="{{ app_root }}"
     - name: Apply .dockerignore
       shell: /bin/cat .dockerignore | /usr/bin/xargs -n 1 rm -rf
       args:
         chdir: "{{ app_root }}"
```
