### ISSUE TITLE
/usr/local/bin/builder.sh: line 4:     5 Killed                  "$@"

### ISSUE THREAD

**Issue by nirving-versent** [ansible/ansible-container#134]
Hello,
I am getting the following when i run
```
ansible-container build 
Starting Docker Compose engine to build your images...
Attaching to ansible_ansible-container_1
Cleaning up Ansible Container builder...
Attaching to ansible_ansible-container_1
Cleaning up Ansible Container builder...
Attaching to ansible_ansible-container_1, ansible_standalone_1
ansible-container_1  | /usr/local/bin/builder.sh: line 4:     5 Killed                  "$@"
ansible_ansible-container_1 exited with code 137
Aborting on container exit...
Stopping ansible_standalone_1 ... 
```
main.yml
```
- hosts: standalone
  roles:
    - { role: oracle.jdk }
```
container.yml
```
version: "1"
services:
  # Add your containers here, specifying the base image you want to build from
  # For example:
  #
  standalone:
    image: centos:7

registries: {}
```
If I remove the `roles` then it will work.

Any ideas?

```
docker --version
Docker version 1.11.2, build b9f10c9

ansible --version
ansible 2.0.1.0
  config file = 
  configured module search path = Default w/o overrides

docker-machine --version
docker-machine version 0.7.0, build a650a40
```
