### ISSUE TITLE
ansible-container python-netaddr package is not installed

### ISSUE THREAD

**Issue by le9i0nx** [ansible/ansible-container#138]
##### ISSUE TYPE
 - Bug Report

##### container.yml 

```
version: "1"
services:
  mail:
    image: le9i0nx/ansible-role-test:ubuntu-trusty
    command: ['/sbin/init']
    volumes:
      - /var/www:/usr/share/nginx/html
```

##### main.yml 

```
- hosts: mail
  roles:
    - role: debops.auth
    - role: debops.users

- hosts: mail
  become: False

  roles:

    - role: debops.core
      tags: [ 'role::core' ]
      become: True
```

##### OS / ENVIRONMENT

```

```
##### STEPS TO REPRODUCE

```

```

##### EXPECTED RESULTS

I would like to how to manage the container assembly
make your inherited default

##### ACTUAL RESULTS
```
root@debian:~/test_doc# ansible-container build
Starting Docker Compose engine to build your images...
Attaching to ansible_ansible-container_1
Cleaning up Ansible Container builder...
No image found for tag test_doc-mail:latest, so building from scratch
Attaching to ansible_mail_1, ansible_ansible-container_1
ansible-container_1  | 
ansible-container_1  | PLAY [mail] ********************************************************************
ansible-container_1  | 
ansible-container_1  | TASK [setup] *******************************************************************
ansible-container_1  | ok: [mail]
ansible-container_1  | ERROR! python-netaddr package is not installed
ansible_ansible-container_1 exited with code 1
Aborting on container exit...
Stopping ansible_mail_1 ... done
Ansible playbook run failed.
Cleaning up Ansible Container builder..
```

```

```
