### ISSUE TITLE
rethink build specification in container.yml

### ISSUE THREAD

**Issue by dustymabe** [ansible/ansible-container#217]
There are a few issues I'd like to discuss.

- Being more explicit about what is going on in ansible-container
- allowing for users to specify what playbook file to use
- making the resulting image names from produced ansible-container images predictable
- allowing for new "build strategies" to be used in the future

I'd like to introduce the concept of a "build strategy". Currently there would exist two "build strategies": `dockerfile`, and `ansible`. The default build strategy would be `dockerfile` if a build context path was given. 
 
Here are 3 scenarios:
```
services:
  db:
    image: postgres:latest

  api:
    image: myapi:latest
    build:
        context: ./path/to/dockerfiledir/

  webui:
    image: mywebui:latest
    build:
        strategy: ansible
        from: centos:7
        playbook: ./mywebui.yml
```

1st
```
  db:
    image: postgres:latest
```

For db service in the 1st scenario, no build would occur and the postgres image would be used only at runtime (i.e. no image needs to be created).

2nd
```
  api:
    image: myapi:latest
    build:
        context: ./path/to/dockerfiledir/
```

For the api service in the 2nd scenario, we are using the `dockerfile` build strategy because we passed in the path to a directory where the Dockerfile lives. The build would execute and the resulting container image would be tagged with `myapi:latest`. A user could optionally specify `strategy: dockerfile` here if they wanted, but it is implied so the software should take care of setting that. NOTE: this case is completely compatible with docker-compose. 

3rd
```
  webui:
    image: mywebui:latest
    build:
        strategy: ansible
        from: centos:7
        playbook: ./mywebui.yml
```

For the webui service we set a build strategy of `ansible` and specify we want to use the `centos:7` image as the starting image. We also state that we want to run the playbook in `./mywebui.yml` against the container before saving it off under the `mywebui:latest` tag.

Thoughts?

**Comment by chouseknecht** [comment]
I have some thoughts on the 3rd scenario. We sort of talked about this yesterday. Hopefully I'm not *bike-shedding*. 

I agree with the specification of #3 as you have it stated. I would say that the following should also result in an `ansible` build:

```
webui:
  image: mywebui:latest
  build:
    from: centos:7
```

If we see a `build` directive that includes a `from`, then the default strategy will be `ansible`, and the playbook will default to `main.yml`. 

We also talked about adding a *build* configuration section to `container.yml`. It would make the `build` command a bit more convenient and a project more *sharable*. If I want to share my project with someone, how will they construct the `build` and `run` commands? I can document of course, but having a config section that comes with reasonable defaults that I can tweak would be more convenient.

I propose we add the following top-level section for the `ansible` strategy:

```
ansible_build:
   playbook: main.yml
   image: ansible/ansible-container:02   (or whatever the latest builder image is on Docker Hub)
   volumes:
        # list any volumes that
    entrypoint: /build.sh 
    working_dir: /
    environment:
        # list environment vars
```

The properties in this section will match the `ansible-container` service properties we use today, and anything found in this section will override the defaults we have coded into the current compose template for the `build` command.
