### ISSUE TITLE
Fix su with docker connection plugin

### ISSUE THREAD

**Issue by chouseknecht** [ansible/ansible-container#237]
This seems to still be broken. Trying to run the following:

```
- name: Create DB
  hosts: postgres
  become: yes
  become_method: su
  become_user: postgres
  gather_facts: no
  tasks:
    - postgresql_db:
        name: "{{ postgres_db_name }}"
        login_user: :{{ postgres_username }}"
        login_password: :{{ postgres_password }}"
        encoding: UTF-8
```

But I get: "msg": "Internal Error: this connection module does not support running commands via su"

I came across the following lightweight command that does exactly what we need: 

https://github.com/ncopa/su-exec

Wondering if we can hook this into the connection plugin.
