### ISSUE TITLE
ansible-container push with roles

### ISSUE THREAD

**Issue by bonovoxly** [ansible/ansible-container#255]
##### ISSUE TYPE

 - Bug Report

##### container.yml 

```
version: "1"
services:
  # Add your containers here, specifying the base image you want to build from
  # For example:
  #
  # web:
  #   image: ubuntu:trusty
  #   ports:
  #     - "80:80"
  #   command: ['/usr/bin/dumb-init', '/usr/sbin/apache2ctl', '-D', 'FOREGROUND']
  #   dev_overrides:
  #     environment:
  #       - "DEBUG=1"
  #
  generaldev:
    image: ubuntu:16.04
registries: {}
  # Add optional registries used for deployment. For example:
  #  google:
  #    url: https://gcr.io
  #    namespace: my-cool-project-xxxxxx

```

##### main.yml 

```
# This should be your Ansible playbooks to provision your containers.
# An inventory will be automatically created using the names of the services
# from your container.yml file.
# Add any roles or other modules you'll need to this directory too.
# For many examples of roles, check out Ansible Galaxy: https://galaxy.ansible.com/
#
# - hosts: all
#   gather_facts: false
#   tasks:
#     - raw: which python || apt-get update
#     - raw: (which python && which aptitude) || apt-get install -y python python-apt aptitude
# - hosts: web
#   tasks:
#     - name: Upgrade APT
#       apt: upgrade=yes
#     - name: Install ca-certificates
#       apt: name=ca-certificates state=latest
#     - name: Install dumb-init
#       apt: deb=https://github.com/Yelp/dumb-init/releases/download/v1.0.2/dumb-init_1.0.2_amd64.deb
#     - name: Install Apache
#       apt: name=apache2 state=latest

# all development containers need certain packages.
- hosts: generaldev
  gather_facts: false

  vars_files:
    - vars/dev.yml

  roles:
    - role: ubuntu.raw_install_python
    - role: instance.packages
```

##### OS / ENVIRONMENT

```
Ansible Container, version 0.2.0-pre
Darwin, L000159.local, 15.6.0, Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64, x86_64
2.7.10 (default, Sep 23 2015, 04:34:21)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)] /Users/williamcawthra/gits/personal/playbook/ansible-container/env/bin/python
No DOCKER_HOST environment variable found. Assuming UNIX socket at /var/run/docker.sock
{u'Architecture': u'x86_64',
 u'BridgeNfIp6tables': True,
 u'BridgeNfIptables': True,
 u'CPUSet': True,
 u'CPUShares': True,
 u'CgroupDriver': u'cgroupfs',
 u'ClusterAdvertise': u'',
 u'ClusterStore': u'',
 u'Containers': 3,
 u'ContainersPaused': 0,
 u'ContainersRunning': 1,
 u'ContainersStopped': 2,
 u'CpuCfsPeriod': True,
 u'CpuCfsQuota': True,
 u'Debug': True,
 u'DefaultRuntime': u'default',
 u'DockerRootDir': u'/var/lib/docker',
 u'Driver': u'aufs',
 u'DriverStatus': [[u'Root Dir', u'/var/lib/docker/aufs'],
                   [u'Backing Filesystem', u'extfs'],
                   [u'Dirs', u'100'],
                   [u'Dirperm1 Supported', u'true']],
 u'ExecutionDriver': u'',
 u'ExperimentalBuild': True,
 u'HttpProxy': u'',
 u'HttpsProxy': u'',
 u'ID': u'CGC2:5N4B:X6IO:CYMM:YW6D:TGMD:LLNA:FSUD:RHSC:NHIZ:QQZS:HXLQ',
 u'IPv4Forwarding': True,
 u'Images': 70,
 u'IndexServerAddress': u'https://index.docker.io/v1/',
 u'KernelMemory': True,
 u'KernelVersion': u'4.4.13-moby',
 u'Labels': None,
 u'LoggingDriver': u'json-file',
 u'MemTotal': 4141019136,
 u'MemoryLimit': True,
 u'NCPU': 4,
 u'NEventsListener': 119,
 u'NFd': 143,
 u'NGoroutines': 388,
 u'Name': u'moby',
 u'NoProxy': u'',
 u'OSType': u'linux',
 u'OomKillDisable': True,
 u'OperatingSystem': u'Alpine Linux v3.4',
 u'Plugins': {u'Authorization': None,
              u'Network': [u'host', u'overlay', u'null', u'bridge'],
              u'Volume': [u'local']},
 u'RegistryConfig': {u'IndexConfigs': {u'docker.io': {u'Mirrors': None,
                                                      u'Name': u'docker.io',
                                                      u'Official': True,
                                                      u'Secure': True}},
                     u'InsecureRegistryCIDRs': [u'127.0.0.0/8'],
                     u'Mirrors': None},
 u'Runtimes': {u'default': {u'path': u'docker-runc'}},
 u'SecurityOptions': [u'seccomp'],
 u'ServerVersion': u'1.12.0-rc2',
 u'SwapLimit': True,
 u'Swarm': {u'CACertHash': u'',
            u'ControlAvailable': False,
            u'Error': u'',
            u'LocalNodeState': u'inactive',
            u'Managers': 0,
            u'NodeID': u'',
            u'Nodes': 0,
            u'RemoteManagers': None},
 u'SystemStatus': None,
 u'SystemTime': u'2016-09-27T02:38:09.895844196Z'}
{u'ApiVersion': u'1.24',
 u'Arch': u'amd64',
 u'BuildTime': u'2016-06-17T22:09:20.440355664+00:00',
 u'Experimental': True,
 u'GitCommit': u'a7119de',
 u'GoVersion': u'go1.6.2',
 u'KernelVersion': u'4.4.13-moby',
 u'Os': u'linux',
 u'Version': u'1.12.0-rc2'}
```
##### SUMMARY
When using roles (which works fine with `ansible-container build`), the `push` functionality seems broken.  

When running push, you'll eventually hit the following error:

```
ansible-container_1  | Host generaldev failed
ansible-container_1  | ERROR! the role 'ubuntu.raw_install_python' was not found in /ansible-container/ansible/roles:/ansible-container/ansible:/roles
ansible-container_1  |
ansible-container_1  | The error appears to have been in '/ansible-container/ansible/main.yml': line 31, column 7, but may
ansible-container_1  | be elsewhere in the file depending on the exact syntax problem.
ansible-container_1  |
ansible-container_1  | The offending line appears to be:
ansible-container_1  |
ansible-container_1  |   roles:
ansible-container_1  |     - role: ubuntu.raw_install_python
ansible-container_1  |       ^ here
ansible-container_1  |
ansible_ansible-container_1 exited with code 1
```

It also seems odd that during a push, the playbook is run. It is very possible I am mis-using this feature/functionality.

##### STEPS TO REPRODUCE

Create a playbook with a role. You can build the container like so:

```
ansible-container --debug build --with-volumes /path/to/your/ansible/roles:/roles
```

After a successful build, pushing will generate the error:

```
ansible-container --debug push
```

##### EXPECTED RESULTS

I expected a successful push (if the registry is configured properly or if `--push-to` is used) or an error that did NOT involve the use of Ansible roles.

##### ACTUAL RESULTS

`ansible-container` errors saying it cannot find the role:

```
ansible-container_1  | Host generaldev failed
ansible-container_1  | ERROR! the role 'ubuntu.raw_install_python' was not found in /ansible-container/ansible/roles:/ansible-container/ansible:/roles
ansible-container_1  |
ansible-container_1  | The error appears to have been in '/ansible-container/ansible/main.yml': line 31, column 7, but may
ansible-container_1  | be elsewhere in the file depending on the exact syntax problem.
ansible-container_1  |
ansible-container_1  | The offending line appears to be:
ansible-container_1  |
ansible-container_1  |   roles:
ansible-container_1  |     - role: ubuntu.raw_install_python
ansible-container_1  |       ^ here
ansible-container_1  |
ansible_ansible-container_1 exited with code 1
```
