### ISSUE TITLE
ansible-container push read time out

### ISSUE THREAD

**Issue by bonovoxly** [ansible/ansible-container#263]
##### ISSUE TYPE

 - Bug Report

##### container.yml 

```
version: "1"
services:
  # Add your containers here, specifying the base image you want to build from
  # For example:
  #
  # web:
  #   image: ubuntu:trusty
  #   ports:
  #     - "80:80"
  #   command: ['/usr/bin/dumb-init', '/usr/sbin/apache2ctl', '-D', 'FOREGROUND']
  #   dev_overrides:
  #     environment:
  #       - "DEBUG=1"
  #
  generaldev:
    image: ubuntu:16.04
registries:
  docker:
    url: https://hub.docker.com
    namespace: bcawthra
  # Add optional registries used for deployment. For example:
  #  google:
  #    url: https://gcr.io
  #    namespace: my-cool-project-xxxxxx

```

##### main.yml 

```
# This should be your Ansible playbooks to provision your containers.
# An inventory will be automatically created using the names of the services
# from your container.yml file.
# Add any roles or other modules you'll need to this directory too.
# For many examples of roles, check out Ansible Galaxy: https://galaxy.ansible.com/
#
# - hosts: all
#   gather_facts: false
#   tasks:
#     - raw: which python || apt-get update
#     - raw: (which python && which aptitude) || apt-get install -y python python-apt aptitude
# - hosts: web
#   tasks:
#     - name: Upgrade APT
#       apt: upgrade=yes
#     - name: Install ca-certificates
#       apt: name=ca-certificates state=latest
#     - name: Install dumb-init
#       apt: deb=https://github.com/Yelp/dumb-init/releases/download/v1.0.2/dumb-init_1.0.2_amd64.deb
#     - name: Install Apache
#       apt: name=apache2 state=latest

# all development containers need certain packages.
- hosts: generaldev
  gather_facts: false

  vars_files:
    - vars/dev.yml

  roles:
    - role: ubuntu.raw_install_python
    - role: instance.packages
```

##### OS / ENVIRONMENT

```
Ansible Container, version 0.2.0-pre
Darwin, L000159.local, 15.6.0, Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64, x86_64
2.7.10 (default, Sep 23 2015, 04:34:21)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)] /Users/williamcawthra/gits/personal/playbook/ansible-container/env/bin/python
No DOCKER_HOST environment variable found. Assuming UNIX socket at /var/run/docker.sock
{u'Architecture': u'x86_64',
 u'BridgeNfIp6tables': True,
 u'BridgeNfIptables': True,
 u'CPUSet': True,
 u'CPUShares': True,
 u'CgroupDriver': u'cgroupfs',
 u'ClusterAdvertise': u'',
 u'ClusterStore': u'',
 u'Containers': 3,
 u'ContainersPaused': 0,
 u'ContainersRunning': 0,
 u'ContainersStopped': 3,
 u'CpuCfsPeriod': True,
 u'CpuCfsQuota': True,
 u'Debug': True,
 u'DefaultRuntime': u'default',
 u'DockerRootDir': u'/var/lib/docker',
 u'Driver': u'aufs',
 u'DriverStatus': [[u'Root Dir', u'/var/lib/docker/aufs'],
                   [u'Backing Filesystem', u'extfs'],
                   [u'Dirs', u'100'],
                   [u'Dirperm1 Supported', u'true']],
 u'ExecutionDriver': u'',
 u'ExperimentalBuild': True,
 u'HttpProxy': u'',
 u'HttpsProxy': u'',
 u'ID': u'R4I5:GYYH:I5IM:PGQ4:OZGA:NA5J:XRSC:OSZ5:ZVP5:QC5U:PMEL:EKCA',
 u'IPv4Forwarding': True,
 u'Images': 70,
 u'IndexServerAddress': u'https://index.docker.io/v1/',
 u'KernelMemory': True,
 u'KernelVersion': u'4.4.13-moby',
 u'Labels': None,
 u'LoggingDriver': u'json-file',
 u'MemTotal': 4141019136,
 u'MemoryLimit': True,
 u'NCPU': 4,
 u'NEventsListener': 8,
 u'NFd': 32,
 u'NGoroutines': 55,
 u'Name': u'moby',
 u'NoProxy': u'',
 u'OSType': u'linux',
 u'OomKillDisable': True,
 u'OperatingSystem': u'Alpine Linux v3.4',
 u'Plugins': {u'Authorization': None,
              u'Network': [u'overlay', u'null', u'bridge', u'host'],
              u'Volume': [u'local']},
 u'RegistryConfig': {u'IndexConfigs': {u'docker.io': {u'Mirrors': None,
                                                      u'Name': u'docker.io',
                                                      u'Official': True,
                                                      u'Secure': True}},
                     u'InsecureRegistryCIDRs': [u'127.0.0.0/8'],
                     u'Mirrors': None},
 u'Runtimes': {u'default': {u'path': u'docker-runc'}},
 u'SecurityOptions': [u'seccomp'],
 u'ServerVersion': u'1.12.0-rc2',
 u'SwapLimit': True,
 u'Swarm': {u'CACertHash': u'',
            u'ControlAvailable': False,
            u'Error': u'',
            u'LocalNodeState': u'inactive',
            u'Managers': 0,
            u'NodeID': u'',
            u'Nodes': 0,
            u'RemoteManagers': None},
 u'SystemStatus': None,
 u'SystemTime': u'2016-09-29T00:56:09.349066457Z'}
{u'ApiVersion': u'1.24',
 u'Arch': u'amd64',
 u'BuildTime': u'2016-06-17T22:09:20.440355664+00:00',
 u'Experimental': True,
 u'GitCommit': u'a7119de',
 u'GoVersion': u'go1.6.2',
 u'KernelVersion': u'4.4.13-moby',
 u'Os': u'linux',
 u'Version': u'1.12.0-rc2'}
```
##### SUMMARY

The `ansible-container push` is not successful and takes multiple attempts to push an image.  It may or may not have to do with hub.docker.com.

##### STEPS TO REPRODUCE

Create an image.  Push the image:

```
ansible-container --debug push --with-volumes /path/to/your/ansible/roles:/roles
```

It may take multiple attempts to push.

##### EXPECTED RESULTS

A successful push.

##### ACTUAL RESULTS

The push will "timeout", with the following error as an example:

```
Pushing bcawthra/ansible-container-generaldev:20160927121448...
The push refers to a repository [docker.io/bcawthra/ansible-container-generaldev]
Preparing
Retrying in 1 second
Waiting
Pushing
Layer already exists
Pushing
Layer already exists
Pushing
UnixHTTPConnectionPool(host='localhost', port=None): Read timed out.
Traceback (most recent call last):
  File "/Users/williamcawthra/gits/personal/playbook/ansible-container/ansible-container/container/cli.py", line 206, in commandline
    getattr(engine, u'cmdrun_{}'.format(args.subcommand))(**vars(args))
  File "/Users/williamcawthra/gits/personal/playbook/ansible-container/ansible-container/container/engine.py", line 384, in cmdrun_push
    engine_obj.push_latest_image(host, url=url, namespace=namespace)
  File "/Users/williamcawthra/gits/personal/playbook/ansible-container/ansible-container/container/docker/engine.py", line 715, in push_latest_image
    for data in stream:
  File "/Users/williamcawthra/gits/personal/playbook/ansible-container/env/lib/python2.7/site-packages/docker_py-1.8.0-py2.7.egg/docker/client.py", line 225, in _stream_helper
    data = reader.read(1)
  File "/Users/williamcawthra/gits/personal/playbook/ansible-container/env/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/packages/urllib3/response.py", line 258, in read
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out.
```

As you can see, this wasn't the first push.  

This COULD be a network issue;  but this has happened on different networks.
