### ISSUE TITLE
install python when copy fails with "module failure"

### ISSUE THREAD

**Issue by MaxiReglisse** [ansible/ansible-container#264]
same problem as "Copy module failure in 2.20 #15721", but i found a different work around : i install python in the container, but i need to do that only one time, because everything falls into place after this first and unique installation.

##### ISSUE TYPE

 - Bug Report

##### container.yml 
```
version: "1"
services:
  ldap:
    image: dinkel/openldap
    entrypoint: /docker-entrypoint.sh
    command: [ "slapd", "-d", "32768", "-u", "openldap", "-g", "openldap" ]
    environment:
      - SLAPD_PASSWORD=secret
      - SLAPD_DOMAIN=georchestra.org
      - SLAPD_ADDITIONAL_MODULES=groupofmembers

registries: {}
```

##### main.yml 
```
- hosts: ldap
  gather_facts: no
  vars:
  tasks:
    - name: Update all packages 
      raw: apt-get update
    - name: Install ldap-utils
      raw: apt-get install -y ldap-utils
#    - name: Install python 
#      raw: apt-get install -y python python-apt
    - name: Copy groupofmembers.ldif
      copy: src=../groupofmembers.ldif dest=/etc/ldap.dist/modules owner=root group=root mode=0775
    - name: Copy member.ldif
      copy: src=../memberof.ldif dest=/tmp owner=openldap group=openldap mode=0775
    - name: Copy georchestra.ldif
      copy: src=../georchestra.ldif dest=/tmp owner=openldap group=openldap mode=0775
    - name: Copy groupofmembers.ldif
      copy: src=../groupofmembers.ldif dest=/etc/ldap.dist/modules/ owner=openldap group=openldap mode=0775
    - name: Create docker-entrypoint.d directory
      file: path=/docker-entrypoint.d state=directory owner=root group=root mode=0755
    #- name: Copy docker-entrypoint.d/*
    #  copy: src=../docker/docker-entrypoint.d/* dest=/docker-entrypoint.d/ owner=root group=root mode=0775
    # ne fonctionne pas. on copie le fichier.
    - name: Copy 00-populate
      copy: src=../docker/docker-entrypoint.d/00-populate dest=/docker-entrypoint.d/ owner=root group=root mode=0775
    - name: Copy docker-entrypoint.sh
      copy: src=../docker/docker-entrypoint.sh dest=/ owner=root group=root mode=0775
```

##### OS / ENVIRONMENT

```
Ansible Container, version 0.2.0-pre
Linux, service-info12, 4.4.0-38-generic, #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016, x86_64
2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609] /usr/bin/python
No DOCKER_HOST environment variable found. Assuming UNIX socket at /var/run/docker.sock
{u'Architecture': u'x86_64',
 u'BridgeNfIp6tables': True,
 u'BridgeNfIptables': True,
 u'CPUSet': True,
 u'CPUShares': True,
 u'CgroupDriver': u'cgroupfs',
 u'ClusterAdvertise': u'',
 u'ClusterStore': u'',
 u'Containers': 0,
 u'ContainersPaused': 0,
 u'ContainersRunning': 0,
 u'ContainersStopped': 0,
 u'CpuCfsPeriod': True,
 u'CpuCfsQuota': True,
 u'Debug': False,
 u'DefaultRuntime': u'runc',
 u'DockerRootDir': u'/var/lib/docker',
 u'Driver': u'aufs',
 u'DriverStatus': [[u'Root Dir', u'/var/lib/docker/aufs'],
                   [u'Backing Filesystem', u'extfs'],
                   [u'Dirs', u'16'],
                   [u'Dirperm1 Supported', u'true']],
 u'ExecutionDriver': u'',
 u'ExperimentalBuild': False,
 u'HttpProxy': u'',
 u'HttpsProxy': u'',
 u'ID': u'BHTK:32FH:RA6Z:TGCE:S3FJ:KRDY:IP3Y:NWMH:5V3N:B3X5:H23M:WG2A',
 u'IPv4Forwarding': True,
 u'Images': 4,
 u'IndexServerAddress': u'https://index.docker.io/v1/',
 u'KernelMemory': True,
 u'KernelVersion': u'4.4.0-38-generic',
 u'Labels': None,
 u'LiveRestoreEnabled': False,
 u'LoggingDriver': u'json-file',
 u'MemTotal': 33679785984,
 u'MemoryLimit': True,
 u'NCPU': 8,
 u'NEventsListener': 2,
 u'NFd': 41,
 u'NGoroutines': 55,
 u'Name': u'service-info12',
 u'NoProxy': u'',
 u'OSType': u'linux',
 u'OomKillDisable': True,
 u'OperatingSystem': u'Ubuntu 16.04.1 LTS',
 u'Plugins': {u'Authorization': None,
              u'Network': [u'host', u'overlay', u'null', u'bridge'],
              u'Volume': [u'local']},
 u'RegistryConfig': {u'IndexConfigs': {u'docker.io': {u'Mirrors': None,
                                                      u'Name': u'docker.io',
                                                      u'Official': True,
                                                      u'Secure': True}},
                     u'InsecureRegistryCIDRs': [u'127.0.0.0/8'],
                     u'Mirrors': None},
 u'Runtimes': {u'runc': {u'path': u'docker-runc'}},
 u'SecurityOptions': [u'apparmor', u'seccomp'],
 u'ServerVersion': u'1.12.1',
 u'SwapLimit': False,
 u'Swarm': {u'Cluster': {u'CreatedAt': u'0001-01-01T00:00:00Z',
                         u'ID': u'',
                         u'Spec': {u'CAConfig': {},
                                   u'Dispatcher': {},
                                   u'Orchestration': {},
                                   u'Raft': {},
                                   u'TaskDefaults': {}},
                         u'UpdatedAt': u'0001-01-01T00:00:00Z',
                         u'Version': {}},
            u'ControlAvailable': False,
            u'Error': u'',
            u'LocalNodeState': u'inactive',
            u'Managers': 0,
            u'NodeAddr': u'',
            u'NodeID': u'',
            u'Nodes': 0,
            u'RemoteManagers': None},
 u'SystemStatus': None,
 u'SystemTime': u'2016-09-29T15:08:14.554075479+02:00'}
{u'ApiVersion': u'1.24',
 u'Arch': u'amd64',
 u'BuildTime': u'2016-08-18T05:33:38.359262265+00:00',
 u'GitCommit': u'23cf638',
 u'GoVersion': u'go1.6.3',
 u'KernelVersion': u'4.4.0-38-generic',
 u'Os': u'linux',
 u'Version': u'1.12.1'}
```
##### SUMMARY
it is necessary to install python in the container, just one time, when you want to build an image in which i need to copy a file.

##### Fisrt build

ansible-container will fail when it will try to copy a file.
my docker environment has been cleaned : no container, no image, no volume.
and lines concerning python are commented : 
```
#    - name: Install python 
#      raw: apt-get install -y python python-apt
```
```
$ ansible-container build
No DOCKER_HOST environment variable found. Assuming UNIX socket at /var/run/docker.sock
Starting Docker Compose engine to build your images...
0.2: Pulling from ansible/ansible-container-builder
8d30e94188e7: Pull complete
24cbd75f8b32: Pull complete
d6ee161b4be5: Pull complete
a4b49951d8df: Pull complete
853ec44630ce: Pull complete
b7e98f774514: Pull complete
d787669f451c: Pull complete
250fdf0b77c5: Pull complete
33400106458e: Pull complete
Digest: sha256:ecbf2feee8cfa0b4167ca1bb74bfff62f61c3e7009b048f239da13db3806bc6b
Status: Downloaded newer image for ansible/ansible-container-builder:0.2
Attaching to ansible_ansible-container_1
Cleaning up Ansible Container builder...
No image found for tag geosync-ldap:latest, so building from scratch
latest: Pulling from dinkel/openldap
6a5a5368e0c2: Pull complete
972589a83202: Pull complete
d13470039f58: Pull complete
12de2abf2c7a: Pull complete
07f52b3e71ee: Pull complete
Digest: sha256:4b59b367643c101f2fc854ca18896402ea263e533105a703884bfaeee5e57c77
Status: Downloaded newer image for dinkel/openldap:latest
Attaching to ansible_ldap_1, ansible_ansible-container_1
ansible-container_1  | Host ldap running
ansible-container_1  | 
ansible-container_1  | PLAY [ldap] ********************************************************************
ansible-container_1  | 
ansible-container_1  | TASK [Update all packages] *****************************************************
ansible-container_1  | ok: [ldap]
ansible-container_1  | 
ansible-container_1  | TASK [Install ldap-utils] ******************************************************
ansible-container_1  | ok: [ldap]
ansible-container_1  | 
ansible-container_1  | TASK [Copy groupofmembers.ldif] ************************************************
ansible-container_1  | fatal: [ldap]: FAILED! => {"failed": true, "msg": "Failed to get information on remote file (/etc/ldap.dist/modules): MODULE FAILURE"}
ansible-container_1  | 
ansible-container_1  | NO MORE HOSTS LEFT *************************************************************
ansible-container_1  | 
ansible-container_1  | PLAY RECAP *********************************************************************
ansible-container_1  | ldap                       : ok=2    changed=0    unreachable=0    failed=1   
ansible-container_1  |  [WARNING]: Could not create retry file 'main.retry'.         [Errno 2] No such
ansible-container_1  | file or directory: ''
ansible-container_1  | 
ansible_ansible-container_1 exited with code 1
Aborting on container exit...
Stopping ansible_ldap_1 ... done
Ansible playbook run failed.
Cleaning up Ansible Container builder...
Ansible build failed
```
##### Second build
i modify main.yml, uncommenting the two lines concerning python : 

    - name: Install python 
      raw: apt-get install -y python python-apt

i rebuild the image, ansible-container will be OK now.
```
$ ansible-container build
No DOCKER_HOST environment variable found. Assuming UNIX socket at /var/run/docker.sock
Starting Docker Compose engine to build your images...
Attaching to ansible_ansible-container_1
Cleaning up Ansible Container builder...
No image found for tag geosync-ldap:latest, so building from scratch
Attaching to ansible_ansible-container_1, ansible_ldap_1
ansible-container_1  | Host ldap running
ansible-container_1  | 
ansible-container_1  | PLAY [ldap] ********************************************************************
ansible-container_1  | 
ansible-container_1  | TASK [Update all packages] *****************************************************
ansible-container_1  | ok: [ldap]
ansible-container_1  | 
ansible-container_1  | TASK [Install ldap-utils] ******************************************************
ansible-container_1  | ok: [ldap]
ansible-container_1  | 
ansible-container_1  | TASK [Install python] **********************************************************
ansible-container_1  | ok: [ldap]
ansible-container_1  | 
ansible-container_1  | TASK [Copy groupofmembers.ldif] ************************************************
ansible-container_1  | changed: [ldap]
ansible-container_1  | 
ansible-container_1  | TASK [Copy member.ldif] ********************************************************
ansible-container_1  | changed: [ldap]
ansible-container_1  | 
ansible-container_1  | TASK [Copy georchestra.ldif] ***************************************************
ansible-container_1  | changed: [ldap]
ansible-container_1  | 
ansible-container_1  | TASK [Copy groupofmembers.ldif] ************************************************
ansible-container_1  | changed: [ldap]
ansible-container_1  | 
ansible-container_1  | TASK [Create docker-entrypoint.d directory] ************************************
ansible-container_1  | changed: [ldap]
ansible-container_1  | 
ansible-container_1  | TASK [Copy 00-populate] ********************************************************
ansible-container_1  | changed: [ldap]
ansible-container_1  | 
ansible-container_1  | TASK [Copy docker-entrypoint.sh] ***********************************************
ansible-container_1  | changed: [ldap]
ansible-container_1  | 
ansible-container_1  | PLAY RECAP *********************************************************************
ansible-container_1  | ldap                       : ok=10   changed=7    unreachable=0    failed=0   
ansible-container_1  | 
ansible_ansible-container_1 exited with code 0
Aborting on container exit...
Stopping ansible_ldap_1 ... done
Exporting built containers as images...
Committing image...
Exported geosync-ldap with image ID sha256:0c4f1d4c2e5a214069c44d8cafb47e6cdf5d1b94da6fb28bb02f2a56b9e8ef01
Cleaning up ldap build container...
Cleaning up Ansible Container builder...
```
##### Third build
now, i can comment the two lines concerning python, they are no more necessary, and the build will be OK !
```
#    - name: Install python 
#      raw: apt-get install -y python python-apt
```

```
$ ansible-container build
No DOCKER_HOST environment variable found. Assuming UNIX socket at /var/run/docker.sock
Starting Docker Compose engine to build your images...
Attaching to ansible_ansible-container_1
Cleaning up Ansible Container builder...
Attaching to ansible_ansible-container_1, ansible_ldap_1
ansible-container_1  | Host ldap running
ansible-container_1  | 
ansible-container_1  | PLAY [ldap] ********************************************************************
ansible-container_1  | 
ansible-container_1  | TASK [Update all packages] *****************************************************
ansible-container_1  | ok: [ldap]
ansible-container_1  | 
ansible-container_1  | TASK [Install ldap-utils] ******************************************************
ansible-container_1  | ok: [ldap]
ansible-container_1  | 
ansible-container_1  | TASK [Copy groupofmembers.ldif] ************************************************
ansible-container_1  | changed: [ldap]
ansible-container_1  | 
ansible-container_1  | TASK [Copy member.ldif] ********************************************************
ansible-container_1  | ok: [ldap]
ansible-container_1  | 
ansible-container_1  | TASK [Copy georchestra.ldif] ***************************************************
ansible-container_1  | ok: [ldap]
ansible-container_1  | 
ansible-container_1  | TASK [Copy groupofmembers.ldif] ************************************************
ansible-container_1  | changed: [ldap]
ansible-container_1  | 
ansible-container_1  | TASK [Create docker-entrypoint.d directory] ************************************
ansible-container_1  | ok: [ldap]
ansible-container_1  | 
ansible-container_1  | TASK [Copy 00-populate] ********************************************************
ansible-container_1  | ok: [ldap]
ansible-container_1  | 
ansible-container_1  | TASK [Copy docker-entrypoint.sh] ***********************************************
ansible-container_1  | ok: [ldap]
ansible-container_1  | 
ansible-container_1  | PLAY RECAP *********************************************************************
ansible-container_1  | ldap                       : ok=9    changed=2    unreachable=0    failed=0   
ansible-container_1  | 
ansible_ansible-container_1 exited with code 0
Aborting on container exit...
Stopping ansible_ldap_1 ... done
Exporting built containers as images...
Committing image...
Exported geosync-ldap with image ID sha256:34321d62f0cc6df319e51940528ea411676a4c7eaa765cf99ebbc4dfca265a6d
Cleaning up ldap build container...
Cleaning up Ansible Container builder...
```
and so on for the future builds...
i just need to install python one time and everything falls into place.

remember: you need to erase everything before testing that.
```
docker rm -f $(docker ps -a -q) && docker rmi -f $(docker images -q) && docker volume rm `docker volume ls -q` && docker ps -a | cut -c-12 | xargs docker rm
```

I restarted 3 times before describing the problem here...

hope it helps,

Ernest.

**Comment by chouseknecht** [comment]
Rather than commenting out the task to install python, you could make it conditional. For example, the following will only install python if a simple one line programs fails to execute:

```
---
- hosts: all
  gather_facts: false
  tasks:
    - name: Update all packages
      raw: apt-get update

    - raw: python -c "print 'hello world'"
      register: output
      ignore_errors: yes

    - name: Install python
      raw: apt-get install -y python python-apt
      when: output.rc != 0

    - name: Install ldap-utils
      apt: name=ldap-utils state=latest
```

The other option of course is to create a new version (or your own copy) of the `dinkel/openldap` image and add python to it.

I assume what you're asking for Ansible Container to do is detect when python is missing, and if so, attempt to install it.

I think that's outside of the scope of Ansible Container. If Ansible decides to add such functionality, then we would certainly support it, but for now, as I demonstrated above, it's trivial for the user to detect and install python using the `raw` module or simply create an image with python already installed.
