### ISSUE TITLE
Service using tag --services not found

### ISSUE THREAD

**Issue by ReeSilva** [ansible/ansible-container#274]
##### ISSUE TYPE

 - Bug Report

##### container.yml 

```
version: "1"
services:
  auth:
    image: "cterminal/base-image"
    ports:
      - "8002:80"
  content:
    image: "cterminal/base-image"
    ports:
      - "8003:80"
  folder:
    image: "cterminal/base-image"
    ports:
      - "8004:80"
  upload:
    image: "cterminal/base-image"
    ports:
      - "8005:80"
  3rdparty-upload:
    image: "cterminal/base-image"
    ports:
      - "8006:80"
  computer-vision:
    image: "cterminal/base-image"
    ports:
      - "8007:80"
  search:
    image: "cterminal/base-image"
    ports:
      - "8008:80"
  user-profile:
    image: "cterminal/base-image"
    ports:
      - "8009:80"
  email:
    image: "cterminal/base-image"
  user-relations:
    image: "cterminal/base-image"
    ports:
      - "8010:80"
  credits-list:
    image: "cterminal/base-image"
    ports:
      - "8011:80"
  inviter:
    image: "cterminal/base-image"
    ports:
      - "8012:80"
  content-queue-listener:
    image: "cterminal/base-image"
  search-queue-listener:
    image: "cterminal/base-image"
  inviter-queue-listener:
    image: "cterminal/base-image"
  folder-queue-listener:
    image: "cterminal/base-image"
  user-profile-queue-listener:
    image: "cterminal/base-image"
  credits-list-queue-listener:
    image: "cterminal/base-image"
  web:
    image: "cterminal/alpine-node-web"
    ports:
      - "3000:3000"

registries:
  cterminal:
    url: https://index.docker.io/v1/
    namespace: cterminal
```

##### main.yml 

```
---
# Playbook for the auth service container
- name: configure the auth image
  remote_user: root
  hosts: auth
  vars_files:
    - roles/auth/vars/{{ env }}/main.yml
    - roles/auth/vars/{{ env }}/app-vars.yml
    - roles/auth/vars/{{ env }}/sensitive-vars.yml
  roles:
    - auth

# Playbook for the content service container
- name: configure the content image
  remote_user: root
  hosts: content
  vars_files:
    - roles/content/vars/{{ env }}/main.yml
    - roles/content/vars/{{ env }}/app-vars.yml
    - roles/content/vars/{{ env }}/sensitive-vars.yml
  roles:
    - content

# Playbook for the folder service container
- name: configure the folder image
  remote_user: root
  hosts: folder
  vars_files:
    - roles/folder/vars/{{ env }}/main.yml
    - roles/folder/vars/{{ env }}/app-vars.yml
    - roles/folder/vars/{{ env }}/sensitive-vars.yml
  roles:
    - folder

# Playbook for the upload service container
- name: configure the upload image
  remote_user: root
  hosts: upload
  vars_files:
    - roles/upload/vars/{{ env }}/main.yml
    - roles/upload/vars/{{ env }}/app-vars.yml
    - roles/upload/vars/{{ env }}/sensitive-vars.yml
  roles:
    - upload

# Playbook for the 3rdparty-upload service container
- name: configure the 3rdparty-upload image
  remote_user: root
  hosts: 3rdparty-upload
  vars_files:
    - roles/3rdparty-upload/vars/{{ env }}/main.yml
    - roles/3rdparty-upload/vars/{{ env }}/app-vars.yml
    - roles/3rdparty-upload/vars/{{ env }}/sensitive-vars.yml
  roles:
    - 3rdparty-upload

# Playbook for the computer-vision service container
- name: configure the computer-vision image
  remote_user: root
  hosts: computer-vision
  vars_files:
    - roles/computer-vision/vars/{{ env }}/main.yml
    - roles/computer-vision/vars/{{ env }}/app-vars.yml
    - roles/computer-vision/vars/{{ env }}/sensitive-vars.yml
  roles:
    - computer-vision

# Playbook for the search service container
- name: configure the search image
  remote_user: root
  hosts: search
  vars_files:
    - roles/search/vars/{{ env }}/main.yml
    - roles/search/vars/{{ env }}/app-vars.yml
    - roles/search/vars/{{ env }}/sensitive-vars.yml
  roles:
    - search

- name: configure the user-profile image
  remote_user: root
  hosts: user-profile
  vars_files:
    - roles/user-profile/vars/{{ env }}/main.yml
    - roles/user-profile/vars/{{ env }}/app-vars.yml
    - roles/user-profile/vars/{{ env }}/sensitive-vars.yml
  roles:
    - user-profile

- name: configure the email image
  remote_user: root
  hosts: email
  vars_files:
    - roles/email/vars/{{ env }}/main.yml
    - roles/email/vars/{{ env }}/app-vars.yml
    - roles/email/vars/{{ env }}/sensitive-vars.yml
  roles:
    - email

- name: configure the user-relations image
  remote_user: root
  hosts: user-relations
  vars_files:
    - roles/user-relations/vars/{{ env }}/main.yml
    - roles/user-relations/vars/{{ env }}/app-vars.yml
    - roles/user-relations/vars/{{ env }}/sensitive-vars.yml
  roles:
    - user-relations

- name: configure the credits-list image
  remote_user: root
  hosts: credits-list
  vars_files:
    - roles/credits-list/vars/{{ env }}/main.yml
    - roles/credits-list/vars/{{ env }}/app-vars.yml
    - roles/credits-list/vars/{{ env }}/sensitive-vars.yml
  roles:
    - credits-list

- name: configure the inviter image
  remote_user: root
  hosts: inviter
  vars_files:
    - roles/inviter/vars/{{ env }}/main.yml
    - roles/inviter/vars/{{ env }}/app-vars.yml
    - roles/inviter/vars/{{ env }}/sensitive-vars.yml
  roles:
    - inviter

# Playbook for the web client
- name: configure the web client
  remote_user: root
  hosts: web
  vars_files:
    - roles/web/vars/{{ env }}/main.yml
    - roles/web/vars/{{ env }}/app-vars.yml
    - roles/web/vars/{{ env }}/sensitive-vars.yml
  roles:
    - web

# Playbook for the content-queue-listener
- name: configure the content queue listener
  remote_user: root
  hosts: content-queue-listener
  vars_files:
    - roles/content-queue-listener/vars/{{ env }}/main.yml
    - roles/content-queue-listener/vars/{{ env }}/app-vars.yml
    - roles/content-queue-listener/vars/{{ env }}/sensitive-vars.yml
  roles:
    - content-queue-listener

- name: configure the search queue listener
  remote_user: root
  hosts: search-queue-listener
  vars_files:
    - roles/search-queue-listener/vars/{{ env }}/main.yml
    - roles/search-queue-listener/vars/{{ env }}/app-vars.yml
    - roles/search-queue-listener/vars/{{ env }}/sensitive-vars.yml
  roles:
    - search-queue-listener

- name: configure the folder queue listener
  remote_user: root
  hosts: folder-queue-listener
  vars_files:
    - roles/folder-queue-listener/vars/{{ env }}/main.yml
    - roles/folder-queue-listener/vars/{{ env }}/app-vars.yml
    - roles/folder-queue-listener/vars/{{ env }}/sensitive-vars.yml
  roles:
    - folder-queue-listener

- name: configure the user-profile queue listener
  remote_user: root
  hosts: user-profile-queue-listener
  vars_files:
    - roles/user-profile-queue-listener/vars/{{ env }}/main.yml
    - roles/user-profile-queue-listener/vars/{{ env }}/app-vars.yml
    - roles/user-profile-queue-listener/vars/{{ env }}/sensitive-vars.yml
  roles:
    - user-profile-queue-listener

- name: configure the inviter queue listener
  remote_user: root
  hosts: inviter-queue-listener
  vars_files:
    - roles/inviter-queue-listener/vars/{{ env }}/main.yml
    - roles/inviter-queue-listener/vars/{{ env }}/app-vars.yml
    - roles/inviter-queue-listener/vars/{{ env }}/sensitive-vars.yml
  roles:
    - inviter-queue-listener

- name: configure the credits-list queue listener
  remote_user: root
  hosts: credits-list-queue-listener
  vars_files:
    - roles/credits-list-queue-listener/vars/{{ env }}/main.yml
    - roles/credits-list-queue-listener/vars/{{ env }}/app-vars.yml
    - roles/credits-list-queue-listener/vars/{{ env }}/sensitive-vars.yml
  roles:
    - credits-list-queue-listener
```

##### OS / ENVIRONMENT

```
Ansible Container, version 0.3.0-pre
Linux, strkrntbk, 4.7.6-1-ARCH, #1 SMP PREEMPT Fri Sep 30 19:28:42 CEST 2016, x86_64
2.7.12 (default, Jun 28 2016, 08:31:05) 
[GCC 6.1.1 20160602] /usr/bin/python2.7
No DOCKER_HOST environment variable found. Assuming UNIX socket at /var/run/docker.sock
{u'Architecture': u'x86_64',
 u'BridgeNfIp6tables': True,
 u'BridgeNfIptables': True,
 u'CPUSet': True,
 u'CPUShares': True,
 u'CgroupDriver': u'cgroupfs',
 u'ClusterAdvertise': u'',
 u'ClusterStore': u'',
 u'Containers': 14,
 u'ContainersPaused': 0,
 u'ContainersRunning': 0,
 u'ContainersStopped': 14,
 u'CpuCfsPeriod': True,
 u'CpuCfsQuota': True,
 u'Debug': False,
 u'DefaultRuntime': u'runc',
 u'DockerRootDir': u'/var/lib/docker',
 u'Driver': u'devicemapper',
 u'DriverStatus': [[u'Pool Name', u'docker-8:2-1967167-pool'],
                   [u'Pool Blocksize', u'65.54 kB'],
                   [u'Base Device Size', u'10.74 GB'],
                   [u'Backing Filesystem', u'xfs'],
                   [u'Data file', u'/dev/loop0'],
                   [u'Metadata file', u'/dev/loop1'],
                   [u'Data Space Used', u'6.326 GB'],
                   [u'Data Space Total', u'107.4 GB'],
                   [u'Data Space Available', u'101 GB'],
                   [u'Metadata Space Used', u'9.966 MB'],
                   [u'Metadata Space Total', u'2.147 GB'],
                   [u'Metadata Space Available', u'2.138 GB'],
                   [u'Thin Pool Minimum Free Space', u'10.74 GB'],
                   [u'Udev Sync Supported', u'true'],
                   [u'Deferred Removal Enabled', u'false'],
                   [u'Deferred Deletion Enabled', u'false'],
                   [u'Deferred Deleted Device Count', u'0'],
                   [u'Data loop file',
                    u'/var/lib/docker/devicemapper/devicemapper/data'],
                   [u'Metadata loop file',
                    u'/var/lib/docker/devicemapper/devicemapper/metadata'],
                   [u'Library Version', u'1.02.135 (2016-09-26)']],
 u'ExecutionDriver': u'',
 u'ExperimentalBuild': False,
 u'HttpProxy': u'',
 u'HttpsProxy': u'',
 u'ID': u'3ISF:YDHJ:A7I5:D4IR:KNUE:4QUQ:C6BZ:6SB7:GSFV:KIW5:YRUI:P7ET',
 u'IPv4Forwarding': True,
 u'Images': 32,
 u'IndexServerAddress': u'https://index.docker.io/v1/',
 u'KernelMemory': True,
 u'KernelVersion': u'4.7.6-1-ARCH',
 u'Labels': None,
 u'LiveRestoreEnabled': False,
 u'LoggingDriver': u'json-file',
 u'MemTotal': 12527988736,
 u'MemoryLimit': True,
 u'NCPU': 4,
 u'NEventsListener': 0,
 u'NFd': 17,
 u'NGoroutines': 25,
 u'Name': u'strkrntbk',
 u'NoProxy': u'',
 u'OSType': u'linux',
 u'OomKillDisable': True,
 u'OperatingSystem': u'Arch Linux',
 u'Plugins': {u'Authorization': None,
              u'Network': [u'null', u'bridge', u'host', u'overlay'],
              u'Volume': [u'local']},
 u'RegistryConfig': {u'IndexConfigs': {u'docker.io': {u'Mirrors': None,
                                                      u'Name': u'docker.io',
                                                      u'Official': True,
                                                      u'Secure': True}},
                     u'InsecureRegistryCIDRs': [u'127.0.0.0/8'],
                     u'Mirrors': None},
 u'Runtimes': {u'runc': {u'path': u'docker-runc'}},
 u'SecurityOptions': [u'seccomp'],
 u'ServerVersion': u'1.12.2',
 u'SwapLimit': True,
 u'Swarm': {u'Cluster': {u'CreatedAt': u'0001-01-01T00:00:00Z',
                         u'ID': u'',
                         u'Spec': {u'CAConfig': {},
                                   u'Dispatcher': {},
                                   u'Orchestration': {},
                                   u'Raft': {},
                                   u'TaskDefaults': {}},
                         u'UpdatedAt': u'0001-01-01T00:00:00Z',
                         u'Version': {}},
            u'ControlAvailable': False,
            u'Error': u'',
            u'LocalNodeState': u'inactive',
            u'Managers': 0,
            u'NodeAddr': u'',
            u'NodeID': u'',
            u'Nodes': 0,
            u'RemoteManagers': None},
 u'SystemStatus': None,
 u'SystemTime': u'2016-10-18T13:38:12.957569125-02:00'}
{u'ApiVersion': u'1.24',
 u'Arch': u'amd64',
 u'BuildTime': u'2016-10-16T13:09:44.392986012+02:00',
 u'GitCommit': u'bb80604',
 u'GoVersion': u'go1.7.1',
 u'KernelVersion': u'4.7.6-1-ARCH',
 u'Os': u'linux',
 u'Version': u'1.12.2'}
```
##### SUMMARY

When I use the tag `--services`on `ansible-container build` it returns that the service was not found on my ansible/main.yml

##### STEPS TO REPRODUCE

```
ansible-container build --services content -- -e env=ci
```

##### EXPECTED RESULTS

Run the ansible-container build only for the content service

##### ACTUAL RESULTS

Return that the requested service is not referenced

```
No DOCKER_HOST environment variable found. Assuming UNIX socket at /var/run/docker.sock
Starting Docker Compose engine to build your images...
Attaching to ansible_ansible-container_1
Cleaning up Ansible Container builder...
The requested service(s) is not referenced in ansible/main.yml. Nothing to build.

```

##### ADDITIONAL INFO
I'm trying to run this on my local. I have a CI environment where this parameter is working correctly.
If I run ansible-container build without this parameter the service content works correctly.
