### ISSUE TITLE
local_action || delegate_to: 127.0.0.1 doesn't work

### ISSUE THREAD

**Issue by zerginator** [ansible/ansible-container#321]
##### ISSUE TYPE
 - Bug Report

##### main.yml 
- hosts: all
  gather_facts: false
  tasks:
  - name: Create /tmp/testFolder
    local_action: file path=/tmp/testFolder state=directory

##### OS / ENVIRONMENT
centos 7
##### SUMMARY
local_action seams not to work when running ansible-container build

##### STEPS TO REPRODUCE
run ansible-container init and replace main.yml with the one on top

##### EXPECTED RESULTS
/tmp/testFolder  will be created

##### ACTUAL RESULTS
nothing happens

**Comment by ryansb** [comment]
I think you need to do:

```
- local_action:
    module: file
    args:
      path: /tmp/testFolder
      state: directory
```
