### ISSUE TITLE
Allow providing custom config_path via cli arguments

### ISSUE THREAD

**Issue by rakshazi** [ansible/ansible-container#340]
##### ISSUE TYPE

 - Feature Idea

##### container.yml 

```
Not needed
```

##### main.yml 

```
Not needed
```

##### OS / ENVIRONMENT

```
Not needed
```
##### SUMMARY

https://github.com/ansible/ansible-container/blob/develop/container/config.py#L32 has hardcoded path to "<...>/ansible/container.yml" file, but in case with multiple projects in one ansible dir (centralised repository with configuration, deploy, etc, for all team projects) it will be better to have ability to set container.yml file path via playbook or via cli arguments
##### STEPS TO REPRODUCE

```
Not needed
```

##### EXPECTED RESULTS

**FIrst way**. Set path to `container.yml` via cli args

```
ansible-container build --config-path=/ansible/roles/projectname/vars/container.yml
```

**Second way**. Set path to `container.yml` via playbook vars

`cat ansible/main.yml`:

```yml
---
- hosts: all
  vars:
    - container_config_path: "{{ playbook_dir }}/roles/projectname/vas/container.yml"
#...
```
##### ACTUAL RESULTS

```
container.yml must be placed in <PROJECT_DIR>/ansible/container.yml
```
