### ISSUE TITLE
`ansible.django-gulp-nginx` in getting started guide fails to build

### ISSUE THREAD

**Issue by flux627** [ansible/ansible-container#341]
##### ISSUE TYPE

 - Bug Report

##### container.yml 

```
version: '2'
defaults:
  POSTGRES_USER: django
  POSTGRES_PASSWORD: sesame
  POSTGRES_DB: django
  DJANGO_ROOT: /django
  DJANGO_USER: django
  DJANGO_PORT: 8080
  DJANGO_VENV: /venv
  NODE_USER: node
  NODE_HOME: /node
  NODE_ROOT: ''
  GULP_DEV_PORT: 8080
services:
  
  django:
    image: centos:7
    environment:
      DATABASE_URL: pgsql://{{ POSTGRES_USER }}:{{ POSTGRES_PASSWORD }}@postgresql:5432/{{
        POSTGRES_DB }}
      DJANGO_ROOT: '{{ DJANGO_ROOT }}'
      DJANGO_VENV: '{{ DJANGO_VENV }}'
    expose:
    - '{{ DJANGO_PORT }}'
    working_dir: '{{ DJANGO_ROOT }}'
    links:
    - postgresql
    user: '{{ DJANGO_USER }}'
    command: ['/usr/bin/dumb-init', '{{ DJANGO_VENV }}/bin/gunicorn', -w, '2', -b, '0.0.0.0:{{ DJANGO_PORT }}', 'project.wsgi:application']
    entrypoint: [/usr/bin/entrypoint.sh]
    dev_overrides:
      command: [/usr/bin/dumb-init, '{{ DJANGO_VENV }}/bin/python', manage.py, runserver,
        '0.0.0.0:{{ DJANGO_PORT }}']
      volumes:
      - $PWD:{{ DJANGO_ROOT }}
      depends_on:
      - postgresql

    options:
      kube:
        runAsUser: 1000

  gulp:
    image: centos:7
    user: '{{ NODE_USER }}'
    working_dir: '{{ NODE_HOME }}'
    command: ['/bin/false']
    environment:
      NODE_HOME: '{{ NODE_HOME }}'
    volumes:
      - $PWD:{{ NODE_HOME }}
    dev_overrides:
      command: [/usr/bin/dumb-init, /usr/bin/gulp]
      ports:
      - 8080:{{ GULP_DEV_PORT }}
      - 3001:3001
      links:
      - django

    options:
      kube:
        state: absent
      openshift:
        state: absent

  nginx:
    image: centos:7
    ports:
    - {{ DJANGO_PORT }}:8000 
    user: nginx
    links:
    - django
    command: ['/usr/bin/dumb-init', 'nginx', '-c', '/etc/nginx/nginx.conf']
    dev_overrides:
      ports: []
      command: /bin/false

    options:
      kube:
        runAsUser: 1000 

  postgresql:
    image: openshift/postgresql-92-centos7
    environment:
    - POSTGRESQL_DATABASE={{ POSTGRES_DB }}
    - POSTGRESQL_USER={{ POSTGRES_USER }}
    - POSTGRESQL_PASSWORD={{ POSTGRES_PASSWORD }}
    expose:
    - 5432
    volumes:
    - postgres-data:/var/lib/pgsql/data

    options:
      openshift:
        persistent_volume_claims:
        - volume_name: postgres-data
          claim_name: postgres-data
          access_modes:
          - ReadWriteMany

registries: {}

volumes:
  postgres-data: {}
```

##### main.yml 

```
- hosts: django
  gather_facts: no
  roles:
  - django-gunicorn

- hosts: gulp
  gather_facts: no
  roles:
  - gulp-static

- hosts: nginx
  gather_facts: no
  roles:
  - role: ansible.nginx-container
    ASSET_PATHS:
    - /tmp/static
    PROXY: yes
    PROXY_PASS: http://django:8080
    PROXY_LOCATION: "~* /(admin|api)"
```

##### OS / ENVIRONMENT

```
Ansible Container, version 0.2.0
Darwin, Juliens-MBP.lan, 16.1.0, Darwin Kernel Version 16.1.0: Wed Oct 19 20:31:56 PDT 2016; root:xnu-3789.21.4~4/RELEASE_X86_64, x86_64
2.7.10 (default, Jul 30 2016, 18:31:42)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] /usr/bin/python
No DOCKER_HOST environment variable found. Assuming UNIX socket at /var/run/docker.sock
{u'Architecture': u'x86_64',
 u'BridgeNfIp6tables': True,
 u'BridgeNfIptables': True,
 u'CPUSet': True,
 u'CPUShares': True,
 u'CgroupDriver': u'cgroupfs',
 u'ClusterAdvertise': u'',
 u'ClusterStore': u'',
 u'Containers': 10,
 u'ContainersPaused': 0,
 u'ContainersRunning': 0,
 u'ContainersStopped': 10,
 u'CpuCfsPeriod': True,
 u'CpuCfsQuota': True,
 u'Debug': True,
 u'DefaultRuntime': u'runc',
 u'DockerRootDir': u'/var/lib/docker',
 u'Driver': u'aufs',
 u'DriverStatus': [[u'Root Dir', u'/var/lib/docker/aufs'],
                   [u'Backing Filesystem', u'extfs'],
                   [u'Dirs', u'76'],
                   [u'Dirperm1 Supported', u'true']],
 u'ExecutionDriver': u'',
 u'ExperimentalBuild': False,
 u'HttpProxy': u'',
 u'HttpsProxy': u'',
 u'ID': u'BUMB:HJZB:LZ76:YEBX:VH7O:46Z3:QR4U:QHTP:ZBR2:VYXB:RB5S:W4TA',
 u'IPv4Forwarding': True,
 u'Images': 19,
 u'IndexServerAddress': u'https://index.docker.io/v1/',
 u'KernelMemory': False,
 u'KernelVersion': u'4.4.27-moby',
 u'Labels': None,
 u'LiveRestoreEnabled': False,
 u'LoggingDriver': u'json-file',
 u'MemTotal': 2094673920,
 u'MemoryLimit': True,
 u'NCPU': 4,
 u'NEventsListener': 1,
 u'NFd': 16,
 u'NGoroutines': 29,
 u'Name': u'moby',
 u'NoProxy': u'*.local, 169.254/16',
 u'OSType': u'linux',
 u'OomKillDisable': True,
 u'OperatingSystem': u'Alpine Linux v3.4',
 u'Plugins': {u'Authorization': None,
              u'Network': [u'overlay', u'null', u'host', u'bridge'],
              u'Volume': [u'local']},
 u'RegistryConfig': {u'IndexConfigs': {u'docker.io': {u'Mirrors': None,
                                                      u'Name': u'docker.io',
                                                      u'Official': True,
                                                      u'Secure': True}},
                     u'InsecureRegistryCIDRs': [u'127.0.0.0/8'],
                     u'Mirrors': None},
 u'Runtimes': {u'runc': {u'path': u'docker-runc'}},
 u'SecurityOptions': [u'seccomp'],
 u'ServerVersion': u'1.12.3',
 u'SwapLimit': True,
 u'Swarm': {u'Cluster': {u'CreatedAt': u'0001-01-01T00:00:00Z',
                         u'ID': u'',
                         u'Spec': {u'CAConfig': {},
                                   u'Dispatcher': {},
                                   u'Orchestration': {},
                                   u'Raft': {},
                                   u'TaskDefaults': {}},
                         u'UpdatedAt': u'0001-01-01T00:00:00Z',
                         u'Version': {}},
            u'ControlAvailable': False,
            u'Error': u'',
            u'LocalNodeState': u'inactive',
            u'Managers': 0,
            u'NodeAddr': u'',
            u'NodeID': u'',
            u'Nodes': 0,
            u'RemoteManagers': None},
 u'SystemStatus': None,
 u'SystemTime': u'2016-12-23T15:34:30.952286311Z'}
{u'ApiVersion': u'1.24',
 u'Arch': u'amd64',
 u'BuildTime': u'2016-10-26T23:26:11.105168198+00:00',
 u'GitCommit': u'6b644ec',
 u'GoVersion': u'go1.6.3',
 u'KernelVersion': u'4.4.27-moby',
 u'Os': u'linux',
 u'Version': u'1.12.3'}
```
##### SUMMARY
I'm not sure if this problem is because of `ansible.django-gulp-nginx`, my environment, a bug in ansible-container, or a bug in ansible, so I'm not sure if this is the appropriate place to post this. I found another issue regarding this getting started guide, but it seems to be different. When I follow the tutorial steps, running
```
ansible-container init ansible.django-gulp-nginx
ansible-container build
```
results in the following error:
```
ansible-container_1  | TASK [django-gunicorn : Copy source] *******************************************
ansible-container_1  | fatal: [django]: FAILED! => {"changed": false, "failed": true, "msg": "synchronize uses rsync to function. rsync needs to connect to the remote host via ssh or a direct filesystem copy. This remote host is being accessed via docker instead so it cannot work."}
```
I noticed this issue in the ansible repo, maybe it is related?
https://github.com/ansible/ansible/issues/16306

##### STEPS TO REPRODUCE
See above

##### EXPECTED RESULTS
Build should succeed

##### ACTUAL RESULTS
Build fails
