### ISSUE TITLE
Ansible tries to execute the COMMAND before the container built

### ISSUE THREAD

**Issue by brucellino** [ansible/ansible-container#342]
##### ISSUE TYPE

Bug Report

##### container.yml 

```
version: "1"
services:
{% for slave in slaves %}
  build-slave-{{ slave.name }}:
    image: "{{ slave.base_image}}:{{ slave.base_image_tag }}"
    ports:
        - "{{ slave.host_port }}:{{ container_port }}"
    command: ["/usr/sbin/sshd", "-D","-p {{ container_port}}"]
    #command: ["/bin/sh","-c","while true; do sleep 1000; done"]
    volumes_from:
      - CODE-RADE-src:rw
      - CODE-RADE-modules:rw
      - CODE-RADE-soft:rw
      - CODE-RADE-repo:rw
      - CODE-RADE-cvmfs:rw
{% endfor %}
  CODE-RADE-src:
    image: alpine
    command: ["/bin/sh","-c","while true; do sleep 1000; done"]
    volumes:
      - "{{ src_dir }}:{{ src_dir }}"
  CODE-RADE-soft:
    image: alpine
    command: ["/bin/sh","-c","while true; do sleep 1000; done"]
    volumes:
      - "{{ soft_dir }}:{{ soft_dir }}"
  CODE-RADE-repo:
    image: alpine
    command: ["/bin/sh","-c","while true; do sleep 1000; done"]
    volumes:
      - "{{ repo_dir }}:{{ repo_dir }}"
  CODE-RADE-modules:
    image: alpine
    command: ["/bin/sh","-c","while true; do sleep 1000; done"]
    volumes:
      - "{{ modules_dir }}"
  CODE-RADE-cvmfs:
    image: alpine
    command: ["/bin/sh","-c","while true; do sleep 1000; done"]
    volumes:
      - "{{ cvmfs_dir }}"


registries:
  docker:
    url: https://hub.docker.com
    namespace: /u/aaroc
  quay:
    url: https://quay.io
    namespace: aaroc

```

##### main.yml 

```
# This should be your Ansible playbooks to provision your containers.
# An inventory will be automatically created using the names of the services
# from your container.yml file.
# Add any roles or other modules you'll need to this directory too.
# For many examples of roles, check out Ansible Galaxy: https://galaxy.ansible.com/
#
---
- name: Group the build cluster
  hosts: localhost
  connection: local
  tasks:
    - name: Add ubuntu build slaves to group
      add_host:
        name: "build-slave-{{ item }}"
        groups: ubuntu-slaves
      with_items:
        - ubuntu1404
        - ubuntu1610
    - name: Add CentOS slaves to group
      add_host:
        name: "build-slave-{{ item }}"
        groups: centos-slaves
      with_items:
        - centos6
        - centos7

- name: Raw Setup (ubuntu)
  hosts: ubuntu-slaves
  gather_facts: false
  tasks:
  - name: Install Python (Ubuntu)
    raw: which python || apt-get -y update && apt-get install -y python

- name: Raw Setup (CentOS)
  hosts: centos-slaves
  gather_facts: false
  tasks:
    - name: install python
      raw: which python || yum -y update && yum install -y python

- name: Prepare Jenkins environment
  hosts: ubuntu-slaves:centos-slaves
  tasks:
    - name: Update jenkins user
      user:
        name: jenkins
        home: /home/jenkins
        state: present
        password: nope
    - name: add keys to the authorized keys
      authorized_key:
        user: root
        key: https://github.com/{{ item }}.keys
        validate_certs: False
      with_items:
        - brucellino
        - jenkinssagrid

    - name: install sshd
      package:
        name: openssh-server
        state: present
    - name: generate host keys
      command: "ssh-keygen -f /etc/ssh/ssh_host_{{item }}_key -N '' -t {{ item }}"
      args:
        creates: "/etc/ssh/ssh_host_{{item }}_key"
      with_items:
        - rsa
        - dsa
        - ecdsa

    - name: ensure run dir present
      file:
        dest: /var/run/sshd
        state: directory
        owner: root

    - name: Replace the pam login
      lineinfile:
        dest: /etc/pam.d/sshd
        line: "session    optional     pam_loginuid.so"
        regexp: "session    required     pam_loginuid.so"
        state: present

- name: CODE-RADE secret sauce
  hosts: ubuntu-slaves:centos-slaves
  tasks:
  - name: install prerequisites
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - git
      - environment-modules
      - wget
      - bzip2
      - vim
      - which
      - tree
      - java-1.8.0-openjdk.x86_64
    when: ansible_os_family == "RedHat"

  - name: Install Vanilla compiler (RedHat)
    yum:
      name: '@Development tools'
      state: present
    when: ansible_os_family == 'RedHat'

  - name: Install prerequisites (Debian)
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - build-essential
      - git
      - environment-modules
      - wget
      - bzip2
      - vim
      - default-jdk
      - tree
    when: "{{ ansible_os_family == 'Debian'}}"

  - name: Push the modules (RedHat)
    copy:
      src: "files/usr/share/Modules/modulefiles/{{ item }}"
      dest: "/usr/share/Modules/modulefiles/{{ item }}"
    with_items:
      - ci
      - deploy
    when: ansible_os_family == "RedHat"

  - name: Push the modules (Debian)
    copy:
      src: "files/usr/share/Modules/modulefiles/{{ item }}"
      dest: "/usr/share/modules/modulefiles/{{ item }}"
    with_items:
      - ci
      - deploy
    when: ansible_os_family == "Debian"

```

##### OS / ENVIRONMENT

```
Ansible Container, version 0.3.0-pre
Linux, serbaggio, 4.4.0-51-generic, #72-Ubuntu SMP Thu Nov 24 18:29:54 UTC 2016, x86_64
2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] /usr/bin/python
No DOCKER_HOST environment variable found. Assuming UNIX socket at /var/run/docker.sock
{u'Architecture': u'x86_64',
 u'BridgeNfIp6tables': True,
 u'BridgeNfIptables': True,
 u'CPUSet': True,
 u'CPUShares': True,
 u'CgroupDriver': u'cgroupfs',
 u'ClusterAdvertise': u'',
 u'ClusterStore': u'',
 u'Containers': 14,
 u'ContainersPaused': 0,
 u'ContainersRunning': 0,
 u'ContainersStopped': 14,
 u'CpuCfsPeriod': True,
 u'CpuCfsQuota': True,
 u'Debug': False,
 u'DefaultRuntime': u'runc',
 u'DockerRootDir': u'/var/lib/docker',
 u'Driver': u'aufs',
 u'DriverStatus': [[u'Root Dir', u'/var/lib/docker/aufs'],
                   [u'Backing Filesystem', u'extfs'],
                   [u'Dirs', u'69'],
                   [u'Dirperm1 Supported', u'true']],
 u'ExecutionDriver': u'',
 u'ExperimentalBuild': False,
 u'HttpProxy': u'',
 u'HttpsProxy': u'',
 u'ID': u'O4O7:C7V3:PT4A:3GDE:PDWG:KHS2:MOI2:CNIJ:DMZH:OH7U:WOTC:5345',
 u'IPv4Forwarding': True,
 u'Images': 5,
 u'IndexServerAddress': u'https://index.docker.io/v1/',
 u'KernelMemory': True,
 u'KernelVersion': u'4.4.0-51-generic',
 u'Labels': None,
 u'LiveRestoreEnabled': False,
 u'LoggingDriver': u'json-file',
 u'MemTotal': 8236060672,
 u'MemoryLimit': True,
 u'NCPU': 8,
 u'NEventsListener': 0,
 u'NFd': 16,
 u'NGoroutines': 25,
 u'Name': u'serbaggio',
 u'NoProxy': u'',
 u'OSType': u'linux',
 u'OomKillDisable': True,
 u'OperatingSystem': u'Ubuntu 16.04.1 LTS',
 u'Plugins': {u'Authorization': None,
              u'Network': [u'overlay', u'bridge', u'null', u'host'],
              u'Volume': [u'local']},
 u'RegistryConfig': {u'IndexConfigs': {u'docker.io': {u'Mirrors': None,
                                                      u'Name': u'docker.io',
                                                      u'Official': True,
                                                      u'Secure': True}},
                     u'InsecureRegistryCIDRs': [u'127.0.0.0/8'],
                     u'Mirrors': None},
 u'Runtimes': {u'runc': {u'path': u'docker-runc'}},
 u'SecurityOptions': [u'apparmor', u'seccomp'],
 u'ServerVersion': u'1.12.5',
 u'SwapLimit': False,
 u'Swarm': {u'Cluster': {u'CreatedAt': u'0001-01-01T00:00:00Z',
                         u'ID': u'',
                         u'Spec': {u'CAConfig': {},
                                   u'Dispatcher': {},
                                   u'Orchestration': {},
                                   u'Raft': {},
                                   u'TaskDefaults': {}},
                         u'UpdatedAt': u'0001-01-01T00:00:00Z',
                         u'Version': {}},
            u'ControlAvailable': False,
            u'Error': u'',
            u'LocalNodeState': u'inactive',
            u'Managers': 0,
            u'NodeAddr': u'',
            u'NodeID': u'',
            u'Nodes': 0,
            u'RemoteManagers': None},
 u'SystemStatus': None,
 u'SystemTime': u'2016-12-28T15:33:44.176329999+01:00'}
{u'ApiVersion': u'1.24',
 u'Arch': u'amd64',
 u'BuildTime': u'2016-12-16T02:42:17.070078439+00:00',
 u'GitCommit': u'7392c3b',
 u'GoVersion': u'go1.6.4',
 u'KernelVersion': u'4.4.0-51-generic',
 u'Os': u'linux',
 u'Version': u'1.12.5'
```

I also have vars : 
```
# Vars for Buildslave
---
slaves:
  - name: centos6
    base_image: centos
    base_image_tag: 6
    host_port: 5000
  - name: centos7
    base_image: centos
    base_image_tag: 7
    host_port: 5001
  - name: ubuntu1404
    base_image: ubuntu
    base_image_tag: "14.04"
    host_port: 5002
  - name: ubuntu1610
    base_image: ubuntu
    base_image_tag: "16.10"
    host_port: 5003

container_port: 5200
modules_dir: /data/modules
src_dir: /data/src/
repo_dir: /data/artefacts
soft_dir: /data/ci-build
cvmfs_dir: /cvmfs

```
##### SUMMARY

When I try to build this, I get the following error : 

`ERROR: for build-slave-centos6  invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"/usr/sbin/sshd\\\": stat /usr/sbin/sshd: no such file or directory\"\n"` (full output below)

##### STEPS TO REPRODUCE

The code is at https://github.com/AAROC/CODE-RADE-build-containers

```
ansible-container --var-file=vars.yml build
```

##### EXPECTED RESULTS

Main.yml should install, configure and start (amongst other things),  the SSH server. The images that are used as reference do not contain the ssh server, so the "COMMAND" part of the container.yml file is not found - but this should be added by the playbook. The main.yml should be executed by ansible, and the containers should be properly built. 

##### ACTUAL RESULTS

The build fails with the error below 

```
ansible-container --var-file=vars.yml build
No DOCKER_HOST environment variable found. Assuming UNIX socket at /var/run/docker.sock
Starting Docker Compose engine to build your images...
Attaching to ansible_ansible-container_1
Cleaning up Ansible Container builder...
No image found for tag code-rade-build-containers-CODE-RADE-cvmfs:latest, so building from scratch
No image found for tag code-rade-build-containers-build-slave-ubuntu1610:latest, so building from scratch
No image found for tag code-rade-build-containers-build-slave-centos6:latest, so building from scratch
No image found for tag code-rade-build-containers-build-slave-centos7:latest, so building from scratch
No image found for tag code-rade-build-containers-CODE-RADE-modules:latest, so building from scratch
No image found for tag code-rade-build-containers-CODE-RADE-repo:latest, so building from scratch
No image found for tag code-rade-build-containers-build-slave-ubuntu1404:latest, so building from scratch
No image found for tag code-rade-build-containers-CODE-RADE-soft:latest, so building from scratch
No image found for tag code-rade-build-containers-CODE-RADE-src:latest, so building from scratch

ERROR: for build-slave-centos6  invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"/usr/sbin/sshd\\\": stat /usr/sbin/sshd: no such file or directory\"\n"

ERROR: for build-slave-centos7  invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"/usr/sbin/sshd\\\": stat /usr/sbin/sshd: no such file or directory\"\n"

ERROR: for build-slave-ubuntu1404  invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"/usr/sbin/sshd\\\": stat /usr/sbin/sshd: no such file or directory\"\n"

ERROR: for build-slave-ubuntu1610  invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"/usr/sbin/sshd\\\": stat /usr/sbin/sshd: no such file or directory\"\n"
Attaching to ansible_CODE-RADE-src_1, ansible_CODE-RADE-cvmfs_1, ansible_CODE-RADE-modules_1, ansible_CODE-RADE-soft_1, ansible_CODE-RADE-repo_1, ansible_ansible-container_1
ansible-container_1       | Running pip install of ansible/requirements.txt
ansible-container_1       | Host CODE-RADE-cvmfs running
ansible-container_1       | Host build-slave-ubuntu1610 failed
ansible-container_1       | Host build-slave-centos6 failed
ansible-container_1       | Host build-slave-centos7 failed
ansible-container_1       | Host CODE-RADE-modules running
ansible-container_1       | Host CODE-RADE-repo running
ansible-container_1       | Host build-slave-ubuntu1404 failed
ansible-container_1       | Host CODE-RADE-soft running
ansible-container_1       | Host CODE-RADE-src running
ansible-container_1       | 
ansible-container_1       | PLAY [Group the build cluster] *************************************************
ansible-container_1       | 
ansible-container_1       | TASK [Gathering Facts] *********************************************************
ansible-container_1       | ok: [localhost]
ansible-container_1       | 
ansible-container_1       | TASK [Add ubuntu build slaves to group] ****************************************
ansible-container_1       | changed: [localhost] => (item=ubuntu1404)
ansible-container_1       | changed: [localhost] => (item=ubuntu1610)
ansible-container_1       | 
ansible-container_1       | TASK [Add CentOS slaves to group] **********************************************
ansible-container_1       | changed: [localhost] => (item=centos6)
ansible-container_1       | changed: [localhost] => (item=centos7)
ansible-container_1       | 
ansible-container_1       | PLAY [Raw Setup (ubuntu)] ******************************************************
ansible-container_1       | 
ansible-container_1       | TASK [Install Python (Ubuntu)] *************************************************
ansible-container_1       | fatal: [build-slave-ubuntu1610]: FAILED! => {"changed": true, "failed": true, "rc": 1, "stderr": "Error response from daemon: Container 32a4c43975ae9f793b5af11c131a1101ce8f5e889c03d34b8b1a0676d7dfdf3b is not running\n", "stdout": "", "stdout_lines": []}
ansible-container_1       | fatal: [build-slave-ubuntu1404]: FAILED! => {"changed": true, "failed": true, "rc": 1, "stderr": "Error response from daemon: Container cd2d05b13d94370d1a0c98dfb2d2ab111687215fa09b2a5cf3b1f8c259726809 is not running\n", "stdout": "", "stdout_lines": []}
ansible-container_1       | 	to retry, use: --limit @/ansible-container/ansible/main.retry
ansible-container_1       | 
ansible-container_1       | PLAY RECAP *********************************************************************
ansible-container_1       | build-slave-ubuntu1404     : ok=0    changed=0    unreachable=0    failed=1   
ansible-container_1       | build-slave-ubuntu1610     : ok=0    changed=0    unreachable=0    failed=1   
ansible-container_1       | localhost                  : ok=3    changed=2    unreachable=0    failed=0   
ansible-container_1       | 
ansible_ansible-container_1 exited with code 2
Aborting on container exit...
Stopping ansible_CODE-RADE-soft_1 ... done
Stopping ansible_CODE-RADE-repo_1 ... done
Stopping ansible_CODE-RADE-modules_1 ... done
Stopping ansible_CODE-RADE-src_1 ... done
Stopping ansible_CODE-RADE-cvmfs_1 ... done
Ansible playbook run failed.
Cleaning up Ansible Container builder...
Ansible build failed

```
