### ISSUE TITLE
couldn't git pull from within a docker container while buidling image using ansible-container build

### ISSUE THREAD

**Issue by manjitkumar** [ansible/ansible-container#347]
This is not an issue but a desperate attempt to understand the working of ssh-agent forwarding with docker containers. If you feel this is not a right place to ask, please redirect to relevant community and close the issue.

##### ISSUE TYPE

 - Help Wanted

##### container.yml 

```
version: "2"
services:
  local_api:
    image: python:2.7
    expose:
      - "8080"
    command: ['/usr/bin/dumb-init']
    dev_overrides:
      environment:
        - "DEBUG=1"
registries:
  local:
    url: https://docker-hub.local.io
    namespace: localspace

```

##### main.yml 

```
# This should be your Ansible playbooks to provision your containers.
# An inventory will be automatically created using the names of the services
# from your container.yml file.
# Add any roles or other modules you'll need to this directory too.
# For many examples of roles, check out Ansible Galaxy: https://galaxy.ansible.com/
#
---
- hosts: all
  gather_facts: false
  tasks:
    - name: Only say hello when running via Ansible Container
      command: echo "Hello!"
      when: ansible_env.ANSIBLE_CONTAINER is defined

    - name: Make project directory 
      file:
        path: "/code/repo"
        owner: "root"
        group: "root"
        mode: 0755
        state: directory

    - name: setup the git repo
      git:
        repo: "git@github.com:local/repo.git"
        version: "master"
        depth: 1
        dest: /code/repo
        accept_hostkey: yes
        force: yes

```

##### OS / ENVIRONMENT

```
Ansible Container, version 0.2.0
Darwin, myhost.local, 16.1.0, Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64, x86_64
2.7.10 (default, Jul 30 2016, 18:31:42)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] /Users/manjit/.virtualenvs/ansible-containers/bin/python
No DOCKER_HOST environment variable found. Assuming UNIX socket at /var/run/docker.sock
{u'Architecture': u'x86_64',
 u'BridgeNfIp6tables': True,
 u'BridgeNfIptables': True,
 u'CPUSet': True,
 u'CPUShares': True,
 u'CgroupDriver': u'cgroupfs',
 u'ClusterAdvertise': u'',
 u'ClusterStore': u'',
 u'Containers': 1,
 u'ContainersPaused': 0,
 u'ContainersRunning': 0,
 u'ContainersStopped': 1,
 u'CpuCfsPeriod': True,
 u'CpuCfsQuota': True,
 u'Debug': True,
 u'DefaultRuntime': u'runc',
 u'DockerRootDir': u'/var/lib/docker',
 u'Driver': u'aufs',
 u'DriverStatus': [[u'Root Dir', u'/var/lib/docker/aufs'],
                   [u'Backing Filesystem', u'extfs'],
                   [u'Dirs', u'18'],
                   [u'Dirperm1 Supported', u'true']],
 u'ExecutionDriver': u'',
 u'ExperimentalBuild': False,
 u'HttpProxy': u'',
 u'HttpsProxy': u'',
 u'ID': u'RJRC:F25M:MHLJ:OQYY:UYTC:LYTP:QYTP:USOC:CKXN:FC7A:NKSF:SMK2',
 u'IPv4Forwarding': True,
 u'Images': 2,
 u'IndexServerAddress': u'https://index.docker.io/v1/',
 u'KernelMemory': False,
 u'KernelVersion': u'4.4.39-moby',
 u'Labels': None,
 u'LiveRestoreEnabled': False,
 u'LoggingDriver': u'json-file',
 u'MemTotal': 2094940160,
 u'MemoryLimit': True,
 u'NCPU': 2,
 u'NEventsListener': 1,
 u'NFd': 19,
 u'NGoroutines': 29,
 u'Name': u'moby',
 u'NoProxy': u'*.local, 169.254/16',
 u'OSType': u'linux',
 u'OomKillDisable': True,
 u'OperatingSystem': u'Alpine Linux v3.4',
 u'Plugins': {u'Authorization': None,
              u'Network': [u'null', u'overlay', u'host', u'bridge'],
              u'Volume': [u'local']},
 u'RegistryConfig': {u'IndexConfigs': {u'docker.io': {u'Mirrors': [u'docker-registry.grofer.io:5000'],
                                                      u'Name': u'docker.io',
                                                      u'Official': True,
                                                      u'Secure': True}},
                     u'InsecureRegistryCIDRs': [u'127.0.0.0/8'],
                     u'Mirrors': [u'docker-registry.grofer.io:5000']},
 u'Runtimes': {u'runc': {u'path': u'docker-runc'}},
 u'SecurityOptions': [u'seccomp'],
 u'ServerVersion': u'1.12.5',
 u'SwapLimit': True,
 u'Swarm': {u'Cluster': {u'CreatedAt': u'0001-01-01T00:00:00Z',
                         u'ID': u'',
                         u'Spec': {u'CAConfig': {},
                                   u'Dispatcher': {},
                                   u'Orchestration': {},
                                   u'Raft': {},
                                   u'TaskDefaults': {}},
                         u'UpdatedAt': u'0001-01-01T00:00:00Z',
                         u'Version': {}},
            u'ControlAvailable': False,
            u'Error': u'',
            u'LocalNodeState': u'inactive',
            u'Managers': 0,
            u'NodeAddr': u'',
            u'NodeID': u'',
            u'Nodes': 0,
            u'RemoteManagers': None},
 u'SystemStatus': None,
 u'SystemTime': u'2017-01-02T11:46:31.532821871Z'}
{u'ApiVersion': u'1.24',
 u'Arch': u'amd64',
 u'BuildTime': u'2016-12-16T06:14:34.536244887+00:00',
 u'GitCommit': u'7392c3b',
 u'GoVersion': u'go1.6.4',
 u'KernelVersion': u'4.4.39-moby',
 u'Os': u'linux',
 u'Version': u'1.12.5'}
```
##### SUMMARY

I am trying to build an image for docker container using ansible-container where I need to clone a private git repository into my docker container and run the service. I failed to git clone the repository and understood my ssh keys aren't accessible within the docker container whereas previously I made it work with ansible running on remote servers by ssh-agent forwarding. If there are other better ways to do git clone inside docker containers, please let me know. 

##### STEPS TO REPRODUCE

1. Initialize an ansible container project
```
 ansible-container  init
```

2. Add above-given lines to container.yml and main.yml

3. Start building with 
```
ansible-container  build
```

##### ACTUAL RESULTS

```

```

**Comment by chouseknecht** [comment]
I might be wrong, but I think for SSH Agent Forwarding to work, you have to run sshd in the target container, and you likely have to connect to that container using SSH. Ansible Container does not rely on SSH, but instead using the `docker exec` by way of the Docker connection plugin.

**Comment by chouseknecht** [comment]
An alternative might be to clone the private repo to a local path before running `build`. In `container.yml`, map the local path into the container using the `volumes` directive, and then during the build copy the files to a path inside the container using the copy module.

**Comment by manjitkumar** [comment]
@chouseknecht  I was able to pull git repository by placing my ssh keys on the server and using `ssh_opts: "-i /.ssh/id_rsa"` option with git module. I intend to remove my ssh keys from the container and squash layers for the final image. Let me know if you have another approach or this approach violates something which is unknown to me and a huge thanks for your response.

**Comment by chouseknecht** [comment]
@j00bar, this is where it would be ideal to have a `build_overrides` directive in `container.yml`. In this case we would want to mount a volume " ~/.ssh/id_rsa:/home/<user>/.ssh/id_rsa" to the service containers during the build only.

So maybe something like... 

```
version: '2'
services:
   web:
      image: apache
      user: apache
      build_overrides:
         volumes:
         -  ~/.ssh/id_rsa:/home/apache/.ssh/id_rsa
      dev_overrides:
         volumes:
         - ${PWD}:/var/lib/www
```
