### ISSUE TITLE
During `build` override `read_only` directive

### ISSUE THREAD

**Issue by chouseknecht** [ansible/ansible-container#357]
##### ISSUE TYPE
 - Feature Idea
 
##### container.yml 
```
version: "2"
services:
  apache:
    image: base-images-apache:latest
    ports:
      - 80:8080
      - 443:44443
    working_dir: /usr/local/apache2
    command: ["/usr/local/apache2/bin/httpd", "-DFOREGROUND"]
    entrypoint: ["/usr/local/bin/dumb-init", "--"]
    user: httpd
    read_only: true
    tmpfs:
      - /tmp
    options:
      kube:
        runAsUser: 1000
```

##### SUMMARY

During `build` AC overrides the `user`, `command`,  and `entrypoint` directives in `container.yml` for each service touched by `main.yml`. In addition, it should also override `read_only`.

See the mailing list discussion [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/ansible-container/tga3dELUvV0)
