### ISSUE TITLE
Cannot run ansible-contianer-builder concurrently

### ISSUE THREAD

**Issue by deromka** [ansible/ansible-container#386]
##### ISSUE TYPE

 - Bug Report

##### container.yml 

```
version: "2"
defaults:
  docker_registry_name: dockerhub.com
  docker_repo:docker-staging
  docker_repo_staging:docker-staging
  docker_repo_releases:docker-releases
  use_local_profiles: false
  profile: general
  profile_version: latest
  base_image: dockerhub.com/docker-releases/openjdk
  container_user: user
  container_group: sss
  working_dir: /scripts
  basedir: /profiles
services:
  # Add your containers here, specifying the base image you want to build from

  # profile data volume container is a pre-requisite
{% if not use_local_profiles %}
  profile:
    image: "{{ docker_registry_name }}/{{ docker_repo_staging }}/{{ profile }}_profile:{{ profile_version }}"
{% endif %}

  {{ service_profile_name }}:
    image: {{ base_image }}
    entrypoint: "./run-{{ service_profile_name }}.sh"
    command: [""]
    working_dir: {{ working_dir }}
#    ports: {{ ports }}
{% if env is defined %}
    environment: {{ env }}
{% endif %}
{% if not use_local_profiles %}
    volumes_from:
    - profile
{% else %}
    volumes:
      - {{ basedir }}/profiles/{{ service_profile_name }}:/config/:ro
{% endif %}
    labels:
      "org.label-schema.schema-version": "1.0.0-rc.1"
      "org.label-schema.name": "{{ service_profile_name }}"
      "org.label-schema.description": "{{ component_label }}"
      "org.label-schema.vendor": "Cisco"
      "org.label-schema.build-date": "{{ img_build_date }}"
      "org.label-schema.vcs-type": "git"
      "org.label-schema.vcs-url": "https://github.com/devops/docker.git"
      "org.label-schema.vcs-ref": "N/A"
      "org.label-schema.cisco.image_tag": "{{ maven_artifact_version }}"
    dev_overrides:
      environment:
        - "DEBUG=1"

registries:
  docker-staging:
    url: {{ docker_registry_name }}/{{ docker_repo_staging }}
 docker-releases:
    url: {{ docker_registry_name }}/{{ docker_repo_releases }}


```

##### main.yml 

```
# This should be your Ansible playbooks to provision your containers.
# An inventory will be automatically created using the names of the services
# from your container.yml file.
# Add any roles or other modules you'll need to this directory too.
# For many examples of roles, check out Ansible Galaxy: https://galaxy.ansible.com/
#
---


- hosts: profile
  any_errors_fatal: true
  gather_facts: false

- hosts: "{{ lookup('env','service_profile_name') }}"
  any_errors_fatal: true
  ignore_errors: no
  gather_facts: true
  vars:
    profile: "{{ lookup('env','profile')|default('general')}}"
    service_name: "{{ lookup('env','service_name') }}"
    service_profile_name: "{{ lookup('env','service_profile_name') }}"
    img_build_date: "{{ lookup('env','img_build_date') }}"
    maven_artifact_version: "{{ lookup('env','maven_artifact_version') }}"

  vars_files:
    - "/ansible-container/services/{{ service_profile_name }}/vars.yml"
  roles:
    - role: install-service
    - role: configure-service

```

##### OS / ENVIRONMENT

```
21/02/17 13:00:17.276 0.2: Pulling from ansible/ansible-container-builder
21/02/17 13:01:25.232 Digest: sha256:ecbf2feee8cfa0b4167ca1bb74bfff62f61c3e7009b048f239da13db3806bc6b
21/02/17 13:01:25.237 Status: Downloaded newer image for ansible/ansible-container-builder:0.2
21/02/17 13:01:25.259 
**21/02/17 13:01:25.259 ERROR: for ansible-container  Conflict. The name "/ansible_ansible-container_1" is already in use by container** 13fd2da4521448029255cd72a7a1a55904ced4714da48b43e30513612462580c. You have to remove (or rename) that container to be able to reuse that name.
21/02/17 13:01:25.260 Cleaning up Ansible Container builder...
21/02/17 13:01:25.261 Cleaning up temporary directory /tmp/tmpuKMWNv...
21/02/17 13:01:25.261 Cleaning up temporary directory /tmp/tmpZ5djRI...
21/02/17 13:01:25.262 No container with the name ansible-container
21/02/17 13:01:25.262 Traceback (most recent call last):
21/02/17 13:01:25.262   File "/usr/lib/python2.7/site-packages/container/cli.py", line 212, in commandline
21/02/17 13:01:25.262     getattr(engine, u'cmdrun_{}'.format(args.subcommand))(**vars(args))
21/02/17 13:01:25.262   File "/usr/lib/python2.7/site-packages/container/engine.py", line 372, in cmdrun_build
21/02/17 13:01:25.262     touched_hosts = set(engine_obj.hosts_touched_by_playbook())
21/02/17 13:01:25.262   File "/usr/lib/python2.7/site-packages/container/docker/engine.py", line 71, in hosts_touched_by_playbook
21/02/17 13:01:25.262     builder_container_id = self.get_builder_container_id()
21/02/17 13:01:25.262   File "/usr/lib/python2.7/site-packages/container/docker/engine.py", line 189, in get_builder_container_id
21/02/17 13:01:25.262     return self.get_container_id_by_name(self.builder_container_img_name)
21/02/17 13:01:25.262   File "/usr/lib/python2.7/site-packages/container/docker/engine.py", line 149, in get_container_id_by_name
21/02/17 13:01:25.262     raise NameError('No container with the name %s' % name)
21/02/17 13:01:25.262 NameError: No container with the name ansible-container
21/02/17 13:01:25.262 Attaching to 
21/02/17 13:01:25.452 [ERROR] Error exec the deployer script
21/02/17 13:01:25.968 [BFA] Scanning build for known causes...
21/02/17 13:01:25.969 [BFA] No failure causes found
21/02/17 13:01:25.969 [BFA] Done. 0s
21/02/17 13:01:25.973 [INFO] ------------------------------------------------------------------------
21/02/17 13:01:25.973 [INFO] BUILD FAILURE
21/02/17 13:01:25.973 [INFO] ------------------------------------------------------------------------
21/02/17 13:01:25.973 [INFO] Total time: 3:01.986s
21/02/17 13:01:25.973 [INFO] Finished at: Tue Feb 21 13:01:24 IST 2017
21/02/17 13:01:26.309 [INFO] Final Memory: 57M/315M
```
##### STEPS TO REPRODUCE

Execute two builds concurrently 

```

```

##### EXPECTED RESULTS

The ansible-contianer-builder will have an option of having to set a name, in order multiple concurrent builds will run independently

##### ACTUAL RESULTS

The ansible-container-builder name is hardcoded:

class Engine(BaseEngine):

    engine_name = 'Docker'
    orchestrator_name = 'Docker Compose'
    **builder_container_img_name = 'ansible-container'**
    builder_container_img_tag = 'ansible-container-builder'
    default_registry_url = 'https://index.docker.io/v1/'
    default_registry_name = 'dockerhub'
    _client = None
    _orchestrated_hosts = None
    api_version = ''
    temp_dir = None

```
21/02/17 13:01:25.259 ERROR: for ansible-container  Conflict. The name "/ansible_ansible-container_1" is already in use by container 13fd2da4521448029255cd72a7a1a55904ced4714da48b43e30513612462580c. You have to remove (or rename) that container to be able to reuse that name.
```
