### ISSUE TITLE
During ansible-container build "TypeError: run() got an unexpected keyword argument 'expose'"

### ISSUE THREAD

**Issue by ehelms** [ansible/ansible-container#478]
##### ISSUE TYPE

 - Bug Report

##### container.yml 

```
---
version: "2"
settings:
  conductor_base: centos:7
defaults:
  POSTGRES_USER: foreman
  POSTGRES_PASSWORD: foreman
  POSTGRES_DB: foreman
  POSTGRES_PORT: 5432
  MONGODB_USER: admin
  MONGODB_PASSWORD: admin
  MONGODB_DATABASE: pulp_database
  MONGODB_PORT: 27017
services:
  foreman:
    from: centos:7
    roles:
      - epel-repositories
      - puppet-repositories
      - foreman-repositories
      - katello-repositories
      - foreman
    command: ['/usr/bin/start-foreman.sh']
    entrypoint: ['/usr/bin/entrypoint.sh']
    environment:
      - POSTGRES_DB={{ POSTGRES_DB }}
      - POSTGRES_USER={{ POSTGRES_USER }}
      - POSTGRES_PASSWORD={{ POSTGRES_PASSWORD }}
      - SEED_ADMIN_USER=admin
      - SEED_ADMIN_PASSWORD=changeme
      - SEED_ORGANIZATION=Default Organization
      - SEED_LOCATION=Raleigh
    ports:
      - 8080:8080
    expose:
      - 8080
  foreman-tasks:
    from: centos:7
    roles:
      - epel-repositories
      - puppet-repositories
      - foreman-repositories
      - katello-repositories
      - foreman
      - foreman-tasks
    command: ['/usr/bin/start-foreman-tasks.sh']
    entrypoint: ['/usr/bin/entrypoint.sh']
    environment:
      - POSTGRES_DB={{ POSTGRES_DB }}
      - POSTGRES_USER={{ POSTGRES_USER }}
      - POSTGRES_PASSWORD={{ POSTGRES_PASSWORD }}
  foreman-proxy:
    from: centos:7
    roles:
      - epel-repositories
      - foreman-repositories
      - foreman-proxy
    command: ['/usr/bin/start-foreman-proxy.sh']
    expose:
      - 8080
  foreman-proxy-register:
    from: centos:7
    roles:
      - epel-repositories
      - foreman-repositories
      - foreman-proxy
    command: ['/usr/bin/register.sh']
    environment:
      - FOREMAN_PROXY_SERVICE_HOST=foreman_proxy
      - FOREMAN_PROXY_SERVICE_PORT=8080
      - FOREMAN_SERVICE_HOST=foreman
      - FOREMAN_SERVICE_PORT=8080
    depends_on:
      - foreman
      - foreman-proxy
  cp-app:
    from: centos:7
    roles:
      - epel-repositories
      - katello-repositories
      - candlepin
    environment:
      - POSTGRES_DB={{ POSTGRES_DB }}
      - POSTGRES_USER={{ POSTGRES_USER }}
      - POSTGRES_PASSWORD={{ POSTGRES_PASSWORD }}
      - POSTGRES_PORT={{ POSTGRES_PORT }}
      - POSTGRES_SERVICE=postgres
      - QPID_SERVICE=qpid
      - QPID_PORT=5672
    expose:
      - 8080
    command: ['/usr/bin/start_candlepin.sh']
    entrypoint: ['/usr/bin/entrypoint.sh']
    options:
      kube:
        runAsUser: 1000
  qpid:
    from: centos:7
    roles:
      - epel-repositories
      - qpid
    command: ['/usr/bin/startup.sh']
    expose:
      - 5672
  pulp:
    from: centos:7
    roles:
      - epel-repositories
      - katello-repositories
      - pulp
    command: ['/usr/bin/start_httpd.sh']
    entrypoint: ['/usr/bin/entrypoint.sh']
    expose:
      - 8080
    depends_on:
      - qpid
      - mongodb
  pulp-worker:
    from: centos:7
    roles:
      - epel-repositories
      - katello-repositories
      - pulp
      - pulp-worker
    entrypoint: ['/usr/bin/entrypoint.sh']
    depends_on:
      - qpid
      - pulp
    depends_on:
      - mongodb
    volumes:
      - pulp-data:/var/lib/pulp
      - puppet-data:/etc/puppet
    options:
      openshift:
        persistent_volume_claims:
          - volume_name: pulp-data
            claim_name: pulp-data
            access_modes:
              - ReadWriteMany
          - volume_name: puppet-data
            claim_name: puppet-data
            access_modes:
              - ReadWriteMany
  pulp-resource-manager:
    from: centos:7
    roles:
      - epel-repositories
      - katello-repositories
      - pulp
      - pulp-resource-manager
    depends_on:
      - qpid
      - pulp
    entrypoint: ['/usr/bin/entrypoint.sh']
  pulp-celerybeat:
    from: centos:7
    roles:
      - epel-repositories
      - katello-repositories
      - pulp
      - pulp-celerybeat
    entrypoint: ['/usr/bin/entrypoint.sh']
    depends_on:
      - qpid
      - pulp
  puppet:
    from: puppet/puppetserver
    volumes:
      - puppet-data:/etc/puppet
    expose:
      - 8140
    options:
      openshift:
        persistent_volume_claims:
          - volume_name: puppet-data
            claim_name: puppet-data
            access_modes:
              - ReadWriteMany
  postgres:
    from: ansible/postgresql:latest
    environment:
      - POSTGRES_DB={{ POSTGRES_DB }}
      - POSTGRES_USER={{ POSTGRES_USER }}
      - POSTGRES_PASS={{ POSTGRES_PASSWORD }}
      - PGDATA=/var/lib/pgsql/data/userdata
    volumes:
      - postgres-data:/var/lib/pgsql/data
    expose:
      - "{{ POSTGRES_PORT }}"
    options:
      openshift:
        persistent_volume_claims:
          - volume_name: postgres-data
            claim_name: postgres-data
            access_modes:
              - ReadWriteMany
  mongodb:
    from: centos/mongodb-26-centos7:latest
    environment:
      - MONGODB_USER={{ MONGODB_USER }}
      - MONGODB_PASSWORD={{ MONGODB_PASSWORD }}
      - MONGODB_DATABASE={{ MONGODB_DATABASE }}
      - MONGODB_ADMIN_PASSWORD={{ MONGODB_PASSWORD }}
    volumes:
      - mongodb-data:/var/lib/mongodb/data
    expose:
      - "{{ MONGODB_PORT }}"
    options:
      openshift:
        persistent_volume_claims:
          - volume_name: mongodb-data
            claim_name: mongodb-data
            access_modes:
              - ReadWriteMany
volumes:
  postgres-data: {}
  mongodb-data: {}
  puppet-data: {}
  pulp-data: {}
registries:
  oc-cluster:
    url: http://172.30.1.1:5000
    namespace: foreman
  # Add optional registries used for deployment. For example:
  #  google:
  #    url: https://gcr.io
  #    namespace: my-cool-project-xxxxxx
```

##### OS / ENVIRONMENT

```
Ansible Container, version 0.9.1rc0
Linux, war.eagle, 4.6.6-200.fc23.x86_64, #1 SMP Wed Aug 10 23:13:35 UTC 2016, x86_64
2.7.11 (default, Jul  8 2016, 19:45:00) 
[GCC 5.3.1 20160406 (Red Hat 5.3.1-6)] /usr/bin/python
{
  "ContainersPaused": 0, 
  "Labels": null, 
  "DefaultRuntime": "runc", 
  "CgroupDriver": "cgroupfs", 
  "ContainersRunning": 0, 
  "NGoroutines": 28, 
  "Swarm": {
    "Managers": 0, 
    "ControlAvailable": false, 
    "NodeID": "", 
    "Cluster": {
      "Spec": {
        "Raft": {}, 
        "CAConfig": {}, 
        "Dispatcher": {}, 
        "Orchestration": {}, 
        "TaskDefaults": {}
      }, 
      "Version": {}, 
      "ID": "", 
      "CreatedAt": "0001-01-01T00:00:00Z", 
      "UpdatedAt": "0001-01-01T00:00:00Z"
    }, 
    "Nodes": 0, 
    "Error": "", 
    "RemoteManagers": null, 
    "LocalNodeState": "inactive", 
    "NodeAddr": ""
  }, 
  "LoggingDriver": "json-file", 
  "OSType": "linux", 
  "HttpProxy": "", 
  "Runtimes": {
    "runc": {
      "path": "docker-runc"
    }
  }, 
  "DriverStatus": [
    [
      "Pool Name", 
      "docker-253:3-17170446-pool"
    ], 
    [
      "Pool Blocksize", 
      "65.54 kB"
    ], 
    [
      "Base Device Size", 
      "10.74 GB"
    ], 
    [
      "Backing Filesystem", 
      "xfs"
    ], 
    [
      "Data file", 
      "/dev/loop0"
    ], 
    [
      "Metadata file", 
      "/dev/loop1"
    ], 
    [
      "Data Space Used", 
      "7.028 GB"
    ], 
    [
      "Data Space Total", 
      "107.4 GB"
    ], 
    [
      "Data Space Available", 
      "100.3 GB"
    ], 
    [
      "Metadata Space Used", 
      "10.54 MB"
    ], 
    [
      "Metadata Space Total", 
      "2.147 GB"
    ], 
    [
      "Metadata Space Available", 
      "2.137 GB"
    ], 
    [
      "Thin Pool Minimum Free Space", 
      "10.74 GB"
    ], 
    [
      "Udev Sync Supported", 
      "true"
    ], 
    [
      "Deferred Removal Enabled", 
      "false"
    ], 
    [
      "Deferred Deletion Enabled", 
      "false"
    ], 
    [
      "Deferred Deleted Device Count", 
      "0"
    ], 
    [
      "Data loop file", 
      "/home/docker/devicemapper/devicemapper/data"
    ], 
    [
      "Metadata loop file", 
      "/home/docker/devicemapper/devicemapper/metadata"
    ], 
    [
      "Library Version", 
      "1.02.109 (2015-09-22)"
    ]
  ], 
  "OperatingSystem": "Fedora 23 (Workstation Edition)", 
  "Containers": 0, 
  "HttpsProxy": "", 
  "BridgeNfIp6tables": true, 
  "MemTotal": 16700760064, 
  "Driver": "devicemapper", 
  "IndexServerAddress": "https://index.docker.io/v1/", 
  "ClusterStore": "", 
  "ExecutionDriver": "", 
  "SystemStatus": null, 
  "OomKillDisable": true, 
  "ClusterAdvertise": "", 
  "SystemTime": "2017-05-02T14:42:34.666369675-04:00", 
  "Name": "war.eagle", 
  "CPUSet": true, 
  "RegistryConfig": {
    "InsecureRegistryCIDRs": [
      "172.30.0.0/16", 
      "127.0.0.0/8"
    ], 
    "IndexConfigs": {
      "docker.io": {
        "Official": true, 
        "Name": "docker.io", 
        "Secure": true, 
        "Mirrors": null
      }
    }, 
    "Mirrors": null
  }, 
  "SecurityOptions": [
    "seccomp"
  ], 
  "ContainersStopped": 0, 
  "NCPU": 8, 
  "NFd": 18, 
  "Architecture": "x86_64", 
  "KernelMemory": true, 
  "CpuCfsQuota": true, 
  "Debug": false, 
  "ID": "PP7J:YWUF:VJG7:OPQQ:AVCZ:BEIA:XEX2:BB7W:ELOD:I2QM:O472:Y2MB", 
  "IPv4Forwarding": true, 
  "KernelVersion": "4.6.6-200.fc23.x86_64", 
  "BridgeNfIptables": true, 
  "NoProxy": "", 
  "LiveRestoreEnabled": false, 
  "ServerVersion": "1.12.6", 
  "CpuCfsPeriod": true, 
  "ExperimentalBuild": false, 
  "MemoryLimit": true, 
  "SwapLimit": true, 
  "Plugins": {
    "Volume": [
      "local"
    ], 
    "Network": [
      "null", 
      "bridge", 
      "host", 
      "overlay"
    ], 
    "Authorization": null
  }, 
  "Images": 13, 
  "DockerRootDir": "/home/docker", 
  "NEventsListener": 0, 
  "CPUShares": true
}
{
  "KernelVersion": "4.6.6-200.fc23.x86_64", 
  "Os": "linux", 
  "BuildTime": "2017-01-10T20:21:11.017972579+00:00", 
  "ApiVersion": "1.24", 
  "Version": "1.12.6", 
  "GitCommit": "78d1802", 
  "Arch": "amd64", 
  "GoVersion": "go1.6.4"
}
```
##### SUMMARY

```
Traceback (most recent call last):
  File "/usr/bin/conductor", line 11, in <module>
    load_entry_point('ansible-container', 'console_scripts', 'conductor')()
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/cli.py", line 349, in conductor_commandline
    **params)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/core.py", line 682, in conductorcmd_build
    container_id = engine.run_container(cur_image_id, service_name, **run_kwargs)
  File "/_ansible/container/docker/engine.py", line 81, in __wrapped__
    return fn(self, *args, **kwargs)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/docker/engine.py", line 189, in run_container
    **run_kwargs
  File "/usr/lib/python2.7/site-packages/docker/models/containers.py", line 660, in run
    detach=detach, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/models/containers.py", line 703, in create
    create_kwargs = _create_container_args(kwargs)
  File "/usr/lib/python2.7/site-packages/docker/models/containers.py", line 884, in _create_container_args
    raise create_unexpected_kwargs_error('run', kwargs)
TypeError: run() got an unexpected keyword argument 'expose'
```

##### STEPS TO REPRODUCE

```
ansible-container build
```

**Comment by chouseknecht** [comment]
Quick glance at engine.run_container() seems like we're passing `expose` to the call to client.containers.run().

**Comment by wbrefvem** [comment]
@chouseknecht I saw something similar when trying to build the apache container from the getting started guide. By the time the time the service definition in `container.yml` got passed to the conductor, the web key's children (i.e., all the params for `client.container.run()` were wrapped by an `apache` key. I'm pretty sure it's happening somewhere in `container.docker.engine.Engine.run_container`, but I'm not entirely sure where.

**Comment by chouseknecht** [comment]
@wbrefvem 

Thanks for pointing this out. I'll run through the getting started example, and attempt to reproduce. In the meantime, if you have the output from a run with the `--debug` option, it would be quite helpful.

**Comment by wbrefvem** [comment]
@chouseknecht 

This log line prints the params passed to `client.container.run`:

```
2017-05-02T19:55:31.064582 Running container in docker    
[container.docker.engine] 
caller_file=/_ansible/container/docker/engine.py 
caller_func=run_container caller_line=185 image=u'sha256:a8493f5f50ffda70c2eeb2d09090debf7d39c8ffcd63b43ff81b111ece6f28bf' 
params={"apache": {"image": "centos:7", "entrypoint": ["/usr/bin/entrypoint.sh"], "working_dir": "/", "user": "apache", "command": ["/usr/bin/dumb-init", "httpd", "-DFOREGROUND"], "ports": ["80:8080", "443:8443"]}, "command": "sh -c \"while true; do sleep 1; done\"", "ports": {"80": ["80"]}, "name": "empty-dir_web", "environment": {"PYTHONPATH": "/_usr/lib/python2.7", "CPATH": "/_usr/include:/_usr/local/include", "LD_LIBRARY_PATH": "/_usr/lib:/_usr/lib64:/_usr/local/lib", "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/_usr/sbin:/_usr/bin:/_usr/local/sbin:/_usr/local/bin"}, "working_dir": "/", "entrypoint": [], "user": "root", "volumes": {"60da23652bdc474e54168ec4e1a2f524ed4c291fe0851f3a2106348bb6787212": {"bind": "/_usr", "mode": "ro"}}, "privileged": true}
```
`params` is built from a call to `Engine.run_kwargs_for_service`, which in turn calls `self.services`, which returns the following`ordereddict`:
```
2017-05-02T19:55:31.062551 to_return: 
ordereddict([('apache', ordereddict([('image', 'centos:7'), ('entrypoint', ['/usr/bin/entrypoint.sh']), ('working_dir', '/'), ('user', 'apache'), ('command', ['/usr/bin/dumb-init', 'httpd', '-DFOREGROUND']), ('ports', ['80:8080', '443:8443'])])), (u'command', ['/usr/bin/dumb-init', '/usr/sbin/apache2ctl', '-D', 'FOREGROUND']), (u'from', u'centos:7'), (u'ports', ['80:80']), (u'roles', ['apache-container']), ('defaults', ordereddict([('APACHE_HOSTNAME', 'localhost'), ('APACHE_SSL', 1), ('APACHE_PORT', 8080), ('APACHE_SSL_PORT', 8443), ('APACHE_SSL_PROTOCOLS', 'All -SSLv2 -SSLv3'), ('APACHE_SSL_CIPHER_SUITE', 'AES256+EECDH:AES256+EDH'), ('APACHE_ALLOW_OVERRIDE', 'All'), ('APACHE_VHOST_OPTIONS', 'Indexes FollowSymLinks'), ('APACHE_DEFAULT_CHARSET', 'UTF-8'), ('APACHE_EXTRA_PARAMETERS', []), ('APACHE_ASSET_PATHS', ['./files'])]))]) 
[container.docker.engine] 
caller_file=/_ansible/container/docker/engine.py 
caller_func=run_kwargs_for_service 
caller_line=159
 ```
This leads me to believe that the bug is in the initialization of the service dict, which as far as I can tell doesn't get touched after the `Engine` object is created.

**Comment by ehelms** [comment]
Thanks for the quick turn around!

**Comment by chouseknecht** [comment]
@wbrefvem 

I'm looking at the [Real world usage](http://docs.ansible.com/ansible-container/getting_started.html#real-world-usage-starting-from-a-working-base-setup) example found in our [Getting Started guide](http://docs.ansible.com/ansible-container/getting_started.html). However, that doesn't have an `apache` service in it, so not sure where your example is coming from. 

Perhaps what you're doing is using the example container.yml from the [Dipping a Toe In section](http://docs.ansible.com/ansible-container/getting_started.html#dipping-a-toe-in-starting-from-scratch) that looks like the following, and modifying it:

```yaml
version: "2"
services:
  web:
    from: "ubuntu:trusty"
    ports:
      - "80:80"
    command: ["/usr/bin/dumb-init", "/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
    dev_overrides:
      environment:
        - "DEBUG=1"
```

If you can point me in the right direction, I'll try to reproduce what you're seeing.

**Comment by wbrefvem** [comment]
@chouseknecht 

I'm using `container.yml` as is after running `ansible-container init`, which is different from what's in the docs. The only modification I made was to delete the curly braces after the `services` key and uncomment the `web` service:

```yaml
services:
  # Add your containers here, specifying the base image you want to build from
  # For example:

  web:
    from: centos:7
    roles:
      - apache-container
    ports:
      - "80:80"
    command: ['/usr/bin/dumb-init', '/usr/sbin/apache2ctl', '-D', 'FOREGROUND']
    dev_overrides:
      environment:
        - "DEBUG=1"
```
This throws an error if there's no apache-container role installed, so after searching Ansible Galaxy,I  also installed the following `requirements.yml` with `apache-galaxy install`:

```yaml
- src: chouseknecht.apache-container
  name: apache-container
```
Which yelled because I didn't use `ansible-container install`, which I tried to run but got this:

```
ERROR	Invalid container.yml: Error: no definition found in container.yml for service For example.
```
After that, I ran the build and got the results described in my previous comments.

Using the `container.yml` from the docs seems to work, so this is likely PEBKAC on my part. I didn't think to check the `container.yml` I got from `ansible-container init` against the one in the docs.
