### ISSUE TITLE
Role caching is too eager

### ISSUE THREAD

**Issue by ddelbondio** [ansible/ansible-container#482]
##### ISSUE TYPE
 - Bug Report

##### container.yml 
```
version: "2"
settings:
  conductor_base: debian:8.6

services:
  eager-cache:
    from: debian:8.6
    roles:
      - common

registries: {}
```

##### roles/common/tasks/main.yml
```
- shell: echo $(date) > /buildstamp
```

##### OS / ENVIRONMENT
```
Ansible Container, version 0.9.1rc0
...
```

##### SUMMARY
`get_role_fingerprint` only takes the content of the role into account. While the example above is a little contrived it, this is a real issue when doing updates using the package manager for example. There you expect different results even though the role itself has not changed at all.

##### STEPS TO REPRODUCE
run `ansible-container build` twice

##### EXPECTED RESULTS
Two images with different values in /buildstamp

##### ACTUAL RESULTS
Only one image is produced

##### Discussion
I think that keeping the role caching behaviour would be fine if there was a way to disable the cache without also disabling the conductor cache, as done by --no-cache. I think it makes sense to split --no-cache into --no-conductor-cache and --no-(container|service|?)-cache.
