### ISSUE TITLE
Ansible Options cause build to fail

### ISSUE THREAD

**Issue by aaronthebaron** [ansible/ansible-container#499]
##### ISSUE TYPE

 - Bug Report

##### container.yml 

I've removed some sensitive information.
```
version: "2"
settings:
  conductor_base: [registry_url]/pl-ubuntu:trusty
services:
  app:
    roles:
      - container
      - webserver
    from: [registry_url]/pl-ubuntu:trusty
    command: ["/run.sh"]

registries: {}
```

##### OS / ENVIRONMENT

```
Ansible Container, version 0.9.1rc0
Darwin, Wintermute, 15.6.0, Darwin Kernel Version 15.6.0: Fri Feb 17 10:21:18 PST 2017; root:xnu-3248.60.11.4.1~1/RELEASE_X86_64, x86_64
3.6.1 (default, Mar 23 2017, 16:49:01)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] 
```
##### SUMMARY

When I try to build containers with added `ansible_options` the build always fails. It does not seem to change no matter how I format the options. It always fails with the following error information:
```
ERROR! the playbook: [u--tags=api_workplace_container, could not be found
```
It seems that the options are being stored in the ansible command dict as a dict. If I convert them into a string for the command, the build works fine. I will upload a PR with the change I made that allows the containers to build. It's difficult to test these changes however, as it seems like the tests have not been upgraded for 0.9.x

##### STEPS TO REPRODUCE

```
ansible-container --var-file vars/main.secret.yml build --flatten --roles-path /deployment/roles --with-volumes /deployment/environment:/environment --with-variables FLAVOR=stag api_workplace_treeish=77777777 -- --tags "api_workplace_container,api_workplace_app_container" --skip-tags "always" --extra-vars "'FLAVOR=stag api_workplace_treeish=77777777'"
```

##### EXPECTED RESULTS
Successful Build

##### ACTUAL RESULTS

```
ERROR! the playbook: [u--tags=api_workplace_container, could not be found
```
