### ISSUE TITLE
container.yml: volumes doesn't support ${PWD}

### ISSUE THREAD

**Issue by lorin** [ansible/ansible-container#502]
The `volumes` field in container.yml allows you to specify `$PWD` but not `${PWD}`. For example, this is fine:

```
version: '2'
services:
  web:
    ...
    dev_overrides:
      volumes:
        - $PWD/certs:/certs
```

But this doesn't work:

```
version: '2'
services:
  web:
    ...
    dev_overrides:
      volumes:
        - ${PWD}/certs:/certs
```

This is unexpected for folks coming over from Docker Compose, which supports both formats. And, indeed, even the [Ansible Container docs](http://docs.ansible.com/ansible-container/container_yml/reference.html#dev-overrides) have an example that uses `${PWD}`.

It looks like the offending code is in [container/config.py](https://github.com/ansible/ansible-container/blob/develop/container/config.py#L276)
