### ISSUE TITLE
ansible-container 0.9.0 fails to mount volumes during build

### ISSUE THREAD

**Issue by rokroskar** [ansible/ansible-container#522]
##### ISSUE TYPE
 - Bug Report

##### container.yml 
```
version: "2"
services:
  jupyterhub:
    from: centos
    ports:
      - "9000:8000"
    volumes:
      - ~/user-data/notebooks:/notebooks
      - ~/user-data/data:/data
      - ~/user-data/home-dirs:/home-dirs
    roles:
      - jupyterhub
    command: "jupyterhub" 
    working_dir: /usr/local/jupyterhub 
    user: jupyterhub
    environment:
      PATH: /usr/local/miniconda/envs/python35/bin:$PATH"
    
registries: {}

```

##### OS / ENVIRONMENT

```
Ansible Container, version 0.9.0.0
Darwin, id-als-docking-130.ethz.ch, 14.5.0, Darwin Kernel Version 14.5.0: Fri Feb 17 10:33:20 PST 2017; root:xnu-2782.50.9.1.1~1/RELEASE_X86_64, x86_64
2.7.10 (default, Jul 14 2015, 19:46:27)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] /Users/rok/Projects/holdem-server/test_env/bin/python
{
  "ContainersPaused": 0,
  "Labels": null,
  "CgroupDriver": "cgroupfs",
  "ContainersRunning": 2,
  "ContainerdCommit": {
    "Expected": "aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1",
    "ID": "aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1"
  },
  "InitBinary": "docker-init",
  "NGoroutines": 41,
  "Swarm": {
    "Managers": 0,
    "ControlAvailable": false,
    "NodeID": "",
    "Cluster": {
      "Spec": {
        "TaskDefaults": {},
        "Orchestration": {},
        "EncryptionConfig": {
          "AutoLockManagers": false
        },
        "Raft": {
          "HeartbeatTick": 0,
          "ElectionTick": 0
        },
        "CAConfig": {},
        "Dispatcher": {}
      },
      "Version": {},
      "ID": "",
      "CreatedAt": "0001-01-01T00:00:00Z",
      "UpdatedAt": "0001-01-01T00:00:00Z"
    },
    "Nodes": 0,
    "Error": "",
    "RemoteManagers": null,
    "LocalNodeState": "inactive",
    "NodeAddr": ""
  },
  "LoggingDriver": "json-file",
  "OSType": "linux",
  "HttpProxy": "",
  "Runtimes": {
    "runc": {
      "path": "docker-runc"
    }
  },
  "DriverStatus": [
    [
      "Root Dir",
      "/var/lib/docker/aufs"
    ],
    [
      "Backing Filesystem",
      "extfs"
    ],
    [
      "Dirs",
      "163"
    ],
    [
      "Dirperm1 Supported",
      "true"
    ]
  ],
  "OperatingSystem": "Alpine Linux v3.5",
  "Containers": 6,
  "HttpsProxy": "",
  "BridgeNfIp6tables": true,
  "MemTotal": 2095988736,
  "SecurityOptions": [
    "name=seccomp,profile=default"
  ],
  "Driver": "aufs",
  "IndexServerAddress": "https://index.docker.io/v1/",
  "ClusterStore": "",
  "InitCommit": {
    "Expected": "949e6fa",
    "ID": "949e6fa"
  },
  "Isolation": "",
  "SystemStatus": null,
  "OomKillDisable": true,
  "ClusterAdvertise": "",
  "SystemTime": "2017-05-16T12:42:03.940445925Z",
  "Name": "moby",
  "CPUSet": true,
  "RegistryConfig": {
    "InsecureRegistryCIDRs": [
      "127.0.0.0/8"
    ],
    "IndexConfigs": {
      "docker.io": {
        "Official": true,
        "Name": "docker.io",
        "Secure": true,
        "Mirrors": null
      }
    },
    "Mirrors": []
  },
  "DefaultRuntime": "runc",
  "ContainersStopped": 4,
  "NCPU": 4,
  "NFd": 30,
  "Architecture": "x86_64",
  "KernelMemory": true,
  "CpuCfsQuota": true,
  "Debug": true,
  "ID": "JWZD:ZOZM:G5BS:NHZC:WZB7:WF3O:XH3Y:COYQ:SQTH:4MRK:W5TA:V6K2",
  "IPv4Forwarding": true,
  "KernelVersion": "4.9.8-moby",
  "BridgeNfIptables": true,
  "NoProxy": "*.local, 169.254/16",
  "LiveRestoreEnabled": false,
  "ServerVersion": "1.13.1",
  "CpuCfsPeriod": true,
  "ExperimentalBuild": true,
  "MemoryLimit": true,
  "SwapLimit": true,
  "Plugins": {
    "Volume": [
      "local"
    ],
    "Network": [
      "bridge",
      "host",
      "ipvlan",
      "macvlan",
      "null",
      "overlay"
    ],
    "Authorization": null
  },
  "Images": 118,
  "DockerRootDir": "/var/lib/docker",
  "NEventsListener": 1,
  "CPUShares": true,
  "RuncCommit": {
    "Expected": "9df8b306d01f59d3a8029be411de015b7304dd8f",
    "ID": "9df8b306d01f59d3a8029be411de015b7304dd8f"
  }
}
{
  "KernelVersion": "4.9.8-moby",
  "Arch": "amd64",
  "BuildTime": "2017-02-08T08:47:51.966588829+00:00",
  "ApiVersion": "1.26",
  "Version": "1.13.1",
  "MinAPIVersion": "1.12",
  "GitCommit": "092cba3",
  "Os": "linux",
  "Experimental": true,
  "GoVersion": "go1.7.5"
}
```
##### SUMMARY
When upgrading to v0.9.0, the ansible role fails to make directories in the mounted volume. Previous versions work fine with the same playbook. Did I miss some new option/syntax for this upgrade? 

##### STEPS TO REPRODUCE

```
- name: create users 
  user: 
    name: "{{ item.key }}" 
    groups: jupyterhub 
    append: yes 
    shell: /bin/bash 
    password: "{{ item.value }}" 
    home: /home-dirs/{{ item.key }}
    update_password: on_create
  with_dict: "{{ users }}" 
```

Inspecting the container that was created for the build also shows no mounted volumes:

```
"Mounts": [
            {
                "Type": "volume",
                "Name": "ce26b01ceb6bb173e23e5058f84eaa3629d99c2d6b9b3b0ed910128407b74878",
                "Source": "/var/lib/docker/volumes/ce26b01ceb6bb173e23e5058f84eaa3629d99c2d6b9b3b0ed910128407b74878/_data",
                "Destination": "/_usr",
                "Driver": "local",
                "Mode": "ro",
                "RW": false,
                "Propagation": ""
            }
        ]
```
##### EXPECTED RESULTS
the volumes should be mounted 

##### ACTUAL RESULTS

No mounted volumes, build fails

```
failed: [jupyterhub] (item={'key': u'schmittu', 'value': u'$6$rounds=656000$WYf7MNDR.IT9MVmm$jdoBmLNeW4Hp76YXSkII6T8reZuuS01nbM1BHQJm6gAsH84Rc.u/jANUIUy.nB0adN08i/F1NNOYxrF/AzjXO0'}) => {"failed": true, "item": {"key": "schmittu", "value": "$6$rounds=656000$WYf7MNDR.IT9MVmm$jdoBmLNeW4Hp76YXSkII6T8reZuuS01nbM1BHQJm6gAsH84Rc.u/jANUIUy.nB0adN08i/F1NNOYxrF/AzjXO0"}, "msg": "useradd: cannot create directory /home-dirs/schmittu\n", "name": "schmittu", "rc": 12}
	to retry, use: --limit @/tmp/tmpHgP8Eh/playbook.retry
```

**Comment by rokroskar** [comment]
thanks for the quick fix @chouseknecht!

However, using the develop branch still fails: 

```
OSError: [Errno 2] No such file or directory: '...../lib/python2.7/site-packages/ansible_container-0.9.1rc0-py2.7.egg/container/docker/files/setup.py'
```

I installed the develop branch with `python setup.py install`

**Comment by rokroskar** [comment]
sorry, this still doesn't seem to work. Using latest from the `develop` branch and this `conductor.yml`:

```
version: "2"

services: 
  test: 
    from: 'centos:7'
    volumes: 
      - /Users/rok/test-dir:/test-dir
    roles: 
      - yum
```

doing `docker inspect` on the container during build:

```
"Mounts": [
            {
                "Type": "volume",
                "Name": "f6fdc67476a50802cf98b6161a05f46593a0383613806e42b0e37b119582cd4f",
                "Source": "/var/lib/docker/volumes/f6fdc67476a50802cf98b6161a05f46593a0383613806e42b0e37b119582cd4f/_data",
                "Destination": "/_usr",
                "Driver": "local",
                "Mode": "ro",
                "RW": false,
                "Propagation": ""
            }
        ],
```

And after `ansible-container run`:

```json
"Mounts": [
            {
                "Type": "bind",
                "Source": "/Users/rok/test-dir",
                "Destination": "/test-dir",
                "Mode": "rw",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "bfdf70c71357466aba9e949c72a2ba6a056f208ad28073270b9c9a0a5c29d965",
                "Source": "/var/lib/docker/volumes/bfdf70c71357466aba9e949c72a2ba6a056f208ad28073270b9c9a0a5c29d965/_data",
                "Destination": "/_usr",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
```

So, clearly the volume mounts are being skipped at build time. Is there some other place I'm supposed to specify that they are to be used during the build?

**Comment by hardyoyo** [comment]
This is resolved, however, there is an unanswered question at the end of the comments. I found this issue by searching for an error message I am seeing which is similar to the one posted above. I suspect I have a minor configuration issue I need to figure out... however... I have no clue what it might be (since the error message does not point to which volumes line that might be the problem in my container.yml file). Help?

Error message I'm seeing: `docker.errors.APIError: 400 Client Error: Bad Request ("invalid volume spec "/": invalid volume specification: '/': invalid mount config for type "volume": invalid specification: destination can't be '/'")` and the volumes config I'm attempting to use: 
```
services: 
  tomcat:
    from: "tomcat:alpine"
    ports:
      - "8080:8080"
    volumes:
      - "./tomcat_conf:/usr/local/tomcat/conf"
      - "./webapps:/opt/webapps"
```
Since I have no idea which volumes line might be the problem, I will comment them all out and destroy, and try building again with each line uncommented.

**Comment by andyshinn** [comment]
Is it possible this is a bug with Docker for Mac? I have the same issue even with a very basic `container.yml` when specifying the `roles_path`:

```
version: "2"
settings:
  conductor:
    base: centos:7
    roles_path: ansible/roles
  project_name: test
services:
  jboss:
    from: centos:7
    roles:
      - base
```
