### ISSUE TITLE
PYTHONPATH breaks python3* pkg installations on Ubuntu

### ISSUE THREAD

**Issue by michalmedvecky** [ansible/ansible-container#551]
I am not sure whether this is a bug report or not, but:

```
Ansible Container, version 0.9.1rc0
Linux, funnybuilder, 4.8.0-51-generic, #54-Ubuntu SMP Tue Apr 25 16:32:21 UTC 2017, x86_64
2.7.12+ (default, Sep 17 2016, 12:08:02)
[GCC 6.2.0 20160914] /home/misko/ac/bin/python2
ERROR	No Ansible Container project data found - do you need to run "ansible-container init"?
```

`container.yml`:
```
version: "2"
settings:
  conductor_base: ubuntu:16.04
services:
  ssportal:
    from: ubuntu:16.04
    roles:
      - ansible-test
    ports:
    - 80
    entrypoint: ['/usr/bin/dumb-init', '/usr/bin/entrypoint.sh']
volumes:
  static:
    docker: {}
registries: {}
```

`ansible-test/tasks/main.yml`:

```
- name: Install pip
  apt: name="{{ item }}" state=installed update_cache=yes cache_valid_time=3600
  with_items:
    - git
    - python3-pip
```

`ansible-container build` ends up with

```
"SyntaxError: invalid syntax", "", "Current thread 0x00007efe3aa82700 (most recent call first):", "Aborted (core dumped)", "dpkg: error processing package python3-pip (--configure):", " subprocess installed post-installation script returned error exit status 134", "Setting up python3-pkg-resources (20.7.0-1) ...", "Fatal Python error: Py_Initialize: Unable to get the locale encoding", "  File \"/_usr/lib/python2.7/encodings/__init__.py\", line 123", "    raise CodecRegistryError,\\", "                            ^", "SyntaxError: invalid syntax", "", "Current thread 0x00007fb9690fb700 (most recent call first):", "Aborted (core dumped)", "dpkg: error processing package python3-pkg-resources (--configure):", " subprocess installed post-installation script returned error exit status 134", "dpkg: dependency problems prevent configuration of python3-setuptools:", " python3-setuptools depends on python3-pkg-resources (= 20.7.0-1); however:", "  Package python3-pkg-resources is not configured yet.", "", "dpkg: error processing package python3-setuptools (--configure):", " dependency proble
```

After googling for this message (`Fatal Python error: Py_Initialize: Unable to get the locale encoding`) you find out you have to unset `PYTHONPATH` which is hardwired into https://github.com/ansible/ansible-container/blob/develop/container/core.py#L709

Unsetting `PYTHONPATH` makes things work again.

The question, why Ansible works (gathering facts, running some dummy tasks) against `ubuntu:16.04` image, where there is no Python by default, remains unanswered.
