### ISSUE TITLE
Make conductor template proxy aware (inject custom ENV)

### ISSUE THREAD

**Issue by alesz** [ansible/ansible-container#566]
##### ISSUE TYPE

 - Feature Idea

##### container.yml 

Proposal:
```
settings:
  conductor_base: centos:7
  conductor_environment:
  - "http_proxy=http://proxy-prod:3128"
  - "https_proxy=http://proxy-prod:3128"
  dev_overrides:
    conductor_environment:
    - "http_proxy=http://proxy-dev:3128"
    - "https_proxy=http://proxy-dev:3128"
```

##### SUMMARY

Conductor build fails in explicit proxy environment.
Update `ansible-container/container/docker/templates/conductor-dockerfile.j2` to allow adding custom ENV variables

##### STEPS TO REPRODUCE

```
ansible-container build
```

##### EXPECTED RESULTS

Fetch packages using http_proxy or https_proxy environment variables (if set)

##### ACTUAL RESULTS

Build fails

```

```

**Comment by chouseknecht** [comment]
Adding a `conductor` section to `settings` in `container.yml` that will include `base`, 'environment` and `volumes` attributes. For example:

```
version: '2'
settings:
    conductor:
        base: 'centos:7'
        volumes:
        - tmp-space:/tmp
        environment:
        - http_proxy=http://proxy-dev:3128
        - https_proxy=http://proxy-dev:3128
```

We'll still honor `conductor_base` in settings, so as not to break things.

**Comment by MohamedTalhaoui** [comment]
Hi,

what is the status here ?
This is documented on the ansible-container official documentation but cannot make it work.

I used:
```
settings:
  conductor:
    base: centos:7
    environment:
        http_proxy: http://<proxy_host>:<proxy_port>
        https_proxy: http:/<proxy_host>:<proxy_port>
```
but the environment variables are not set in the base image making the yum update fails:

```
Step 1/12 : FROM centos:7
 ---> 328edcd84f1b
Step 2/12 : ENV ANSIBLE_CONTAINER 1
 ---> Using cache
 ---> 88c7a62b0093
Step 3/12 : RUN yum update -y &&     yum install -y epel-release &&     yum install -y make gcc git python-devel curl rsync libffi-devel openssl-devel &&     yum remove -y python-chardet &&     yum clean all
 ---> Running in bb1e428d4b8b
Loaded plugins: fastestmirror, ovl


 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=<repoid> ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable <repoid>
        or
            subscription-manager repos --disable=<repoid>

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true

Cannot find a valid baseurl for repo: base/7/x86_64

Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=container error was
14: curl#7 - "Failed to connect to 2001:4178:5:200::10: Cannot assign requested address"

```

Thanks.
