### ISSUE TITLE
Possibility to run individual tasks for a service

### ISSUE THREAD

**Issue by HackerMD** [ansible/ansible-container#595]
##### ISSUE TYPE

 Feature Idea

It would be very useful to be able to run individual tasks for a service, for example for testing or debugging purposes (reporting issues on Github), without having to create a role. This would be consistent with the use of [roles in playbooks](https://docs.ansible.com/ansible/playbooks_roles.html#roles).

```yaml
version: "2"

settings:

  conductor_base: centos:7

services:

  foo:
    from: centos:7

    pre_tasks:
      - shell: echo 'hello'

    roles:
      - { role: some_role }

    tasks:
      - shell: echo 'still busy'

    post_tasks:
      - shell: echo 'goodbye'
```
