### ISSUE TITLE
How do I execute the yml script generated by ansible-container deploy

### ISSUE THREAD

**Issue by mchassy** [ansible/ansible-container#641]
##### ISSUE TYPE
 - Question

##### container.yml 

```
version: "2"
settings:
  conductor:
    base: "centos:7"

services:
  mongo:
    from: "centos:7"
    roles:
    - role: mongo_role
    working_dir: "/opt"
    user: orson
    expose:
      - 27017
    volumes:
      - mongo_data:/opt/orson/mongo/data
    dev_overides:
      links:
        tomee
    entrypoint: [/entrypoint.sh]
    command: [/usr/bin/dumb-init, /opt/orson/mongo/bin/mongod --config /opt/orson/mongo/conf/mongod.conf]
  tomee:
    from: "centos:7"
    roles:
    - role: tomee_role
    working_dir: "/opt"
    ports:
      - 8080:8080
    dev_overides:
      links:
        mongo
    user: orson
    entrypoint: [/entrypoint.sh]
    command: [/usr/bin/dumb-init, /opt/orson/tomee/bin/catalina.sh, run]
volumes:
  mongo_data:
    docker: {}

registries:
  docker:
    url: https://index.docker.io/v1/
    namespace: orsontestdata

```

##### OS / ENVIRONMENT

```
Ansible Container, version 0.9.2rc0
Linux, ip-172-31-45-217, 4.9.32-15.41.amzn1.x86_64, #1 SMP Thu Jun 22 06:20:54 UTC 2017, x86_64
2.7.12 (default, Sep  1 2016, 22:14:00)
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] /home/ec2-user/venv_orson/bin/python2.7
{
  "ContainersPaused": 0,
  "Labels": null,
  "CgroupDriver": "cgroupfs",
  "ContainersRunning": 0,
  "ContainerdCommit": {
    "Expected": "4ab9917febca54791c5f071a9d1f404867857fcc",
    "ID": ""
  },
  "InitBinary": "docker-init",
  "NGoroutines": 23,
  "Swarm": {
    "Managers": 0,
    "ControlAvailable": false,
    "NodeID": "",
    "Cluster": {
      "Spec": {
        "TaskDefaults": {},
        "Orchestration": {},
        "EncryptionConfig": {
          "AutoLockManagers": false
        },
        "Raft": {
          "HeartbeatTick": 0,
          "ElectionTick": 0
        },
        "CAConfig": {},
        "Dispatcher": {}
      },
      "Version": {},
      "ID": "",
      "CreatedAt": "0001-01-01T00:00:00Z",
      "UpdatedAt": "0001-01-01T00:00:00Z"
    },
    "Nodes": 0,
    "Error": "",
    "RemoteManagers": null,
    "LocalNodeState": "inactive",
    "NodeAddr": ""
  },
  "LoggingDriver": "json-file",
  "OSType": "linux",
  "HttpProxy": "",
  "Runtimes": {
    "runc": {
      "path": "docker-runc"
    }
  },
  "DriverStatus": [
    [
      "Backing Filesystem",
      "extfs"
    ],
    [
      "Supports d_type",
      "true"
    ],
    [
      "Native Overlay Diff",
      "true"
    ]
  ],
  "OperatingSystem": "Amazon Linux AMI 2017.03",
  "Containers": 0,
  "HttpsProxy": "",
  "BridgeNfIp6tables": true,
  "MemTotal": 8373010432,
  "SecurityOptions": [
    "name=seccomp,profile=default"
  ],
  "Driver": "overlay2",
  "IndexServerAddress": "https://index.docker.io/v1/",
  "ClusterStore": "",
  "InitCommit": {
    "Expected": "949e6facb77383876aeff8a6944dde66b3089574",
    "ID": "N/A"
  },
  "Isolation": "",
  "SystemStatus": null,
  "OomKillDisable": true,
  "ClusterAdvertise": "",
  "SystemTime": "2017-07-06T18:53:16.708900316Z",
  "Name": "ip-172-31-45-217",
  "CPUSet": true,
  "RegistryConfig": {
    "InsecureRegistryCIDRs": [
      "127.0.0.0/8"
    ],
    "IndexConfigs": {
      "docker.io": {
        "Official": true,
        "Name": "docker.io",
        "Secure": true,
        "Mirrors": null
      }
    },
    "Mirrors": []
  },
  "DefaultRuntime": "runc",
  "ContainersStopped": 0,
  "NCPU": 2,
  "NFd": 14,
  "Architecture": "x86_64",
  "KernelMemory": true,
  "CpuCfsQuota": true,
  "Debug": false,
  "ID": "HVZ6:XODW:4RS4:MO4R:4SZH:XNY4:RENM:ZPTA:BCN7:TQNM:2IOU:TYGR",
  "IPv4Forwarding": true,
  "KernelVersion": "4.9.32-15.41.amzn1.x86_64",
  "BridgeNfIptables": true,
  "NoProxy": "",
  "LiveRestoreEnabled": false,
  "ServerVersion": "17.03.1-ce",
  "CpuCfsPeriod": true,
  "ExperimentalBuild": false,
  "MemoryLimit": true,
  "SwapLimit": true,
  "Plugins": {
    "Volume": [
      "local"
    ],
    "Network": [
      "bridge",
      "host",
      "macvlan",
      "null",
      "overlay"
    ],
    "Authorization": null
  },
  "Images": 12,
  "DockerRootDir": "/var/lib/docker",
  "NEventsListener": 0,
  "CPUShares": true,
  "RuncCommit": {
    "Expected": "54296cf40ad8143b62dbcaa1d90e520a2136ddfe",
    "ID": "N/A"
  }
}
{
  "KernelVersion": "4.9.32-15.41.amzn1.x86_64",
  "Arch": "amd64",
  "BuildTime": "2017-05-30T17:59:44.502465179+00:00",
  "ApiVersion": "1.27",
  "Version": "17.03.1-ce",
  "MinAPIVersion": "1.12",
  "GitCommit": "7392c3b/17.03.1-ce",
  "Os": "linux",
  "GoVersion": "go1.7.5"
}
```
##### SUMMARY
On machine A
ansible-container build ==> Check
ansible-container run ==> Check
ansible-container push ==> Check (private docker registry)
ansible-container deploy ==> Check (docker engine)

Now I want to deploy the images onto Machine B and start them running 
I have a yml script generated by deploy.
But what do I actually need to do?

##### STEPS TO REPRODUCE
build, run, push, deploy

##### EXPECTED RESULTS
The 2 services running on Machine B

##### ACTUAL RESULTS
Not sure what to do 

```

```
