### ISSUE TITLE
Run command fails when passing --var-file option with an existing vars file

### ISSUE THREAD

**Issue by geerlingguy** [ansible/ansible-container#643]
##### ISSUE TYPE

 - Bug Report

##### container.yml 

```
version: "2"
settings:
  conductor_base: debian:9

services:
  solr:
    from: "debian:9"
    ports:
      - "8983:8983"
    command: "{{ container_start_command }}"
    roles:
      - setup
      - geerlingguy.java
      - geerlingguy.solr
```

##### OS / ENVIRONMENT

See: https://gist.github.com/geerlingguy/98cb8a4b61baa285bafe813823eb2b23

##### SUMMARY

It seems that when I use the `run` command, I can't also pass a `--var_file`. I am defining my service's `command` as a variable in my `container.yml`, and trying to set the variable in a var file for each environment.

##### STEPS TO REPRODUCE

  1. Create a `vars-test.yml` file with a variable `container_start_command` defined in it.
  2. Use a `container.yml` file like the one above.
  3. Try running the `run` command after building the container(s) along with the `--var_file` option.

It says in the docs line that `[--var-file VAR_FILE]` is one of the options... and it works fine with the `build` option, but it seems not to be accepted by `run`.

##### EXPECTED RESULTS

The variables defined in `vars-test.yml` should be used by the `run` command allowing variables to be used in `container.yml`.

##### ACTUAL RESULTS

```
$ ansible-container --var_file ./vars-test.yml run
usage: ansible-container [-h] [--debug] [--devel] [--engine ENGINE_NAME]
                         [--project-path BASE_PATH]
                         [--project-name PROJECT_NAME] [--var-file VAR_FILE]
                         [--no-selinux]
                         {run,help,deploy,stop,destroy,restart,init,version,build,install,push,import}
                         ...
ansible-container: error: argument subcommand: invalid choice: './vars-test.yml' (choose from 'run', 'help', 'deploy', 'stop', 'destroy', 'restart', 'init', 'version', 'build', 'install', 'push', 'import')
```
