### ISSUE TITLE
Enable post deployment hook in K8s/OpenShift

### ISSUE THREAD

**Issue by chouseknecht** [ansible/ansible-container#648]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
The community is about to land a K8s connection plugin. See https://github.com/ansible/ansible/pull/26668.

Once it lands, we could add the ability to configure post-deployment roles. Examples might include: performing database migrations, creating users, injecting data files.

So perhaps in `container.yml` the following would be configured for a service:

```
version: '2'
services:
   django:
      ...
      openshift:
         post_deployment_roles:
         - role: django-migrate
         - role: create-admin-user
```

The `deploy` command would then add the following to the generated playbook:

```
- name: Post deployment steps
   hosts: django
   connection: kubernetes
   roles:
     - role: django-migrate
     - role: create-admin-user
```
