### ISSUE TITLE
Issue with building

### ISSUE THREAD

**Issue by cdrage** [ansible/ansible-container#66]
```
▶ cat container.yml 
version: "1"
services:
  web:
   image: nginx
   ports:
     - "80:80"
```

```
 - hosts: all
   gather_facts: false
   tasks:
     - raw: which python || apt-get update
     - raw: (which python && which aptitude) || apt-get install -y python python-apt aptitude
 - hosts: web
   tasks:
     - name: Upgrade APT
       apt: upgrade=yes
     - name: Install ca-certificates
       apt: name=ca-certificates state=latest
     - name: Install dumb-init
       apt: deb=https://github.com/Yelp/dumb-init/releases/download/v1.0.2/dumb-init_1.0.2_amd64.deb
     - name: Install Apache
       apt: name=apache2 state=latest
```

Error:
```
▶ ansible-container build
(Re)building the Ansible Container image.
Building Docker Engine context...
Starting Docker build of Ansible Container image...
Ansible Container image has ID sha256:f8be78751e9326d50a94cf7d9a2195655baa9d45a9844bb62f1eabcb4611fca1
Starting Docker Compose engine to build your images...
Attaching to ansible_ansible-container_1
Cleaning up Ansible Container builder...
Attaching to ansible_ansible-container_1, ansible_web_1
ansible-container_1  | 
ansible-container_1  | PLAY [all] *********************************************************************
ansible-container_1  | 
ansible-container_1  | TASK [raw] *********************************************************************
ansible-container_1  | Cannot connect to the Docker daemon. Is the docker daemon running on this host?
ansible-container_1  | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: CalledProcessError: Command '['/usr/bin/docker', 'version']' returned non-zero exit status 1
ansible-container_1  | fatal: [web]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
ansible-container_1  | 
ansible-container_1  | NO MORE HOSTS LEFT *************************************************************
ansible-container_1  |  [WARNING]: Could not create retry file 'main.retry'.         Unable to create
ansible-container_1  | local directories(): [Errno 2] No such file or directory: ''
ansible-container_1  | 
ansible-container_1  | PLAY RECAP *********************************************************************
ansible-container_1  | web                        : ok=0    changed=0    unreachable=0    failed=1   
ansible-container_1  | 
ansible_ansible-container_1 exited with code 1
Aborting on container exit...
Stopping ansible_web_1 ... done
Ansible playbook run failed.
Cleaning up Ansible Container builder...
```

Docker version:
```
~/test/ansible                                                                                                                                                                                                                                                
▶ docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64
```
