### ISSUE TITLE
Task that work in ansible do not work in ansible-container

### ISSUE THREAD

**Issue by basictheprogram** [ansible/ansible-container#679]
##### ISSUE TYPE
 - Bug Report

##### container.yml 
```
version: "2"
defaults:
  keep_deb_src: false
  keep_build_essentials: false
settings:
  conductor:
    base: ubuntu
    volumes: [/Users/tanner/projects/ansible.git/playbooks.git/roles:/etc/ansible/roles:ro]
  project_name: dev
services:
  apache2-servers:
    from: ubuntu
    roles:
      - { role: postfix-satellite }
registries: {}
```

##### OS / ENVIRONMENT
```
$ ansible-container --debug version
Ansible Container, version 0.9.2rc0
Darwin, alliance.local, 16.6.0, Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64, x86_64
2.7.10 (default, Feb  7 2017, 00:08:15)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] /Users/tanner/projects/ansible.git/bin/python
{
  "ContainersPaused": 0,
  "Labels": null,
  "CgroupDriver": "cgroupfs",
  "ContainersRunning": 1,
  "ContainerdCommit": {
    "Expected": "3addd840653146c90a254301d6c3a663c7fd6429",
    "ID": "3addd840653146c90a254301d6c3a663c7fd6429"
  },
  "InitBinary": "docker-init",
  "NGoroutines": 34,
  "Swarm": {
    "ControlAvailable": false,
    "NodeID": "",
    "Error": "",
    "RemoteManagers": null,
    "LocalNodeState": "inactive",
    "NodeAddr": ""
  },
  "LoggingDriver": "json-file",
  "OSType": "linux",
  "HttpProxy": "",
  "Runtimes": {
    "runc": {
      "path": "docker-runc"
    }
  },
  "DriverStatus": [
    [
      "Backing Filesystem",
      "extfs"
    ],
    [
      "Supports d_type",
      "true"
    ],
    [
      "Native Overlay Diff",
      "true"
    ]
  ],
  "OperatingSystem": "Alpine Linux v3.5",
  "Containers": 26,
  "HttpsProxy": "",
  "BridgeNfIp6tables": true,
  "MemTotal": 2095882240,
  "SecurityOptions": [
    "name=seccomp,profile=default"
  ],
  "Driver": "overlay2",
  "IndexServerAddress": "https://index.docker.io/v1/",
  "ClusterStore": "",
  "InitCommit": {
    "Expected": "949e6fa",
    "ID": "949e6fa"
  },
  "Isolation": "",
  "SystemStatus": null,
  "OomKillDisable": true,
  "ClusterAdvertise": "",
  "SystemTime": "2017-08-05T20:10:08.539058125Z",
  "Name": "moby",
  "CPUSet": true,
  "RegistryConfig": {
    "AllowNondistributableArtifactsCIDRs": [],
    "Mirrors": [],
    "IndexConfigs": {
      "docker.io": {
        "Official": true,
        "Name": "docker.io",
        "Secure": true,
        "Mirrors": []
      }
    },
    "AllowNondistributableArtifactsHostnames": [],
    "InsecureRegistryCIDRs": [
      "127.0.0.0/8"
    ]
  },
  "DefaultRuntime": "runc",
  "ContainersStopped": 25,
  "NCPU": 4,
  "NFd": 25,
  "Architecture": "x86_64",
  "KernelMemory": true,
  "CpuCfsQuota": true,
  "Debug": true,
  "ID": "SJPY:DOQH:RM2R:4YZ4:RA53:KJYW:G7JV:5YLB:NETC:W5GZ:TYA7:4T3K",
  "IPv4Forwarding": true,
  "KernelVersion": "4.9.38-moby",
  "BridgeNfIptables": true,
  "NoProxy": "",
  "LiveRestoreEnabled": false,
  "ServerVersion": "17.07.0-ce-rc1",
  "CpuCfsPeriod": true,
  "ExperimentalBuild": true,
  "MemoryLimit": true,
  "SwapLimit": true,
  "Plugins": {
    "Volume": [
      "local"
    ],
    "Network": [
      "bridge",
      "host",
      "ipvlan",
      "macvlan",
      "null",
      "overlay"
    ],
    "Authorization": null,
    "Log": [
      "awslogs",
      "fluentd",
      "gcplogs",
      "gelf",
      "journald",
      "json-file",
      "logentries",
      "splunk",
      "syslog"
    ]
  },
  "Images": 19,
  "DockerRootDir": "/var/lib/docker",
  "NEventsListener": 1,
  "CPUShares": true,
  "RuncCommit": {
    "Expected": "2d41c047c83e09a6d61d464906feb2a2f3c52aa4",
    "ID": "2d41c047c83e09a6d61d464906feb2a2f3c52aa4"
  }
}
{
  "KernelVersion": "4.9.38-moby",
  "Arch": "amd64",
  "BuildTime": "2017-07-26T05:25:01.392492215+00:00",
  "ApiVersion": "1.31",
  "Version": "17.07.0-ce-rc1",
  "MinAPIVersion": "1.12",
  "GitCommit": "8c4be39",
  "Os": "linux",
  "Experimental": true,
  "GoVersion": "go1.8.3"
}
```
##### SUMMARY
Task that function properly with Ansible, fail when executed with ansible-container

##### STEPS TO REPRODUCE

```yaml
- name: install postfix (apt)
  apt:
    name: "{{ item }}"
    state: "latest"
  with_items:
    - "postfix"
```

##### EXPECTED RESULTS
 * The postfix package would be installed. 
 * The python3-minimal package would not be installed

Looking at the [postfix](https://packages.ubuntu.com/xenial/postfix) package it only recommends the python3-minimal package.

Looking at the ansible [apt](http://docs.ansible.com/ansible/latest/apt_module.html) module; install_recommends comments says, "... By default, Ansible will use the same defaults as the operating system. Suggested packages are never installed."

##### ACTUAL RESULTS
```
"Setting up python3-minimal (3.5.1-3) ...", "Fatal Python error: Py_Initialize: Unable to get the locale encoding", "  File \"/_usr/lib/python2.7/encodings/__init__.py\", line 123", "    raise CodecRegistryError,\\", "                            ^", "SyntaxError: invalid syntax", "", "Current thread 0x00007fa729773700 (most recent call first):", "Aborted", "dpkg: error processing package python3-minimal (--configure):", " subprocess installed post-installation script returned error exit status 134", "Errors were encountered while processing:", " python3-minimal"]}
```

**Comment by basictheprogram** [comment]
```yaml
- name: install postfix (apt)
  apt:
    name: "{{ item }}"
    state: latest
    install_recommends: no
  with_items:
    - "postfix"
```

Adding **install_recommends: no** seems to work around this problem.
