### ISSUE TITLE
--with-volumes doesnt mount since 0.2.0

### ISSUE THREAD

**Issue by zerginator** [ansible/ansible-container#688]
Hi, 

great work with ansible-container. Im a big fan! but unfortunately Im stucked in version 0.2.0. Here is the reason why:

Running ansible container with:
ansible-container build --flatten --no-purge-last --with-volumes {{ jenkinsWorkspace }}/target/universal:/tmp/myapplication

##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### container.yml 
version: "2"

services:
     application:
        image: centos:7
        command: /etc/init.d/startApplication.sh

##### main.yml

  name: Installing application
  hosts: application
  remote_user: root
  roles:
      - artifact

##### OS / ENVIRONMENT
Docker Centos:7
Building on Redhat 7 

##### SUMMARY
problem appeared with version 0.3.0 and is also confirmed in 0.9.1
mapped volume didnt show up during build process inside the docker. when i was using the ansible module unarchive to unpack the file

##### STEPS TO REPRODUCE
ansible-container build --flatten --no-purge-last --with-volumes {{ jenkinsWorkspace }}/target/universal:/tmp/myapplication

copy a file in the mapped volume inside docker from /tmp to /opt

check if the volume is mapped inside the 
##### EXPECTED RESULTS
volume should show up in docker

##### ACTUAL RESULTS
volume doesn't show up

**Comment by chouseknecht** [comment]
@zerginator 

Thanks for using Ansible Container, and a big thanks for sharing your feedback!

Testing this in my local environment using the latest source. Not able to reproduce. 

Here's my container.yml:

```
version: "2"
settings:
  conductor:
    base: 'centos:7'
    save: true

services:
  web:
    from: 'centos:7'
    roles:
    - drop-file
    command:
    - /bin/sleep
    - 1d

registries: {}
```

Here's my role tasks:

```
---
- name: copy file
  copy:
     src: '/tmp/myspace/sample.txt'
     dest: '/sample.txt'

- name: Say hello
  debug: msg="Hello world!"
```

And, here's the build command:

```
ansible-container --debug build --with-volumes /Users/chouseknecht:/tmp/myspace
```

Seems to work. Here are the binds to the `conductor` container:

```
"HostConfig": {
   "Binds": [
                "tstvol_secrets:/run/secrets:rw",
                "/Users/chouseknecht/.docker/config.json:/Users/chouseknecht/.docker/config.json:rw",
                "/var/run/docker.sock:/var/run/docker.sock:rw",
                "/Users/chouseknecht:/tmp/myspace:rw",
                "/Users/chouseknecht/projects/ansible-container/container:/_ansible/container:rw",
                "/Users/chouseknecht/tstvol:/src:ro"
            ],
```

Totally possible that this was broken in the 9.1 release, so you might try running from source. 

Also, it's now possible to add your volumes to `container.yml` For example:

```
version: "2"
settings:

  conductor:
    base: 'centos:7'
    save: true
    volumes:
    - /Users/chouseknecht:/tmp/myspace:rw
```

Let me know if I missed anything. Hope this helps.
