### ISSUE TITLE
Facing IO Error while running Ansible Container build

### ISSUE THREAD

**Issue by Manigunner** [ansible/ansible-container#716]
Bug Report
 

##### container.yml 

```
```version: '2'
settings:
  conductor_base: centos:7
services:
  ansible.nginx-container:
    roles:
    - nginx_container
    ports:
    - '8085:8085'
    user: nginx
    command: ['/usr/bin/dumb-init', '/app/server/nginx/sbin/nginx', '-c', '/app/nflott/nginx/conf/nginx.conf']
  ansible.node-container:
    roles:
    - node_container
    ports:
    - '3000:3000'
    user: node
    command: ['/usr/bin/dumb-init', '/app/nflott/node/conf', 'app/nflott/node/temp', 'app/nflott/node/archive']
registries: {}


```

##### OS / ENVIRONMENT

CENTOS 7,ansible version 0.9
```
##### SUMMARY
Facing IO error while running the ansible container build.

##### STEPS TO REPRODUCE
<!---
I have writing code for creating container for nodejs. Written the container.yml and my main.yml is under

ansible-container/roles/node_container/tasks/main.yml
-->

<!--- Paste any example commands between quotes below -->
```
sudo ansible-container --debug build
```

<!--- You can also paste gist.github.com links for larger files -->

##### EXPECTED RESULTS
<!--- What did you expect to happen when running the steps above? -->

Container should be build successfully

##### ACTUAL RESULTS
ller_func=conductorcmd_build caller_line=691 role=nginx_container service=u'ansible.nginx-container'
2017-08-29T07:08:02.008837 Build complete.                [container.core] caller_file=/_ansible/container/core.py caller_func=conductorcmd_build caller_line=789 service=u'ansible.nginx-container'
2017-08-29T07:08:02.012138 Building service...            [container.core] caller_file=/_ansible/container/core.py caller_func=conductorcmd_build caller_line=656 project=ansible_container_dotcom service=u'ansible.node-container'
2017-08-29T07:08:02.018620 Base fingerprint hash = 1cba0d6925fb29528b3b517904064a07fe1d55ab9d29d703a2513828f2020309 [container.core] caller_file=/_ansible/container/core.py caller_func=conductorcmd_build caller_line=667 hash=1cba0d6925fb29528b3b517904064a07fe1d55ab9d29d703a2513828f2020309 service=u'ansible.node-container'
2017-08-29T07:08:02.033869 Could not find container for ansible.node-container [container.docker.engine] all_containers=[<Container: fd3f19c70e>, <Container: ec2650daf7>, <Container: 0b449db508>] caller_file=/_ansible/container/docker/engine.py caller_func=get_container_id_for_service caller_line=478 container=u'ansible_container_dotcom_ansible.node-container'
Traceback (most recent call last):
  File "/usr/bin/conductor", line 11, in <module>
    load_entry_point('ansible-container', 'console_scripts', 'conductor')()
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/cli.py", line 392, in conductor_commandline
    **params)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/core.py", line 678, in conductorcmd_build
    role_fingerprint = get_role_fingerprint(role)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/utils/__init__.py", line 254, in get_role_fingerprint
    hash_role(hash_obj, resolve_role_to_path(role_name))
  File "/_ansible/container/utils/__init__.py", line 238, in hash_role
    hash_dir(hash_obj, role_path)
  File "/_ansible/container/utils/__init__.py", line 233, in hash_dir
    hash_file(hash_obj, abs_file_path)
  File "/_ansible/container/utils/__init__.py", line 219, in hash_file
    with open(file_path, 'rb') as ifs:
IOError: [Errno 2] No such file or directory: u'/src/roles/node_container/tasks/.#main.yml'
2017-08-29T07:08:02.442240 Conductor terminated. Cleaning up. [container.docker.engine] caller_file=/app/ansible_container_source/ansible-container/container/docker/engine.py caller_func=await_conductor_command caller_line=409 command_rc=1 conductor_id=u'fd3f19c70e21c33f17e87cf38c20bf58cb3882a6786d3f71231de521b4f78362' save_container=False
2017-08-29T07:08:03.085711 Conductor exited with status 1 [container.cli] caller_file=/app/ansible_container_source/ansible-container/container/cli.py caller_func=__call__ caller_line=303
