### ISSUE TITLE
Question: Volume shared between containers

### ISSUE THREAD

**Issue by jas02** [ansible/ansible-container#738]
I am using ansible-container 0.9.2. I am trying to share named volume between two running containers. The named volume is called static-content and I have it defined in container.yml  as below. 

However the named volume for nginx service is always different than inside lemur service (empty). When I run manually command:

docker run --rm -ti -v static-content:/www ansible-container-lemur-nginx:20170924085225 bash

I can see correctly the content of named volume "static-content".

What am I doing wrong in the container.yml configuration? How to fix this?

Many thanks in advance

Lumir
##### ISSUE TYPE

 - Question
 ##### container.yml 

```
services:
  postgres:
    from: ubuntu:16.04
    user: postgres
    roles:
      - postgres
    expose:
      - 5432
    environment:
      POSTGRES_USER: "{{ POSTGRES_USER }}"
      POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"
      POSTGRES_DB: "{{ POSTGRES_DB }}"
    command: ['/usr/lib/postgresql/9.5/bin/postgres', '-D', '/var/lib/postgresql/9.5/main', '-c', 'config_file=/etc/postgresql/9.5/main/postgresql.conf']
  lemur:
    from: ubuntu:16.04
    user: lemur
    depends_on: ['postgres']
    roles:
      - lemur
    command: ['/usr/bin/start_lemur.sh']
    links:
      - postgres
      - postgres:postgresql
    ports:
      - '{{ LEMUR_PORT }}'
    volumes:
      - static-content:/www
  nginx:
    from: ubuntu:16.04
    user: root
    roles:
      - nginx
    ports:
      - 0.0.0.0:8000:80
    links:
      - lemur
    command: ['/usr/bin/start_nginx.sh']
    volumes_from:
      - lemur
    # Also tried
    #volumes:
    # - lemur
volumes:
  static-content:
    docker: {}
```

##### OS / ENVIRONMENT

```

```
##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```
