### ISSUE TITLE
Duplicate ports definition in Docker image - breaks OpenShift Service deployment

### ISSUE THREAD

**Issue by alesz** [ansible/ansible-container#742]
##### ISSUE TYPE

 - Bug Report

##### container.yml 

```
version: "2"
settings:
  conductor:
    base: centos:7
  project_name: XXXXXX
  k8s_auth:
    host: XXXXXX
    cert_file: /etc/docker/certs.d/docker-registry-default.apps.XXXXXX/cert.crt
    verify_ssl: 0
  k8s_namespace:
    name: XXXXXX
    description: XXXXXX
    display_name: XXXXXX
services:
  frontend:
    from: "centos:7"
    roles:
      - frontend
    ports:
      - 8000:8000
    command: ["/usr/sbin/nginx"]
    openshift:
      state: present
      service:
        force: false
      deployment:
        force: false
        replicas: 1
        security_context:
          run_as_user: root
        strategy:
          type: Rolling
#      routes:
#        - port: 8000
registries: {}
```

##### OS / ENVIRONMENT

```
Ansible Container, version 0.9.2
Linux, jenkins-worker.XXXXXX, 3.10.0-693.2.2.el7.x86_64, #1 SMP Sat Sep 9 03:55:24 EDT 2017, x86_64
3.6.2 (default, Jul 18 2017, 22:59:45) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] /usr/bin/python3.6
{
  "ID": "PCK7:QD5D:Z5MA:RLYV:NCIA:GH4I:QCRX:D3C6:ECUU:E4AL:QPAC:ZSN6",
  "Containers": 0,
  "ContainersRunning": 0,
  "ContainersPaused": 0,
  "ContainersStopped": 0,
  "Images": 35,
  "Driver": "overlay",
  "DriverStatus": [
    [
      "Backing Filesystem",
      "xfs"
    ],
    [
      "Supports d_type",
      "true"
    ]
  ],
  "SystemStatus": null,
  "Plugins": {
    "Volume": [
      "local"
    ],
    "Network": [
      "bridge",
      "host",
      "macvlan",
      "null",
      "overlay"
    ],
    "Authorization": null,
    "Log": [
      "awslogs",
      "fluentd",
      "gcplogs",
      "gelf",
      "journald",
      "json-file",
      "logentries",
      "splunk",
      "syslog"
    ]
  },
  "MemoryLimit": true,
  "SwapLimit": true,
  "KernelMemory": true,
  "CpuCfsPeriod": true,
  "CpuCfsQuota": true,
  "CPUShares": true,
  "CPUSet": true,
  "IPv4Forwarding": true,
  "BridgeNfIptables": true,
  "BridgeNfIp6tables": true,
  "Debug": false,
  "NFd": 19,
  "OomKillDisable": true,
  "NGoroutines": 30,
  "SystemTime": "2017-09-29T15:36:30.778531455+10:00",
  "LoggingDriver": "json-file",
  "CgroupDriver": "cgroupfs",
  "NEventsListener": 0,
  "KernelVersion": "3.10.0-693.2.2.el7.x86_64",
  "OperatingSystem": "Red Hat Enterprise Linux Server 7.4 (Maipo)",
  "OSType": "linux",
  "Architecture": "x86_64",
  "IndexServerAddress": "https://index.docker.io/v1/",
  "RegistryConfig": {
    "AllowNondistributableArtifactsCIDRs": [],
    "AllowNondistributableArtifactsHostnames": [],
    "InsecureRegistryCIDRs": [
      "127.0.0.0/8"
    ],
    "IndexConfigs": {
      "docker.io": {
        "Name": "docker.io",
        "Mirrors": [],
        "Secure": true,
        "Official": true
      }
    },
    "Mirrors": []
  },
  "NCPU": 2,
  "MemTotal": 3958079488,
  "GenericResources": null,
  "DockerRootDir": "/var/lib/docker",
  "HttpProxy": "",
  "HttpsProxy": "",
  "NoProxy": "",
  "Name": "jenkins-worker.XXXXXX",
  "Labels": null,
  "ExperimentalBuild": false,
  "ServerVersion": "17.09.0-ce",
  "ClusterStore": "",
  "ClusterAdvertise": "",
  "Runtimes": {
    "runc": {
      "path": "docker-runc"
    }
  },
  "DefaultRuntime": "runc",
  "Swarm": {
    "NodeID": "",
    "NodeAddr": "",
    "LocalNodeState": "inactive",
    "ControlAvailable": false,
    "Error": "",
    "RemoteManagers": null
  },
  "LiveRestoreEnabled": false,
  "Isolation": "",
  "InitBinary": "docker-init",
  "ContainerdCommit": {
    "ID": "06b9cb35161009dcb7123345749fef02f7cea8e0",
    "Expected": "06b9cb35161009dcb7123345749fef02f7cea8e0"
  },
  "RuncCommit": {
    "ID": "3f2f8b84a77f73d38244dd690525642a72156c64",
    "Expected": "3f2f8b84a77f73d38244dd690525642a72156c64"
  },
  "InitCommit": {
    "ID": "949e6fa",
    "Expected": "949e6fa"
  },
  "SecurityOptions": [
    "name=seccomp,profile=default"
  ]
}
{
  "Version": "17.09.0-ce",
  "ApiVersion": "1.32",
  "MinAPIVersion": "1.12",
  "GitCommit": "afdb6d4",
  "GoVersion": "go1.8.3",
  "Os": "linux",
  "Arch": "amd64",
  "KernelVersion": "3.10.0-693.2.2.el7.x86_64",
  "BuildTime": "2017-09-26T22:42:49.000000000+00:00"
}
```
##### SUMMARY

Image build and push to Docker registry is successful using `ansible-container build ... ` and `ansible-container push ... `  

Deploying image on OpenShift displays:
```
    This image will be deployed in Deployment Config XXXXXX-frontend.
    Ports 8000/TCP and 8000/TCP will be load balanced by Service XXXXXX-frontend.
    Other containers can access this service through the hostname XXXXXX-frontend.
```
After confirming deployment, following error is displayed:
```
Cannot create service "XXXXXX-frontend". Service "XXXXXX-frontend" is invalid: spec.ports[1].name: Duplicate value: "8000-tcp".
```

Atomic Registry (Docker registry web frontend) shows following info about the image:
```
Container

Command:      # /usr/sbin/nginx

Run as        root
Directory     /
Architecture  amd64

Ports         8000
              8000/tcp
```

##### STEPS TO REPRODUCE

* Define ports mapping to enable service reachability
* Build image
* Push image to Docker registry
* Inspect/deploy image to OpenShift

##### EXPECTED RESULTS

Single port definition in the Docker image instead of two.

##### ACTUAL RESULTS

See summary.
