### ISSUE TITLE
Invalid metadata \ image when having similar services

### ISSUE THREAD

**Issue by cutwater** [ansible/ansible-container#757]
##### ISSUE TYPE
 - Bug Report

##### container.yml 

```
version: '2'
settings:
  save_conductor_container: false
  vars_files:
  - develop.yml

services:
  django:
    from: centos:7
    working_dir: /galaxy
    links:
    - postgres
    - elastic
    - memcache
    - rabbit
    command: [/usr/local/bin/dumb-init, /setup/start-development.sh]
    user: django
    ports:
    - 8000:8000
    environment:
    - C_FORCE_ROOT=1
    dev_overrides:
      volumes:
      - ${PWD}:/galaxy:z
    roles:
    - django-role

  celery:
    from: centos:7
    working_dir: /galaxy
    links:
    - rabbit
    command: [/usr/local/bin/dumb-init, /venv/bin/python, /galaxy/manage.py, celeryd,
      -B, --autoreload, -Q, 'celery,import_tasks,login_tasks']
    environment:
    - C_FORCE_ROOT=1
    user: django
    dev_overrides:
      volumes:
      - ${PWD}:/galaxy:z
    roles:
    - django-role

  postgres:
    from: postgres:9.5.4
    environment:
    - POSTGRES_PASSWORD={{ galaxy_postgres_password }}
    - POSTGRES_USER={{ galaxy_postgres_user }}
    - POSTGRES_DB={{ galaxy_postgres_db }}

  elastic:
    from: elasticsearch:2.4.1

  memcache:
    from: memcached:latest

  rabbit:
    from: rabbitmq
    environment:
    - RABBITMQ_DEFAULT_USER={{ galaxy_rabbitmq_user }}
    - RABBITMQ_DEFAULT_PASS={{ galaxy_rabbitmq_pass }}
    - RABBITMQ_DEFAULT_VHOST={{ galaxy_rabbitmq_vhost }}

  gulp:
    from: centos:7
    roles:
    - gulp-role
    command: [/bin/true]
    working_dir: /galaxy
    volumes:
    - ${PWD}:/galaxy:z
    entrypoint: /usr/bin/entrypoint.sh
    user: gulp
    dev_overrides:
      command: [/usr/local/bin/dumb-init, /usr/bin/gulp]

registries: {}
```

##### OS / ENVIRONMENT

```
Ansible Container, version 0.9.3rc0
Linux, enterprise, 4.13.4-1-ARCH, #1 SMP PREEMPT Thu Sep 28 08:39:52 CEST 2017, x86_64
2.7.13 (default, Jun  2 2017, 13:44:55) 
[GCC 7.1.1 20170516] /home/cutwater/.pyenv/versions/2.7.13/envs/galaxy/bin/python2.7
{
  "ContainersPaused": 0, 
  "Labels": null, 
  "CgroupDriver": "cgroupfs", 
  "ContainersRunning": 5, 
  "ContainerdCommit": {
    "Expected": "06b9cb35161009dcb7123345749fef02f7cea8e0", 
    "ID": "06b9cb35161009dcb7123345749fef02f7cea8e0"
  }, 
  "InitBinary": "docker-init", 
  "NGoroutines": 56, 
  "Swarm": {
    "ControlAvailable": false, 
    "NodeID": "", 
    "Error": "", 
    "RemoteManagers": null, 
    "LocalNodeState": "inactive", 
    "NodeAddr": ""
  }, 
  "LoggingDriver": "json-file", 
  "OSType": "linux", 
  "HttpProxy": "", 
  "Runtimes": {
    "runc": {
      "path": "docker-runc"
    }
  }, 
  "DriverStatus": [
    [
      "Backing Filesystem", 
      "extfs"
    ], 
    [
      "Supports d_type", 
      "true"
    ], 
    [
      "Native Overlay Diff", 
      "true"
    ]
  ], 
  "OperatingSystem": "Arch Linux", 
  "Containers": 8, 
  "HttpsProxy": "", 
  "BridgeNfIp6tables": true, 
  "MemTotal": 16765825024, 
  "SecurityOptions": [
    "name=seccomp,profile=default"
  ], 
  "Driver": "overlay2", 
  "IndexServerAddress": "https://index.docker.io/v1/", 
  "ClusterStore": "", 
  "InitCommit": {
    "Expected": "949e6fa", 
    "ID": "949e6fa"
  }, 
  "GenericResources": null, 
  "Isolation": "", 
  "SystemStatus": null, 
  "OomKillDisable": true, 
  "ClusterAdvertise": "", 
  "SystemTime": "2017-10-09T16:29:09.883843761+02:00", 
  "Name": "enterprise", 
  "CPUSet": true, 
  "RegistryConfig": {
    "AllowNondistributableArtifactsCIDRs": [], 
    "Mirrors": [], 
    "IndexConfigs": {
      "docker.io": {
        "Official": true, 
        "Name": "docker.io", 
        "Secure": true, 
        "Mirrors": []
      }
    }, 
    "AllowNondistributableArtifactsHostnames": [], 
    "InsecureRegistryCIDRs": [
      "127.0.0.0/8"
    ]
  }, 
  "DefaultRuntime": "runc", 
  "ContainersStopped": 3, 
  "NCPU": 8, 
  "NFd": 58, 
  "Architecture": "x86_64", 
  "KernelMemory": true, 
  "CpuCfsQuota": true, 
  "Debug": false, 
  "ID": "BXRO:7ZVJ:QL2Q:WP5F:WB2T:5VYX:XRWX:5YPW:2HAL:2WPD:KVGF:LDMY", 
  "IPv4Forwarding": true, 
  "KernelVersion": "4.13.4-1-ARCH", 
  "BridgeNfIptables": true, 
  "NoProxy": "", 
  "LiveRestoreEnabled": false, 
  "ServerVersion": "17.09.0-ce", 
  "CpuCfsPeriod": true, 
  "ExperimentalBuild": false, 
  "MemoryLimit": true, 
  "SwapLimit": true, 
  "Plugins": {
    "Volume": [
      "local"
    ], 
    "Network": [
      "bridge", 
      "host", 
      "macvlan", 
      "null", 
      "overlay"
    ], 
    "Authorization": null, 
    "Log": [
      "awslogs", 
      "fluentd", 
      "gcplogs", 
      "gelf", 
      "journald", 
      "json-file", 
      "logentries", 
      "splunk", 
      "syslog"
    ]
  }, 
  "Images": 11, 
  "DockerRootDir": "/mnt/data/var/docker", 
  "NEventsListener": 0, 
  "CPUShares": true, 
  "RuncCommit": {
    "Expected": "3f2f8b84a77f73d38244dd690525642a72156c64", 
    "ID": "3f2f8b84a77f73d38244dd690525642a72156c64"
  }
}
{
  "KernelVersion": "4.13.4-1-ARCH", 
  "Arch": "amd64", 
  "BuildTime": "2017-10-05T09:59:07.000000000+00:00", 
  "ApiVersion": "1.32", 
  "Version": "17.09.0-ce", 
  "MinAPIVersion": "1.12", 
  "GitCommit": "afdb6d44a8", 
  "Os": "linux", 
  "GoVersion": "go1.9"
}

```
##### SUMMARY

When having two services based on a single image ("django" and "celery" in the example above) and with a common role, ansible-container builds a single container with common metadata (e.g. exposed ports).

##### STEPS TO REPRODUCE

1. Create compose.yml that has two services based on common image (e.g. `centos:7`). First should have ports mapping, while second shoundn't.
```
django:
    from: centos:7
    ports:
    - 8000:8000
    roles:
    - django-role    
    ...

celery:
    from: centos:7
    roles:
    - django-role    
    ...
```

2. Build images `ansible-container build`.
3. Check images built `docker images`.
4. Check exposed ports `docker inspect <image-name> |grep -A 1 ExposedPorts`

##### EXPECTED RESULTS

Images are created for each service with appropriate metadata (e.g. exposed ports).

##### ACTUAL RESULTS

A single image is created, referenced by tags (`galaxy-celery:latest`, `galaxy-django:latest` from the example below).

```
% docker images
REPOSITORY                             TAG                 IMAGE ID            CREATED             SIZE
galaxy-celery                          20171005164102      61a253cfc962        About an hour ago   964MB
galaxy-celery                          latest              61a253cfc962        About an hour ago   964MB
galaxy-django                          latest              61a253cfc962        About an hour ago   964MB
```
