### ISSUE TITLE
No error when trying to build nonexistent service

### ISSUE THREAD

**Issue by cutwater** [ansible/ansible-container#763]
##### ISSUE TYPE
 - Bug Report

##### container.yml 
```
version: '2'

services:
    foo:
        from: centos:7
        command: [/bin/bash, -c, 'echo FOO']

    bar:
        from: centos:7
        command: [/bin/bash, -c, 'echo BAR']
```

##### SUMMARY

When trying to build nonexistent container, `ansible-container build --services nonexist` command finishes with message `All images successfully built.`

##### STEPS TO REPRODUCE
1. Run `ansible-container build --services nonexist`, where `nonexist` is a service name that is not in the `container.yml` file.
2. Check output.

##### EXPECTED RESULTS

Error or warning message should be printed

##### ACTUAL RESULTS

Command performs no build at all and successfully finishes:

```
$ ansible-container build --services nonexist
Building Docker Engine context...
Starting Docker build of Ansible Container Conductor image (please be patient)...
Parsing conductor CLI args.
Docker™ daemon integration engine loaded. Build starting.       project=test
All images successfully built.
Conductor terminated. Cleaning up.      command_rc=0 conductor_id=a6effd749922f0320f70173659915c9fe63a873e43cd39a6b654f82b8880d34a save_container=False

$ echo $?
0
```
