### ISSUE TITLE
Permission issue on gulp install during ansible-container run

### ISSUE THREAD

**Issue by mikecali** [ansible/ansible-container#768]
##### ISSUE TYPE

 - Bug Report

##### container.yml 

```
cat container.yml 
version: '2'

settings:

  conductor:
    base: 'centos:7'
    volumes:
    - temp-space:/tmp   # Used to copy static content between containers

  k8s_namespace:
    name: demo
    display_name: Ansible Container Demo 
    description: Django framework demo 

defaults:
  POSTGRES_USER: django
  POSTGRES_PASSWORD: sesame
  POSTGRES_DB: django
  DJANGO_ROOT: /django
  DJANGO_USER: django
  DJANGO_PORT: 8080
  DJANGO_VENV: /venv
  NODE_USER: node
  NODE_HOME: /node
  NODE_ROOT: ''
  GULP_DEV_PORT: 8080

services:
  django:
    from: 'centos:7'
    roles:
    - role: django-gunicorn
    environment:
      DATABASE_URL: 'pgsql://{{ POSTGRES_USER }}:{{ POSTGRES_PASSWORD }}@postgresql:5432/{{ POSTGRES_DB }}'
      DJANGO_ROOT: '{{ DJANGO_ROOT }}'
      DJANGO_VENV: '{{ DJANGO_VENV }}'
    expose:
    - '{{ DJANGO_PORT }}'
    working_dir: '{{ DJANGO_ROOT }}'
    links:
    - postgresql
    user: '{{ DJANGO_USER }}'
    command: ['/usr/bin/dumb-init', '{{ DJANGO_VENV }}/bin/gunicorn', -w, '2', -b, '0.0.0.0:{{ DJANGO_PORT }}', 'project.wsgi:application']
    entrypoint: [/usr/bin/entrypoint.sh]
    dev_overrides:
      volumes:
      - '$PWD:{{ DJANGO_ROOT }}'
      command: [/usr/bin/dumb-init, '{{ DJANGO_VENV }}/bin/python', manage.py, runserver, '0.0.0.0:{{ DJANGO_PORT }}']
      depends_on:
      - postgresql

  gulp:
    from: 'centos:7'
    roles:
    - role: gulp-static 
    working_dir: '{{ NODE_HOME }}'
    command: ['/bin/false']
    environment:
      NODE_HOME: '{{ NODE_HOME }}'
    dev_overrides:
      entrypoint: [/entrypoint.sh]
      command: [/usr/bin/dumb-init, /usr/local/bin/gulp]
      ports:
      - '8080:{{ GULP_DEV_PORT }}'
      - 3001:3001
      links:
      - django
      volumes:
      - '$PWD:{{ NODE_HOME }}'
    openshift:
      state: absent

  nginx:
    from: 'centos:7'
    roles:
    - role: ansible.nginx-container
      ASSET_PATHS:
      - /tmp/dist
      PROXY: yes
      PROXY_PASS: 'http://django:8080'
      PROXY_LOCATION: "~* /(admin|api)"
    ports:
    - '{{ DJANGO_PORT }}:8000'
    links:
    - django
    dev_overrides:
      ports: []
      command: /bin/false

  postgresql:
    # Uses a pre-built postgresql image from Docker Hub 
    from: ansible/postgresql:latest
    environment:
    - 'POSTGRES_DB={{ POSTGRES_DB }}'
    - 'POSTGRES_USER={{ POSTGRES_USER }}'
    - 'POSTGRES_PASS={{ POSTGRES_PASSWORD }}'
    - 'PGDATA=/var/lib/pgsql/data/userdata'
    volumes:
    - postgres-data:/var/lib/pgsql/data
    expose:
    - 5432

volumes:
  postgres-data:
    docker: {}
    openshift:
      access_modes:
      - ReadWriteMany
      requested_storage: 3Gi 

  temp-space: 
    docker: {}
    openshift:
      state: absent

registries:
   local_openshift:
     url: https://local.openshift     # The push-to URL, created by chouseknecht.minishift-up role
     namespace: demo
     pull_from_url: 172.30.1.1:5000   # The pull-from URL from within minishift

```

##### OS / ENVIRONMENT

```
$ ansible-container --debug version
Ansible Container, version 0.9.3rc0
Linux, mcalizo.remote.csb, 3.10.0-693.2.2.el7.x86_64, #1 SMP Sat Sep 9 03:55:24 EDT 2017, x86_64
2.7.5 (default, Aug  2 2016, 04:20:16) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] /home/mcalizo/MC-Demo/images/ansible-container-venv-demo/venv/bin/python2
{
  "ContainersPaused": 0, 
  "Labels": null, 
  "DefaultRuntime": "docker-runc", 
  "CgroupDriver": "systemd", 
  "ClusterAdvertise": "", 
  "ContainersRunning": 0, 
  "NGoroutines": 29, 
  "Swarm": {
    "Managers": 0, 
    "ControlAvailable": false, 
    "NodeID": "", 
    "Cluster": {
      "Spec": {
        "Raft": {}, 
        "CAConfig": {}, 
        "Dispatcher": {}, 
        "Orchestration": {}, 
        "TaskDefaults": {}
      }, 
      "Version": {}, 
      "ID": "", 
      "CreatedAt": "0001-01-01T00:00:00Z", 
      "UpdatedAt": "0001-01-01T00:00:00Z"
    }, 
    "Nodes": 0, 
    "Error": "", 
    "RemoteManagers": null, 
    "LocalNodeState": "inactive", 
    "NodeAddr": ""
  }, 
  "LoggingDriver": "journald", 
  "OSType": "linux", 
  "HttpProxy": "", 
  "Runtimes": {
    "runc": {
      "path": "docker-runc"
    }, 
    "docker-runc": {
      "path": "/usr/libexec/docker/docker-runc-current"
    }
  }, 
  "DriverStatus": [
    [
      "Pool Name", 
      "RHEL7CSB-docker--pool"
    ], 
    [
      "Pool Blocksize", 
      "524.3 kB"
    ], 
    [
      "Base Device Size", 
      "10.74 GB"
    ], 
    [
      "Backing Filesystem", 
      "xfs"
    ], 
    [
      "Data file", 
      ""
    ], 
    [
      "Metadata file", 
      ""
    ], 
    [
      "Data Space Used", 
      "4.356 GB"
    ], 
    [
      "Data Space Total", 
      "41.35 GB"
    ], 
    [
      "Data Space Available", 
      "36.99 GB"
    ], 
    [
      "Metadata Space Used", 
      "913.4 kB"
    ], 
    [
      "Metadata Space Total", 
      "255.9 MB"
    ], 
    [
      "Metadata Space Available", 
      "254.9 MB"
    ], 
    [
      "Thin Pool Minimum Free Space", 
      "4.135 GB"
    ], 
    [
      "Udev Sync Supported", 
      "true"
    ], 
    [
      "Deferred Removal Enabled", 
      "true"
    ], 
    [
      "Deferred Deletion Enabled", 
      "false"
    ], 
    [
      "Deferred Deleted Device Count", 
      "0"
    ], 
    [
      "Library Version", 
      "1.02.135-RHEL7 (2016-11-16)"
    ]
  ], 
  "OperatingSystem": "Red Hat Enterprise Linux Workstation 7.3 (Maipo)", 
  "Containers": 7, 
  "HttpsProxy": "", 
  "BridgeNfIp6tables": false, 
  "MemTotal": 16293257216, 
  "Driver": "devicemapper", 
  "IndexServerAddress": "https://registry.access.redhat.com/v1/", 
  "ClusterStore": "", 
  "ExecutionDriver": "", 
  "Registries": [
    {
      "Name": "registry.access.redhat.com", 
      "Secure": true
    }, 
    {
      "Name": "docker.io", 
      "Secure": true
    }
  ], 
  "SystemStatus": null, 
  "OomKillDisable": true, 
  "PkgVersion": "docker-1.12.6-32.git88a4867.el7.x86_64", 
  "SystemTime": "2017-10-14T07:34:17.542842105+13:00", 
  "Name": "mcalizo.remote.csb", 
  "CPUSet": true, 
  "RegistryConfig": {
    "InsecureRegistryCIDRs": [
      "172.30.0.0/16", 
      "127.0.0.0/8"
    ], 
    "IndexConfigs": {
      "registry.access.redhat.com": {
        "Official": false, 
        "Name": "registry.access.redhat.com", 
        "Secure": true, 
        "Mirrors": []
      }, 
      "docker.io": {
        "Official": true, 
        "Name": "docker.io", 
        "Secure": true, 
        "Mirrors": null
      }
    }, 
    "Mirrors": null
  }, 
  "SecurityOptions": [
    "seccomp", 
    "selinux"
  ], 
  "ContainersStopped": 7, 
  "NCPU": 4, 
  "NFd": 20, 
  "Architecture": "x86_64", 
  "KernelMemory": true, 
  "CpuCfsQuota": true, 
  "Debug": false, 
  "IndexServerName": "registry.access.redhat.com", 
  "ID": "IUXW:D25C:FL4G:R3XW:25FS:WF6D:JP55:A5BP:XJNH:N364:DD4V:C65Y", 
  "IPv4Forwarding": true, 
  "KernelVersion": "3.10.0-693.2.2.el7.x86_64", 
  "BridgeNfIptables": false, 
  "NoProxy": "", 
  "LiveRestoreEnabled": false, 
  "ServerVersion": "1.12.6", 
  "CpuCfsPeriod": true, 
  "ExperimentalBuild": false, 
  "MemoryLimit": true, 
  "SwapLimit": true, 
  "Plugins": {
    "Volume": [
      "local"
    ], 
    "Network": [
      "null", 
      "overlay", 
      "bridge", 
      "host"
    ], 
    "Authorization": [
      "rhel-push-plugin"
    ]
  }, 
  "Images": 16, 
  "DockerRootDir": "/var/lib/docker", 
  "NEventsListener": 0, 
  "CPUShares": true
}
{
  "KernelVersion": "3.10.0-693.2.2.el7.x86_64", 
  "PkgVersion": "docker-1.12.6-32.git88a4867.el7.x86_64", 
  "Os": "linux", 
  "BuildTime": "2017-06-19T17:26:57.533975581-04:00", 
  "ApiVersion": "1.24", 
  "Version": "1.12.6", 
  "GitCommit": "88a4867/1.12.6", 
  "Arch": "amd64", 
  "GoVersion": "go1.7.6"
}

```
##### SUMMARY

ansible-container run complete but gulp install did not work with error shown below.

##### STEPS TO REPRODUCE

1. ansible-container init ansible.django-gulp-nginx
2.  ansible-container build
3. ansible-container run
4. docker logs -f ansiblecontainer_gulp_1 - I found the issue.

The script that is being called is " roles/gulp-static/templates/entrypoint.sh.j2"

```
$docker logs -f ansiblecontainer_gulp_1
+ '[' -d /tmp/django ']'
+ mkdir -p /node/dist
+ cp -R /tmp/django/admin /node/dist/
cp: cannot create directory '/node/dist/admin': Permission denied
+ cd /node
+ npm install
Error: EACCES: permission denied, scandir '/node'
TypeError: Cannot read property 'get' of undefined
    at errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:213:17)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:83:20
    at cb (/usr/local/lib/node_modules/npm/lib/npm.js:215:22)
    at /usr/local/lib/node_modules/npm/lib/npm.js:253:24
    at /usr/local/lib/node_modules/npm/lib/config/core.js:81:7
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/npm/lib/config/core.js:80:13
    at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at /usr/local/lib/node_modules/npm/lib/config/core.js:110:20
    at /usr/local/lib/node_modules/npm/lib/config/load-prefix.js:48:7
/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:213
  if (npm.config.get('json')) {
                ^
TypeError: Cannot read property 'get' of undefined
    at process.errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:213:17)
    at emitOne (events.js:115:13)
    at process.emit (events.js:210:7)
    at process._fatalException (bootstrap_node.js:373:26)
+ gulp build
[04:32:38] Local gulp not found in /node
[04:32:38] Try running: npm install gulp
+ su - node -c 'bower install'
/usr/local/lib/node_modules/bower/lib/node_modules/mkdirp/index.js:89
                    throw err0;
                    ^
Error: EACCES: permission denied, mkdir '/node/.config'
    at Object.fs.mkdirSync (fs.js:892:18)
    at sync (/usr/local/lib/node_modules/bower/lib/node_modules/mkdirp/index.js:70:13)
    at Function.sync (/usr/local/lib/node_modules/bower/lib/node_modules/mkdirp/index.js:76:24)
    at Configstore.get (/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:39:13)
    at Configstore (/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:28:44)
    at readCachedConfig (/usr/local/lib/node_modules/bower/lib/config.js:19:23)
    at defaultConfig (/usr/local/lib/node_modules/bower/lib/config.js:11:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/bower/lib/index.js:16:32)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
+ /usr/bin/dumb-init /usr/local/bin/gulp

```

##### EXPECTED RESULTS

I should see the Hello World page as per explained on https://ansible.github.io/ansible-container-demo/

##### ACTUAL RESULTS

]$ ansible-container build --no-container-cache
Building Docker Engine context...	
Starting Docker build of Ansible Container Conductor image (please be patient)...	
Parsing conductor CLI args.
Docker™ daemon integration engine loaded. Build starting.	project=ansible-container
Building service...	project=ansible-container service=django
[DEPRECATION WARNING]: with_ type loops are being phased out, use the 'loop'
keyword instead. This feature will be removed in version 2.9. Deprecation
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
PLAY [django] ******************************************************************
TASK [Gathering Facts] *********************************************************
ok: [django]
TASK [django-gunicorn : Install dumb init] *************************************
changed: [django]
TASK [django-gunicorn : Install epel] ******************************************
changed: [django]
TASK [django-gunicorn : Install python deps] ***********************************
changed: [django] => (item=[u'postgresql-devel', u'python-devel', u'gcc', u'python-virtualenv', u'nc', u'rsync'])
TASK [django-gunicorn : Make Django user] **************************************
changed: [django]
TASK [django-gunicorn : Create /django] ****************************************
changed: [django]
TASK [django-gunicorn : Make virtualenv dir] ***********************************
changed: [django]
TASK [django-gunicorn : Setup virtualenv] **************************************
changed: [django]
TASK [django-gunicorn : Copy core source items] ********************************
changed: [django] => (item=manage.py)
changed: [django] => (item=package.json)
changed: [django] => (item=project)
changed: [django] => (item=requirements.txt)
changed: [django] => (item=requirements.yml)
TASK [django-gunicorn : Install requirements] **********************************
changed: [django]
TASK [django-gunicorn : Remove staticfiles dir] ********************************
ok: [django]
TASK [django-gunicorn : Make staticfiles dir] **********************************
changed: [django]
TASK [django-gunicorn : Collect staticfiles] ***********************************
changed: [django]
TASK [django-gunicorn : Copy static assets to conductor] ***********************
changed: [django]
TASK [django-gunicorn : Copy entrypoint] ***************************************
changed: [django] => (item=entrypoint.sh)
changed: [django] => (item=wait_on_postgres.py)
changed: [django] => (item=manage_django.sh)
PLAY RECAP *********************************************************************
django                     : ok=15   changed=13   unreachable=0    failed=0
Applied role to service	role=ordereddict([('role', 'django-gunicorn')]) service=django
Committed layer as image	image=sha256:76b6f5ef6d3d0fa37ed8a45013de67870f3150462e15f44e3888fc0bfdafa78a service=django
Build complete.	service=django
Building service...	project=ansible-container service=gulp
[DEPRECATION WARNING]: with_ type loops are being phased out, use the 'loop'
keyword instead. This feature will be removed in version 2.9. Deprecation
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
PLAY [gulp] ********************************************************************
TASK [Gathering Facts] *********************************************************
ok: [gulp]
TASK [gulp-static : Install dumb init] *****************************************
changed: [gulp]
TASK [gulp-static : Make node user] ********************************************
changed: [gulp]
TASK [gulp-static : Make node home] ********************************************
changed: [gulp]
TASK [gulp-static : Create dist directory] *************************************
changed: [gulp]
TASK [gulp-static : Install nodejs] ********************************************
changed: [gulp] => (item=[u'https://rpm.nodesource.com/pub_5.x/el/7/x86_64/nodejs-5.9.1-1nodesource.el7.centos.x86_64.rpm', u'git', u'which'])
TASK [gulp-static : Create /tmp/django] ****************************************
changed: [gulp]
TASK [gulp-static : Copy django static files from conductor] *******************
changed: [gulp]
TASK [gulp-static : Clean npm cache] *******************************************
changed: [gulp]
TASK [gulp-static : Install the node helper] ***********************************
changed: [gulp]
TASK [gulp-static : Install the latest node] ***********************************
changed: [gulp]
TASK [gulp-static : Copy frontend source files] ********************************
changed: [gulp] => (item=bower.json)
changed: [gulp] => (item=package.json)
changed: [gulp] => (item=gulpfile.js)
changed: [gulp] => (item=.bowerrc)
changed: [gulp] => (item=src)
TASK [gulp-static : Install node packages] *************************************
changed: [gulp]
TASK [gulp-static : Install gulp] **********************************************
changed: [gulp]
TASK [gulp-static : Install bower] *********************************************
changed: [gulp]
TASK [gulp-static : Template entrypoint script] ********************************
changed: [gulp]
TASK [gulp-static : Build static assets] ***************************************
changed: [gulp]
TASK [gulp-static : Install bower packages] ************************************
changed: [gulp]
TASK [gulp-static : Copy django assets] ****************************************
changed: [gulp]
TASK [gulp-static : Copy static assets to conductor] ***************************
changed: [gulp]
PLAY RECAP *********************************************************************
gulp                       : ok=20   changed=19   unreachable=0    failed=0
Applied role to service	role=ordereddict([('role', 'gulp-static')]) service=gulp
Committed layer as image	image=sha256:ffd6850d6edb0f0e30edfb94ff4456b56c561510ec97624b8fcdac3a0de78a32 service=gulp
Build complete.	service=gulp
Building service...	project=ansible-container service=nginx
[DEPRECATION WARNING]: with_ type loops are being phased out, use the 'loop'
keyword instead. This feature will be removed in version 2.9. Deprecation
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
PLAY [nginx] *******************************************************************
TASK [Gathering Facts] *********************************************************
ok: [nginx]
TASK [ansible.nginx-container : Install epel-release] **************************
changed: [nginx]
TASK [ansible.nginx-container : Install nginx] *********************************
changed: [nginx] => (item=[u'nginx', u'rsync'])
TASK [ansible.nginx-container : Install dumb init] *****************************
changed: [nginx]
TASK [ansible.nginx-container : Update nginx user] *****************************
changed: [nginx]
TASK [ansible.nginx-container : Put nginx config] ******************************
changed: [nginx]
TASK [ansible.nginx-container : Create directories, if they don't exist] *******
changed: [nginx] => (item=/static)
changed: [nginx] => (item=/run/nginx)
changed: [nginx] => (item=/var/log/nginx)
changed: [nginx] => (item=/var/lib/nginx)
TASK [ansible.nginx-container : Clear log files] *******************************
ok: [nginx] => (item=access.log)
ok: [nginx] => (item=error.log)
TASK [ansible.nginx-container : Make directories owned by nginx:root] **********
changed: [nginx] => (item=/static)
changed: [nginx] => (item=/run/nginx)
changed: [nginx] => (item=/var/log/nginx)
changed: [nginx] => (item=/var/lib/nginx)
 [WARNING]: Consider using file module with owner rather than running chown
TASK [ansible.nginx-container : Make directories writable by root group] *******
changed: [nginx] => (item=/var)
changed: [nginx] => (item=/var/log)
changed: [nginx] => (item=/var/lib)
 [WARNING]: Consider using file module with mode rather than running chmod
TASK [ansible.nginx-container : Make directories writable to nginx:root] *******
changed: [nginx] => (item=/static)
changed: [nginx] => (item=/run/nginx)
changed: [nginx] => (item=/var/log/nginx)
changed: [nginx] => (item=/var/lib/nginx)
TASK [ansible.nginx-container : Link log files to stdout] **********************
changed: [nginx] => (item=access.log)
changed: [nginx] => (item=error.log)
 [WARNING]: Consider using file module with state=link rather than running ln
TASK [ansible.nginx-container : Remove /var/cache/nginx, if it exists] *********
ok: [nginx]
TASK [ansible.nginx-container : Create /var/cache/nginx] ***********************
changed: [nginx]
TASK [ansible.nginx-container : Create tmp directories with correct permissions] ***
changed: [nginx] => (item=tmp)
changed: [nginx] => (item=tmp/client_body)
changed: [nginx] => (item=tmp/fastcgi)
changed: [nginx] => (item=tmp/proxy)
changed: [nginx] => (item=tmp/scgi)
changed: [nginx] => (item=tmp/uwsgi)
TASK [ansible.nginx-container : Put static assets] *****************************
changed: [nginx] => (item=/tmp/dist)
TASK [ansible.nginx-container : Itemize default nginx static assets] ***********
ok: [nginx]
TASK [ansible.nginx-container : Copy default content when no static assets] ****
skipping: [nginx] => (item={u'uid': 0, u'woth': False, u'mtime': 1505726335.0, u'inode': 6297608, u'isgid': False, u'size': 3650, u'roth': True, u'isuid': False, u'isreg': True, u'gid': 0, u'ischr': False, u'wusr': True, u'xoth': False, u'rusr': True, u'nlink': 1, u'issock': False, u'rgrp': True, u'path': u'/usr/share/nginx/html/404.html', u'xusr': False, u'atime': 1505726335.0, u'isdir': False, u'ctime': 1507921431.406413, u'wgrp': False, u'xgrp': False, u'dev': 64776, u'isblk': False, u'isfifo': False, u'mode': u'0644', u'islnk': False})
skipping: [nginx] => (item={u'uid': 0, u'woth': False, u'mtime': 1505726335.0, u'inode': 6297609, u'isgid': False, u'size': 3693, u'roth': True, u'isuid': False, u'isreg': True, u'gid': 0, u'ischr': False, u'wusr': True, u'xoth': False, u'rusr': True, u'nlink': 1, u'issock': False, u'rgrp': True, u'path': u'/usr/share/nginx/html/50x.html', u'xusr': False, u'atime': 1505726335.0, u'isdir': False, u'ctime': 1507921431.406413, u'wgrp': False, u'xgrp': False, u'dev': 64776, u'isblk': False, u'isfifo': False, u'mode': u'0644', u'islnk': False})
skipping: [nginx] => (item={u'uid': 0, u'woth': False, u'mtime': 1505726335.0, u'inode': 6297610, u'isgid': False, u'size': 3700, u'roth': True, u'isuid': False, u'isreg': True, u'gid': 0, u'ischr': False, u'wusr': True, u'xoth': False, u'rusr': True, u'nlink': 1, u'issock': False, u'rgrp': True, u'path': u'/usr/share/nginx/html/index.html', u'xusr': False, u'atime': 1505726335.0, u'isdir': False, u'ctime': 1507921431.406413, u'wgrp': False, u'xgrp': False, u'dev': 64776, u'isblk': False, u'isfifo': False, u'mode': u'0644', u'islnk': False})
skipping: [nginx] => (item={u'uid': 0, u'woth': False, u'mtime': 1505726335.0, u'inode': 6297611, u'isgid': False, u'size': 368, u'roth': True, u'isuid': False, u'isreg': True, u'gid': 0, u'ischr': False, u'wusr': True, u'xoth': False, u'rusr': True, u'nlink': 1, u'issock': False, u'rgrp': True, u'path': u'/usr/share/nginx/html/nginx-logo.png', u'xusr': False, u'atime': 1505726335.0, u'isdir': False, u'ctime': 1507921431.407413, u'wgrp': False, u'xgrp': False, u'dev': 64776, u'isblk': False, u'isfifo': False, u'mode': u'0644', u'islnk': False})
skipping: [nginx] => (item={u'uid': 0, u'woth': False, u'mtime': 1505726335.0, u'inode': 6297612, u'isgid': False, u'size': 2811, u'roth': True, u'isuid': False, u'isreg': True, u'gid': 0, u'ischr': False, u'wusr': True, u'xoth': False, u'rusr': True, u'nlink': 1, u'issock': False, u'rgrp': True, u'path': u'/usr/share/nginx/html/poweredby.png', u'xusr': False, u'atime': 1505726335.0, u'isdir': False, u'ctime': 1507921431.407413, u'wgrp': False, u'xgrp': False, u'dev': 64776, u'isblk': False, u'isfifo': False, u'mode': u'0644', u'islnk': False})
TASK [ansible.nginx-container : Clean yum cache] *******************************
 [WARNING]: Consider using yum module rather than running yum
changed: [nginx]
PLAY RECAP *********************************************************************
nginx                      : ok=18   changed=14   unreachable=0    failed=0
Applied role to service	role=ordereddict([('PROXY_LOCATION', '~* /(admin|api)'), ('PROXY_PASS', 'http://django:8080'), ('role', 'ansible.nginx-container'), ('PROXY', 'yes'), ('ASSET_PATHS', ['/tmp/dist'])]) service=nginx
Committed layer as image	image=sha256:214586166d2270ab6d05001153abdb76c4be7dc654532ca48db5c515aeda588c service=nginx
Build complete.	service=nginx
Building service...	project=ansible-container service=postgresql
Service had no roles specified. Nothing to do.	service=postgresql
All images successfully built.
Conductor terminated. Cleaning up.	command_rc=0 conductor_id=101fe3f36ba4e80aa6c33606d978025888a5260ff17f62173a91c906d02e007a save_container=False
(venv) [mcalizo@mcalizo ansible-container]$ 

```

```
