### ISSUE TITLE
Unable to force the use of the default value for log_driver

### ISSUE THREAD

**Issue by pszabop** [ansible/ansible-container#791]
##### ISSUE TYPE
 - Bug Report

##### role.yml 
```
docker_container:
    log_driver: "{{ options.log_driver | default(omit) }}"
    log_options: "{{ options.log_options | default(omit) }}"
```

##### playbook.yml
```
- role: app_server_setup
  options:
        #errors - log_driver: "{{ inventory.log_driver | default(None) }}"
        #errors - log_driver: "{{ inventory.log_driver | default('') }}"
        #errors - log_driver: "{{ inventory.log_driver | default(false) }}"
        #errors - log_driver: "{{ inventory.log_driver }}"
        log_driver: "{{ inventory.log_driver | default('json-file') }}"
        log_options: "{{ inventory.log_options | default({}) }}"

```

##### OS / ENVIRONMENT

```
1: src/server/nodejs $ ansible-container --debug version
Ansible Container, version 0.2.0
Darwin, PAULs-MacBook-Pro.local, 16.7.0, Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64, x86_64
2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] /usr/bin/python
No Ansible Container project data found - do you need to run "ansible-container init"?

```
##### SUMMARY
I'm attempting to force the default for the `log_driver` when my inventory doesn't express an option for a particular `log_driver`.   Normally you use `|default(omit)` to force the default, but that doesn't appear to work for `log_driver`.  If for any inventory possible I want to specify a non-default `log_driver`, I have to specify it for ALL inventories, which is very painful, since the default works for many of the possible inventories.  If I had to do this every inventory would be required to specify the correct value for every conceivable option I might use despite the default being correct most of the time, which can get bad in terms of file size, readability, and maintainability.

I've tried `''`, `()`, `None`, and `false` and (effectively `undefined`), all give errors as illegal value `log_driver`.   or `undefined` (examples above)

I note for many other container options such as the `log_driver` (see above, which is `{}`) a falsey value of the correct type in the playbook seems to work, but not for `log_driver`.

It's possible I'm not understanding how to force a default module option all the way back from an inventory through to the playbook and onto a role, and finally the module, but it's not well documented how to do so, and I've checked docs, stackoverflow, etc.  If you provide an answer I shall cross-post it to stack-overflow.

##### STEPS TO REPRODUCE
Specify the above `log_options` lines in the inventory, playbook, and role for any container, and uncomment the lines that indicate error, they will all give some kind of error whether its `undefined` or `illegal option`.

##### EXPECTED RESULTS
I expected some sort of falsey value to cause the container module to use the default value for `log_driver`, but no falsey value I've tried works.

##### ACTUAL RESULTS
I get an error of either `undefined` or `value of log_driver must be one of: none,json-file,syslog,journald,gelf,fluentd,awslogs,splunk...`

```

```
