### ISSUE TITLE
ports must be specified with mapped port or quoted

### ISSUE THREAD

**Issue by hans-d** [ansible/ansible-container#801]
##### ISSUE TYPE

 - Bug Report
##### container.yml 

```
settings:
  conductor_base: ubuntu:16.04

services:

  squid:
    from: ubuntu:16.04
    roles:
      - squid

    volumes:
      - squid-cache:/var/spool/squid

    ports:
      - 3128

```

##### OS / ENVIRONMENT

```

```
##### SUMMARY

Ports can only be defined as `public:internal`, just having `internal` results in error, or need explicit quotes around the portnumber. Regular docker-compose has no issues with taht

##### STEPS TO REPRODUCE

```
ansible-container build
```

##### EXPECTED RESULTS

Container build

##### ACTUAL RESULTS

(Relevant part of logging)

```
  File "/_ansible/container/utils/__init__.py", line 93, in ports_to_exposed_ports
    exposed_ports = port_spec.rsplit(':')[-1]
AttributeError: 'int' object has no attribute 'rsplit'
```
