### ISSUE TITLE
Intermediate container name error

### ISSUE THREAD

**Issue by chouseknecht** [ansible/ansible-container#818]
##### ISSUE TYPE
 - Bug Report

##### container.yml 
```
version: '2'
settings:

  conductor:
    base: centos:7
    volumes:
    - ${PWD}/static:/static:rw

  project_name: funnels

defaults:
  ng_port: 4200
  postgres_user: funnels
  postgres_password: funnels
  postgres_db: chat

  # role parameters
  user: django
  group: django

services:
  dev:
    from: centos:7
    roles:
      - role: common
        os_packages:
          - https://centos7.iuscommunity.org/ius-release.rpm
      - role: django
      - role: dev
        dev_os_packages:
          - vim
          - make
          - tmux
    ports:
    - '{{ ng_port }}:{{ ng_port }}'
    user: root
    working_dir: /funnels
    entrypoint: [/funnels/scripts/build-dev/entrypoint.sh]
    volumes:
      - ${PWD}:/funnels:rw
    command: ['/funnels/scripts/build-dev/start-dev.sh']
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      - VENV=/venv
      - TMUX
      - FACEBOOK_APP_KEY=519686685031700
      - FACEBOOK_APP_SECRET=817e02cb9860a8a9cec3929d36a62066
      - WITAI_ACCESS_TOKEN=HPSBJEUKVWNWVCQ77UUMPBIWLOD6UYTJ
      - CHAT_WEBHOOK_URL=http://localhost:{{ ng_port }}
      - CHAT_ADMIN_PATH=admin
      - DATABASE_URL=postgres://{{ postgres_user }}:{{ postgres_password }}@postgres:5432/{{ postgres_db }}
      - DJANGO_SETTINGS_MODULE=chat.settings.development
```

##### OS / ENVIRONMENT
```
Ansible Container, version 0.9.3rc0
Darwin, cyclone.local, 16.7.0, Darwin Kernel Version 16.7.0: Wed Oct  4 00:17:00 PDT 2017; root:xnu-3789.71.6~1/RELEASE_X86_64, x86_64
2.7.14 (default, Nov 14 2017, 23:24:24)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.38)] /Users/chouseknecht/.pyenv/versions/2.7.14/envs/venv27/bin/python2.7
{
  "ContainersPaused": 0,
  "Labels": null,
  "CgroupDriver": "cgroupfs",
  "ContainersRunning": 2,
  "ContainerdCommit": {
    "Expected": "06b9cb35161009dcb7123345749fef02f7cea8e0",
    "ID": "06b9cb35161009dcb7123345749fef02f7cea8e0"
  },
  "InitBinary": "docker-init",
  "NGoroutines": 79,
  "Swarm": {
    "ControlAvailable": false,
    "NodeID": "",
    "Error": "",
    "RemoteManagers": null,
    "LocalNodeState": "inactive",
    "NodeAddr": ""
  },
  "LoggingDriver": "json-file",
  "OSType": "linux",
  "HttpProxy": "",
  "Runtimes": {
    "runc": {
      "path": "docker-runc"
    }
  },
  "DriverStatus": [
    [
      "Backing Filesystem",
      "extfs"
    ],
    [
      "Supports d_type",
      "true"
    ],
    [
      "Native Overlay Diff",
      "true"
    ]
  ],
  "OperatingSystem": "Alpine Linux v3.5",
  "Containers": 3,
  "HttpsProxy": "",
  "BridgeNfIp6tables": true,
  "MemTotal": 4139122688,
  "SecurityOptions": [
    "name=seccomp,profile=default"
  ],
  "Driver": "overlay2",
  "IndexServerAddress": "https://index.docker.io/v1/",
  "ClusterStore": "",
  "InitCommit": {
    "Expected": "949e6fa",
    "ID": "949e6fa"
  },
  "GenericResources": null,
  "Isolation": "",
  "SystemStatus": null,
  "OomKillDisable": true,
  "ClusterAdvertise": "",
  "SystemTime": "2017-12-02T23:13:12.528061098Z",
  "Name": "moby",
  "CPUSet": true,
  "RegistryConfig": {
    "AllowNondistributableArtifactsCIDRs": [],
    "Mirrors": [],
    "IndexConfigs": {
      "docker.io": {
        "Official": true,
        "Name": "docker.io",
        "Secure": true,
        "Mirrors": []
      }
    },
    "AllowNondistributableArtifactsHostnames": [],
    "InsecureRegistryCIDRs": [
      "127.0.0.0/8"
    ]
  },
  "DefaultRuntime": "runc",
  "ContainersStopped": 1,
  "NCPU": 4,
  "NFd": 67,
  "Architecture": "x86_64",
  "KernelMemory": true,
  "CpuCfsQuota": true,
  "Debug": true,
  "ID": "ODKF:SEI7:NKVC:PTUK:KBZZ:CJIC:6FF6:EBNK:ENSE:EK7P:A7NN:JQZH",
  "IPv4Forwarding": true,
  "KernelVersion": "4.9.49-moby",
  "BridgeNfIptables": true,
  "NoProxy": "*.local, 169.254/16",
  "LiveRestoreEnabled": false,
  "ServerVersion": "17.09.0-ce",
  "CpuCfsPeriod": true,
  "ExperimentalBuild": true,
  "MemoryLimit": true,
  "SwapLimit": true,
  "Plugins": {
    "Volume": [
      "local"
    ],
    "Network": [
      "bridge",
      "host",
      "ipvlan",
      "macvlan",
      "null",
      "overlay"
    ],
    "Authorization": null,
    "Log": [
      "awslogs",
      "fluentd",
      "gcplogs",
      "gelf",
      "journald",
      "json-file",
      "logentries",
      "splunk",
      "syslog"
    ]
  },
  "Images": 9,
  "DockerRootDir": "/var/lib/docker",
  "NEventsListener": 1,
  "CPUShares": true,
  "RuncCommit": {
    "Expected": "3f2f8b84a77f73d38244dd690525642a72156c64",
    "ID": "3f2f8b84a77f73d38244dd690525642a72156c64"
  }
}
{
  "KernelVersion": "4.9.49-moby",
  "Arch": "amd64",
  "BuildTime": "2017-09-26T22:45:38.000000000+00:00",
  "ApiVersion": "1.32",
  "Version": "17.09.0-ce",
  "MinAPIVersion": "1.12",
  "GitCommit": "afdb6d4",
  "Os": "linux",
  "Experimental": true,
  "GoVersion": "go1.8.3"
}
```
##### SUMMARY

During `build`, when constructing an intermediate container name, we incorrectly assume that a role is a string.

Same for when we attempt to commit a built layer, and add the role name as a `LABEL`. The role that gets passed might not be a string.
