### ISSUE TITLE
Support detached run, stop, and restart

### ISSUE THREAD

**Issue by milky-milk** [ansible/ansible-container#91]
Hello.
Is it possible to use something like `docker-compose -d` or `docker run -d image` with ansible-container? 
I have tried to run a container with nginx with ansible-container, but it exits with `exit 0`
```
version: "1" 
services:
  nginx:
    image: centos:7
    ports:
      - "80:80" 
    command: ['/usr/bin/dumb-init', '/usr/sbin/nginx', '-c', '/etc/nginx/nginx.conf' ]
    volumes:
      - /var/www:/usr/share/nginx/html
```
```
Attaching to ansible_ansible-container_1
Cleaning up Ansible Container builder...
Attaching to ansible_nginx_1
ansible_nginx_1 exited with code 0
```
