### ISSUE TITLE
Feature Idea: Allow for individual Services to be built/run/destroyed

### ISSUE THREAD

**Issue by FearTheBadger** [ansible/ansible-container#934]
##### ISSUE TYPE

 - Feature Idea

##### container.yml 

```
version: "2"
services:
  # Kafka Container
  kafka:
    from: centos:7
    ports:
      - "9092:9092"
    roles:
      - role-kafka
    gather_facts: false
    user: kafka
    command: ['/opt/kafka/bin/kafka-server-start.sh', '/opt/kafka/config/server.properties']

  # Zookeeper Container
  zookeeper:
    from: centos:7
    ports:
      - "2181:2181"
    roles:
      - role-zookeeper
    gather_facts: false
    user: "{{ zoo_user }}"
    command: ['/opt/zookeeper/bin/zkServer.sh', 'start-foreground']

registries: {}
```

##### SUMMARY
It would be great if I could rebuild my Kafka without needing to rebuild my Zookeeper as well. When I'm testing my services I don't need to destroy and rebuild the services that are already running/working. For larger sets of services this becomes time consuming.
